### ISSUE TITLE
November 2022

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#100]
# ToDo

- [x] Settle for a date and location: **Wednesday 2022-11-02 19:15 CET** at C4
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda: Tauri
- [x] Final invitation (deadline **2022-10-26**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/289359494/)
  - [x] [website](https://rust.cologne/2022/11/02/tauri.html)
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: Tauri

Dear Rustaceans,

our next Meetup will be on **Wednesday 2022-11-02, 19:15 CEST**.

As always, we plan to have a friendly get together and talk about the developments in Rust during
the past month.

For Novembers presentation, Florian will show us how to write a simple desktop application using
[Tauri](https://tauri.app).
Tauri is a toolkit for developing desktop applications using web frontend technology.
As such it tries to fill the same niche as Electron. However, all non-frontend code by
application developers is written in Rust. Another major difference from Electron is using the
OS's native web renderer, allowing for much smaller bundle sizes.

The presentation will give a short overview of Tauri and show basic setup as well as development
of a small real world application.

**[You can register here](TODO)**.

We are looking forward to seeing you. :-)

Yours,
Kai and Florian

---

The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.

---

Due to COVID-19 still being around there are some precautions we feel are necessary to make everyone at ease.

We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.

Additionally we generally expect participants to wear masks. During warm weather the venue allows for
decent ventilation. In this case participants may **unanimously** decide masking is not necessary.

```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by Florob** [comment]
@kawogi I've updated the invitation draft, to publish later today.
A quick review would be appreciated.

**Comment by kawogi** [comment]
Looks good to me.
