### ISSUE TITLE
December 2022

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#101]
# ToDo

- [x] Settle for a date and location: **Wednesday 2022-12-07, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **??? T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/290084307/)
  - [x] [website](https://rust.cologne/2022/12/07/advent-of-code.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1600188476548317197)
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: CGN New language features and Advent of Code

Dear Rustaceans,

our next Meetup will be on **Wednesday 2022-12-07, 19:15 CET**.

We will give you an introduction to some new features around the 1.65 release.

The most notable feature will be Generic Associated Types (GAT) which allows using generic type parameters in traits.
Another new language feature is `let … else`, which allows writing certain `if let`-patterns in a more readable manner.
The last feature we'll be talking about is the ability to `break` from a block with a return value.

After this rather theoretical agenda item we'll head over to something more practical:  As a preparation for Christmas we'll have a look at this year's [Advent of Code](https://adventofcode.com/) from a Rustacean's perspective.

As always, you can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
Due to COVID-19 still being around there are some precautions we feel are necessary to make everyone at ease.

We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.

Additionally we generally expect participants to wear masks. During warm weather the venue allows for
decent ventilation. In this case participants may **unanimously** decide masking is not necessary.
```
# Rust News
* [2022 State of Rust Survey](https://blog.rust-lang.org/2022/12/05/survey-launch.html)
* [capnproto-rust 0.15 with GATs](https://dwrensha.github.io/capnproto-rust/2022/11/03/0.15-release.html)
* [async fn in trait MVP in nightly ](https://blog.rust-lang.org/inside-rust/2022/11/17/async-fn-in-trait-nightly.html)

**Comment by Florob** [comment]
Rust 1.65 has been released with GATs, `let-else` and probably other things. Maybe we can come up with content around that.

**Comment by Florob** [comment]
@kawogi What should we put into the announcement (that should be going out today)? Do you have any concrete ideas?
Otherwise, I'd suggest talking about the 1.65 release and general end-of-year-timey mingling.

**Comment by mre** [comment]
Given that it's going to be December, we could do some [Advent of Code](https://adventofcode.com/) with a focus on idiomatic Rust? I do plan on showing up this time. 😆

**Comment by kawogi** [comment]
I was planning to explain some of the recent features, that have been added to 1.65:

- GAT
- `let else` (I think we already covered this this, but doesn't hurt)
- `break` with return values

While GAT might be the most interesting part, I not sure I could explain the topic in a comprehensible manner. But I would give it a try.

I don't think those topics will take much time, so there should be room for some `Advent of Code` as @mre suggested.

Any plans for Glühwein? I'm not sure whether this would be a good idea, given that the COVID numbers are still high-ish.

**Comment by mre** [comment]
Glühwein would be nice and it's sort of a tradition of the meetup, but in light of the pandemic I didn't suggest it. That said I'd still be interested.

**Comment by kawogi** [comment]
@Florob I suggested an agenda for the next meetup. Can you have a look and maybe add the Glühwein-Option?

**Comment by Florob** [comment]
@kawogi Updated with some grammar and other fixes (`break` with return value from `loop` has been stable for over 5 years). I'm also rather hesitant about Glühwein, let's leave it off the announcement.

Can you update Meetup and the website? Otherwise, I'll take care of it this evening.

**Comment by kawogi** [comment]
> `break` with return value from `loop` has been stable for over 5 years

Oops, thanks for fixing!
And thanks for publishing. (would have taken me another two hours before finding the time to do so :/ )

**Comment by mre** [comment]
Hey y'all,
I'll have to chicken out today. 😞 Sorry for the late notice. Hope to see you all again at the start of next year.
