### ISSUE TITLE
January 2023

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#102]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-01-11, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2032-01-04 T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/290743458/)
  - [x] [website](https://rust.cologne/2023/01/11/open-space.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1611061198593695744)
  - [ ] [community calendar]

# Invitation draft

```markdown
Dear Rustaceans,

join our next **open space** style Meetup on **Wednesday 2023-01-11, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting.
It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

We are looking forward to seeing you. :-)

Yours,
Kai and Florian

---

The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.

---

Due to COVID-19 still being around there are some precautions we feel are necessary to make everyone at ease.

We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.

Additionally we generally expect participants to wear masks. During warm weather the venue allows for
decent ventilation. In this case participants may **unanimously** decide masking is not necessary.
```
# Rust News
* [Rust 1.66](https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html)
  + [Detailed Release Notes](https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1660-2022-12-15)
  + Explicit discriminant types
  + `hint::black_box` for benchmarking
  + `cargo remove`
  + `..=X` ranges in patterns
  + [`sym` operands in inline assembly](https://github.com/rust-lang/rust/pull/103168/)
  + Unicode 15

**Comment by kawogi** [comment]
@Florob Do you think we should host the Meetup next week? There were a few smaller changes in the recent release but nothing major imo. We could do a advent-of-code-post-mortem and show some idiomatic Rust.
Alternatively we can move the Meetup to Jan. 25th.

**Comment by Florob** [comment]
@kawogi
> Do you think we should host the Meetup next week?

Probably. I have sent a message to the CCC Cologne list. We should probably wait until tomorrow evening with an actual announcement, in case someone has concerns (I doubt it though).

> There were a few smaller changes in the recent release but nothing major imo.

At least nothing one could spent a longer time talking about.

> We could do a advent-of-code-post-mortem and show some idiomatic Rust.

Personally I got lazy after our meetup, I'm not opposed to the idea though. Could you write up an announcement? Otherwise, I'll propose something tomorrow.

> Alternatively we can move the Meetup to Jan. 25th.

I'd try to avoid that. It only makes the February meetup more stressful.

**Comment by kawogi** [comment]
Then maybe let's just announce an open space this time.

**Comment by Florob** [comment]
Also fine by me. I've updated the announcement text in the issue with what I have ready to commit. Still pretty much the default open space text. Will publish in a bit unless I hear concerns from either the C4 list, or @kawogi by then.
