### ISSUE TITLE
April 2023

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#104]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-04-05, 19:15 CEST** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **??? T - 1 week**)
  - [x] [meetup]
  - [x] [website]
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: Embedded Rust

Dear Rustaceans,

our next Meetup will be on **Wednesday 2023-04-05, 19:15 CEST**.

We'll be showing how Rust can be be run on embedded platforms. Such as: AVR, Raspberry Pi Pico, Raspberry Pi, ARM Cortex, etc.

We will give you an overview of common libraries and how the crates are being organized around the various abstraction levels.

Kai will try to bring some hardware running Rust.

**[You can register here](https://www.meetup.com/rustcologne/events/292561864/)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
Due to COVID-19 still being around there are some precautions we feel are necessary to make everyone at ease.

We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.

Additionally we generally expect participants to wear masks. During warm weather the venue allows for
decent ventilation. In this case participants may **unanimously** decide masking is not necessary.
```
# Rust News
* Rust 1.68
  - [Blog post](https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html)
  - [Detailed release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1680-2023-03-09)
  - Cargo supports a "sparse" protocol for downloading crates.io registry (not default yet)
  - [`pin!()` macro](https://doc.rust-lang.org/stable/std/pin/macro.pin.html)
  - `alloc` specific error handling
* [syn 2.0](https://github.com/dtolnay/syn/releases/tag/2.0.0)

**Comment by kawogi** [comment]
@Florob Can you please proof-read the draft?

**Comment by Florob** [comment]
@kawogi Looks good to me.
