### ISSUE TITLE
May 2023

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#105]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-05-10, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2023-05-03 T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/293321630/)
  - [x] [website](https://rust.cologne/2023/05/10/bring-your-code.html)
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: Bring your code! (and a brief introduction to `serde`)

Dear Rustaceans,

our next Meetup will be on **Wednesday 2023-05-10, 19:15 CET**.

The first part will give you a short overview of the [`serde`](https://crates.io/crates/serde)-crate. Serde is a framework for **serializing and deserializing Rust data structures** efficiently and generically.

For the second part we invite you to solve the attached task and **bring some home-grown code**. It doesn't matter whether your Rust-level is `println!("Hello World!")` or "async webserver on `no_std`". Just give it a try and show your result. You failed on this task? Great! Something to learn for everyone!

**Description of the task**: Write a function that takes the first `n` numbers (`0..n`) and outputs them in the order, they would appear in a dictionary (lexicographic order).

The input `10` would result in the sequence `8, 5, 4, 9, 1, 7, 6, 3, 2, 0` because they would be spelled "eight, five, four, nine, one, seven, six, three, two, zero".

Feel free to fill gaps in this specification with whatever you feel comfortable with. Here are some suggestions:

- print your results to `stdout`, collect them in a `Vec` or return an `Iterator`
- `123405` might become "one hundred twenty-three thousand four hundred five"
- see [Names of large numbers](https://en.wikipedia.org/wiki/Names_of_large_numbers) for event bigger numbers

Depending on how much time is left, we could add some tests, benchmarks, compare memory-footprints, make your solution more generic, …

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by kawogi** [comment]
I guess we should defer the date to 2023-05-10?

Any idea about the agenda? Do we want to give the attendees a little task they can try to solve on their own at home. And then bring their solutions to the meetup to discuss?

**Comment by kawogi** [comment]
Maybe: lexicographically sort a range of numbers in their written form. `0..=9` would result in:
`8, 5, 4, 9, 1, 7, 6, 3, 2, 0`
because: "eight, five, four, nine, one, seven, six, three, two, zero"

This is beginner friendly, doesn't require special knowledge and can be solved in multiple ways. We can add verification of user input. We can also provide test cases, benchmarks and explain how to separate a command line tool from a library function.

**Comment by Florob** [comment]
> I guess we should defer the date to 2023-05-10?

Yes, I think that would be better. Just as a reminder, that is not entirely up to us. There is another group that was pretty adamant they'd be using the room more in the future. I've checked with them that we can have it on the 10th though.

> Any idea about the agenda? Do we want to give the attendees a little task they can try to solve on their own at home. And then bring their solutions to the meetup to discuss?

Sure, we can try how that resonates. Do you think that suffices as agenda, or would that be on top of another program point?
I've been wanting to talk about undefined behavior again for a while. So that might be an idea if we need something else.

> Maybe: lexicographically sort a range of numbers in their written form. 0..=9 would result in:
`8, 5, 4, 9, 1, 7, 6, 3, 2, 0`
because: "eight, five, four, nine, one, seven, six, three, two, zero"

Sounds reasonable. The specification should include what to do about multi-digit numbers though.

**Comment by kawogi** [comment]
> I've checked with them that we can have it on the 10th though.

Sorry, but does that mean the room is available on the 10th or are you waiting for feedback on that matter?

> Do you think that suffices as agenda

I hope so and I'd give it a try. A very brief (30 mins) talk about some random topic might still be a good idea to activate more people. I would imagine that UB deserves more time to talk about and would be a good candidate for a separate meetup. Maybe a short introduction of an interesting crate would fit the bill?

> The specification should include what to do about multi-digit numbers though.

Sure. But I wouldn't mind to keep this a little under-specified, so there's room for discussion and the attendees have an incentive to work on their code on-site. I'll suggest a task description later.

Any opinion about the face-mask rules?

**Comment by Florob** [comment]
> > I've checked with them that we can have it on the 10th though.
>
> Sorry, but does that mean the room is available on the 10th or are you waiting for feedback on that matter?
>
The room is available.

> > Do you think that suffices as agenda
> 
> I hope so and I'd give it a try. A very brief (30 mins) talk about some random topic might still be a good idea to activate more people. I would imagine that UB deserves more time to talk about and would be a good candidate for a separate meetup. Maybe a short introduction of an interesting crate would fit the bill?
> 
Sounds good. How about `serde`? A basic intro should be feasible in ~30mins.

> Any opinion about the face-mask rules?

I think we probably drop them. The group hasn't really opted to keep masks on in month anyway. Incidence and hospitalization are pretty low and dropping. Whether is improving. If that feels more gradual we could also just change the default, asking people to send us a message if they'd prefer masking.

**Comment by kawogi** [comment]
I suggested an agenda and shortened the COVID-footer.
Would you mind to prepare the `serde`-intro?
Another noteworthy alternative would be `clap`.

**Comment by Florob** [comment]
> I suggested an agenda and shortened the COVID-footer.

Thank you. Looks good to me. I've announced the event on Meetup and website.

> Would you mind to prepare the serde-intro?

I'll preper the short intro. Anything I shouldn't forget besides general macro usage and (de-)serialization crates for common formats?

**Comment by kawogi** [comment]
Thank you.

> Anything I shouldn't forget ...

No. I think those are exactly the things that are worth mentioning.
