### ISSUE TITLE
June 2023

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#106]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-06-07, 19:15 CEST** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **2023-05-31 T - 1 week**)
  - [ ] [meetup]
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

```markdown
---
title: "Invalid Argument"
date: 2023-06-07 19:15:00 MESZ
categories: meetup cologne
links:
    "Meetup.com": "TODO"
    "Planning discussion on Github": "https://github.com/Rustaceans/rust-cologne/issues/106"
location: c4
talks:
- title: "clap - Command Line Argument Parser for Rust"
  speaker:
    name: "Kai Giebeler"
    github: kawogi
  abstract: |
    Have you ever written an application but then didn't find the time to document or sanitize the command
    line arguments? Got tired of parsing all those numbers, IP addresses and giving the user proper
    feedback of what they did wrong? In this short introduction we'll learn how to quickly set up a
    user-friendly command line interface for your Rust application using clap.
- title: "Undefined Behavior and Rust"
  speaker:
    name: "Florian Zeitz"
    twitter: florob
    github: florob
  abstract: |
    Undefined behavior and the nasal demons it invokes are a problem in some systems programming
    languages. Rust is virtually free of it in its safe subset. The unsafe subset, however, can
    still invoke undefined behavior. This talk will explore how (unsafe) Rust compares to C in terms
    of its undefined behavior.
---
Dear Rustaceans,

our next Meetup will be on **Wednesday 2023-06-07, 19:15 CEST**.

We will have two talks this time around:

First Kai is going to give a short beginner friendly introduction to the clap crate.
A very flexible user-friendly library for command line argument parsing.

Following that Florian will talk about undefined behavior. Undefined behavior is the bane of many
C programmers existence. What about Rust though? Particularly its unsafe subset.

Later there will be time for open discussions and questions.

**[You can register here](TODO)**.

We are looking forward to seeing you. :-)

Yours,
Kai and Florian
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- Rust 1.70
  + [Blog](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html)
  + [Changelog](https://releases.rs/docs/1.70.0/)

**Comment by damoasda** [comment]
Hi,

@badboy recommended that I inform you via this thread:

Especially for Rust beginners, the **Rust book** by Steve Klabnik and Carol Nichols is very helpful, which is now also available as a German community translation. In addition to the free HTML version on GitHub, I recently published the book as a **paperback** and **e-book** to make it available to as many interested people as possible.

I'm happy to provide the Rust User Group Cologne with the latest e-book for free:
[https://rust-lernen.de/media/2023-03-11-rustbook-de.epub](https://rust-lernen.de/media/2023-03-11-rustbook-de.epub)

I would appreciate reviews on Amazon to make the book even more visible.

Best regards,
Herbert

**Comment by kawogi** [comment]
@damoasda Thanks a lot and sorry for the late reply. We'll make sure it's being mentioned on our next meetup!

Speaking of which: @Florob it's that time again. Any ideas? Another short crate introduction (e.g. `clap`)?

**Comment by Florob** [comment]
> Speaking of which: @Florob it's that time again. Any ideas? Another short crate introduction (e.g. clap)?

@kawogi I would like to talk about undefined behavior. C vs. safe Rust, but also in unsafe Rust. I think that could pair well with a short crate intro. Does that sound reasonable? Would you prepare a clap (or other crate) introduction?

**Comment by kawogi** [comment]
> Would you prepare a clap (or other crate) introduction?

Sure

**Comment by Florob** [comment]
@kawogi I've put an announcement draft in the issue description. Could you proofread and maybe add an abstract for the clap intro?

**Comment by kawogi** [comment]
Done. I just tried to publish this event on meetup but the link https://www.meetup.com/rustcologne/events/293905302 takes me to a 404 page in a private tab. The page only loads in my logged-in browser. Maybe a caching or permission issue? What's your perspective on this?

**Comment by kawogi** [comment]
@Florob This is weird. The previous event https://www.meetup.com/rustcologne/events/293321630/ requires a log-in.
I thought those were visible even without a meetup account? The events are publicly listed on https://www.meetup.com/rustcologne/ but their detail page cannot be accessed by guests.
Do I have to activate `allow guests` in the event's settings?

(I'll update rust.cologne nonetheless)

**Comment by kawogi** [comment]
Looks like it healed itself …
Past events appear to be hidden from guests, but the upcoming one works now.
