### ISSUE TITLE
July 2023

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#107]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-07-05, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2023-06-28**)
  - [x] [meetup]
  - [x] [website]
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: Building web applications with yew / IDEs for Rust development

Dear Rustaceans,

our next Meetup will be on **Wednesday 2023-07-05, 19:15 CEST**.

With good support for WebAssembly in all major Web-Browsers Rust becomes an option for building single page web applications. The Yew-framework strives to give a composable and interactive, yet type safe interface to the DOM. In his talk Tobias will explain several mechanisms offered by Yew to help you build your next single page application in Rust.

The second part will be all about IDEs. You'll learn how to set up a basic development environment for Rust using neovim or VSCode. Feel free show your own setup and discuss what plug-ins are improving your _developer experience_.

**[You can register here](https://www.meetup.com/rustcologne/events/294483447/)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- [Unsafe Rust and Miri by Ralf Jung](https://www.youtube.com/watch?v=svR0p6fSUYY)

**Comment by Florob** [comment]
@kawogi Shall we do short presentations on different IDE/editor setups at next months meetup? I could do (neo)vim. Maybe you could do VS Code? Others could present theirs.

**Comment by belgoking** [comment]
@Florob @kawogi As mentioned at the June meetup, I could give a presentation on single-page-applications with Yew.

**Comment by kawogi** [comment]
@belgoking That would be awesome. Could you give us a very short abstract of what you'll cover in your talk? How do you want to be named in the announcement? Github handle only?

@Florob Sorry, I somehow missed your previous post. Yes, I could give an overview, but It's likely to be very short and boring:
1. install rust + clippy
2. install vscode
3. install rust-analyzer plugin
4. enable clippy in VSCode
5. install some other helpful plugins for Rust-development

Maybe this is a good filler for the evening after the yew talk, because it might spawn a lot of follow-up discussions.

**Comment by kawogi** [comment]
Side note: For the next Meetup I might give an overview of _pattern matching_.

**Comment by Florob** [comment]
@kawogi

> @Florob Sorry, I somehow missed your previous post. Yes, I could give an overview, but It's likely to be very short and boring:
> [snip]
> Maybe this is a good filler for the evening after the yew talk, because it might spawn a lot of follow-up discussions.

Yew + IDE/editor configs sounds reasonable to me. I'd actually prefer if presentations were short. My idea would be that people could "bring their own", following the template:
* How do you set up syntax highlighting? (obviously it's often just build in)
* How do you configure and interact with rust-analyzer? (if supported)
* If LSP is not available, what does your IDE/editor offer instead?
* Any other niceties? (e.g. for neovim people often ask about my non-default diagnostics display)

> Side note: For the next Meetup I might give an overview of pattern matching.

"Next" meaning August I suppose?

**Comment by belgoking** [comment]
@kawogi you can present me with my real name „Tobias Kölsch“

With good support for WebAssembly in all major Web-Browsers Rust becomes an option for building single page web applications. The Yew-framework strives to give a composable and interactive, yet type safe interface to the DOM. This talk presents several mechanisms offered by Yew to help you build your next single page application in Rust.

**Comment by kawogi** [comment]
@Florob @belgoking Can you please review the updated invitation draft in this issue?

**Comment by Florob** [comment]
@kawogi I made some minor changes:
* "this talk" → "his talk", since no talk was previously mentioned.
* "(neo)vim" → "neovim", since I've decided I'm no longer competent to talk about vim, also in the interest of time
* Replaced the COVID section with our more recent version

Otherwise this looks good to me.

**Comment by belgoking** [comment]
@kawogi looks good to me.
