### ISSUE TITLE
August 2023

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#108]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-08-09, 19:15 CET** at C4
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **??? T - 1 week**)
  - [x] [meetup]
  - [x] [website]
  - [ ] [twitter]
  - [x] [community calendar]

# Invitation draft

```markdown
Title: BASIC Rust skills

Dear Rustaceans,

our next Meetup will be on **Wednesday 2023-08-09, 19:15 CEST**.

This time, we'll help the [basic-computer-games](https://github.com/coding-horror/basic-computer-games) project to translate some _very old_ games into Rust. We'll come up with a reasonable pre-selection, but feel free to pick any game you find approachable. Build a team or code alone - it's your choice. Those games were meant to teach programming to newbies, so very basic knowledge to Rust will be sufficient.

The main challenge (and fun!) will be the culture clash between old BASIC spaghetti code and modern idiomatic Rust.

To participate, it is recommended to bring some notebook with a pre-installed rust toolchain.

As usual, you can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](https://www.meetup.com/rustcologne/events/295225790)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- Rust 1.71
  + [ChangeLog](https://releases.rs/docs/1.71.0/)
  + [Blog Post](https://blog.rust-lang.org/2023/07/13/Rust-1.71.0.html)
  + [`*-unwind` ABIs](https://github.com/rust-lang/rfcs/blob/master/text/2945-c-unwind-abi.md#abi-boundaries-and-unforced-unwinding)
  + [debugger visualization attributes](https://doc.rust-lang.org/nightly/reference/attributes/debugger.html#the-debugger_visualizer-attribute)
  + Windows: raw-dylib linking
  + thread locals can now be initialized with `const` expressions (which otherwise are not stable yet)
- Rust 1.71.1: Fixes a `umask` handling related CVE
- [rustfmt now supports `let-else`](https://blog.rust-lang.org/2023/07/01/rustfmt-supports-let-else-statements.html)
  + also new team + policies to prevent such situations
- [Annual Rust Survey Results](https://blog.rust-lang.org/2023/08/07/Rust-Survey-2023-Results.html)

**Comment by kawogi** [comment]
I just stumbled upon this: https://github.com/coding-horror/basic-computer-games
These are some ancient programming exercises. The repo invites to to migrate them into modern programming languages - Rust is among them.

What about doing one/some of these during our meetup?

**Comment by Florob** [comment]
> I just stumbled upon this: https://github.com/coding-horror/basic-computer-games These are some ancient programming exercises. The repo invites to to migrate them into modern programming languages - Rust is among them.
> 
> What about doing one/some of these during our meetup?

I like the idea in theory. We should probably choose some reasonable ones beforehand though. E.g. I had a look at 19_Bunny and it has no description, uses lots of hard to look up ATARI BASIC features, and some of the ports don't actually act correctly. I'd hate to run into that during the meetup.

**Comment by kawogi** [comment]
Alright. I'll try to filter them.

**Comment by kawogi** [comment]
I think those are approachable (I only checked about half of the 50 missing rust implementations):

- https://github.com/coding-horror/basic-computer-games/tree/main/08_Batnum
- https://github.com/coding-horror/basic-computer-games/tree/main/09_Battle
- https://github.com/coding-horror/basic-computer-games/tree/main/20_Buzzword
- https://github.com/coding-horror/basic-computer-games/tree/main/25_Chief
- https://github.com/coding-horror/basic-computer-games/tree/main/26_Chomp
- https://github.com/coding-horror/basic-computer-games/tree/main/34_Digits
- https://github.com/coding-horror/basic-computer-games/tree/main/40_Gomoko
- https://github.com/coding-horror/basic-computer-games/tree/main/44_Hangman

For a quick idea they can be tried here: https://coding-horror.github.io/basic-computer-games/

There's a crate which should simplify some of the original BASIC quirks: https://docs.rs/morristown/0.1.4/morristown/ - we can decide later if we want to use that. Also, I don't think we need to be perfect-to-the character as long as the program follows the description.

So this is mainly interesting for beginners. The more experienced attendees may help the beginners to make their code idiomatic or try to tackle more complex games (tbh - most of the complexity stems from the ancient programming style)

**Comment by kawogi** [comment]
@Florob If you're okay with that agenda, I can try to complete the invitation by tomorrow evening.

**Comment by Florob** [comment]
> @Florob If you're okay with that agenda, I can try to complete the invitation by tomorrow evening.

@kawogi That would be great.

**Comment by kawogi** [comment]
@Florob I completed an invitation draft. Feel free to adjust and publish it. Otherwise I'll do that tomorrow evening.

**Comment by kawogi** [comment]
https://github.com/EmbarkStudios/rust-gpu
https://shadered.org/shaders?language=rust&sort=hot
