### ISSUE TITLE
September 2023

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#109]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-09-13, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2023-09-06 T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/295869748/)
  - [x] [website](https://rust.cologne/2023/09/13/rare-rust.html)
  - [ ] [twitter]
  - [x] [community calendar](https://calendar.google.com/calendar/event?eid=NG84YWl2M3ZzZ21qZGhwNzB1Z29mZ3B1ZHMgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw)

# Invitation draft

```markdown
---
title: "Rare Rust"
date: 2023-09-13 19:15:00 MESZ
categories: meetup cologne
links:
    "Meetup.com": "TODO"
    "Planning discussion on Github": "https://github.com/Rustaceans/rust-cologne/issues/109"
location: c4
---
Dear Rustaceans,

our next Meetup will be on **Wednesday 2023-09-13, 19:15 CEST**.

This September we want to look at the features in Rust that are not used as often.
You may not see them as often, nevertheless you will be happy to know about them when you need them.

Some examples are:
* labeled `break`/`continue`
* higher-kinded types
* pattern matching in unusual places
* path specific visibility
* …

We'll explain a few of them and show example use-cases. If you can think of something that fits the
bill feel free to bring your own examples.

After that we will move to open discussion and mingling.
As usual, you can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](TODO)**.

We are looking forward to seeing you. :-)

Yours,
Kai and Florian
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- Rust 1.72
  - [Release Notes](https://releases.rs/docs/1.72.0/)
  - [Blog Post](https://blog.rust-lang.org/2023/08/24/Rust-1.72.0.html)

**Comment by kawogi** [comment]
Can we move the date to Aug 13? (I might be a little late on that day as well, though)

**Comment by Florob** [comment]
@kawogi I need to ask, but probably yes. Is this going to be a regular occurrence? If so maybe we should generally aim for the 2nd Wednesday. It's a bit unfortunate. I explicitly told people who were making plans at the last meetup that we usually aim for the 1st Wednesday.

**Comment by kawogi** [comment]
It's not a regular thing. Just bad luck with a mandatory school event on a short notice.
I usually keep this date blocked, but sometimes it's not under my control.

There's always the option that the meetup happens without me.

**Comment by Florob** [comment]
Okay, we can do the 13th next month.

**Comment by kawogi** [comment]
I could some live-coding to show how to work with new-types and operator overloading (`Distance / Time → Speed`, Type-safe IDs, …).
And then officially declare the second half to be open for whatever comes up.

**Comment by Florob** [comment]
Do you have a time estimate for that. I recently had an actual use-case for break from labeled block. Which made me think we could maybe have a collection of a little rarer Rust constructs. Would that be plausible to combine with your plans, or do you think new-types would take up to much time?

Otherwise, generally that sounds like a nice idea. We should try to get the announcement out soon so we can end up in next weeks TWiR.

**Comment by kawogi** [comment]
No time estimate, yet. I guess an hour would be appropriate.
But "rare Rust constructs" sound like a very good idea!

Let's try to collect some "rare constructs" here and see if this suffices.

Suggestions:
- break from label
- related: https://doc.rust-lang.org/stable/std/ops/enum.ControlFlow.html
- higher-kinded lifetimes (hard to explain)?
- writing your own hash-Function; switching the Hasher in a HashSet/Map
- destructuring in function arguments
- filling struct fields by copying fields of other structs (using `.. other`)
- locally defined variables, functions, modules, …
- visibility `pub(crate)`, `pub(super)`

**Comment by Florob** [comment]
Let's do that then. I've updated the issue with an announcement draft.
@kawogi Would you review the draft? Do you think it would make sense to split he features among us?

**Comment by kawogi** [comment]
Looks good to me. Will you do the publishing or shall I help you with that?

And yes, let's split them up.

**Comment by Florob** [comment]
I'll publish it and add it to the calendar.

**Comment by kawogi** [comment]
Thanks a lot!

**Comment by Florob** [comment]
> And yes, let's split them up.

@kawogi Maybe we actually should then. I'd call dibs on labelled break and HKTs. Anything you particular want, or don't want, to show?

**Comment by kawogi** [comment]
I'll cover the rest:

- Pattern stuff: destructuring in `$uncommon`; filling struct fields by copying fields of other structs (using `.. other`)
- locally defined variables, functions, modules, …
- visibility pub(crate), pub(super)
- (optional, if I find the time) writing your own hash-Function; switching the Hasher in a HashSet/Map

And then let's improvise on whatever the audience suggests.

**Comment by bnarnold** [comment]
I could contribute a short (10-15 minute) talk on [`GhostCell`](https://plv.mpi-sws.org/rustbelt/ghostcell/) as an example usecase for higher-rank polymorphism.

**Comment by Florob** [comment]
> I could contribute a short (10-15 minute) talk on [`GhostCell`](https://plv.mpi-sws.org/rustbelt/ghostcell/) as an example usecase for higher-rank polymorphism.

I think this would be very interesting. It might be throwing people in at the deep end a bit. However, @kawogi and me should have the more beginner friendly portion of the evening covered, so I think that's fine.
Does GhostCell have any higher-rank polymorphism beyond HRTBs?

**Comment by nwalfield** [comment]
I don't come very often, but I think it would be good to offer something for both beginners and advanced people.  Orthogonally, I'd find a talk about GhostCell very interesting.

**Comment by bnarnold** [comment]
Neat! I agree that `GhostCell` is probably not a great beginner topic, but I think it's a cool way to showcase higher polymorphism, in this case, as you said, through the higher-rank trait bound. If you want to focus on polymorphism over types instead of lifetimes, it's probably not an immediate fit, but the general idea that more general functions give stronger assumptions to the compiler should still get across.

**Comment by kawogi** [comment]
Love to hear some more advanced topics as well!
