### ISSUE TITLE
October 2023

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#110]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-10-04, 19:15 CEST** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **??? T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/296379471/)
  - [x] [website](https://rust.cologne/2023/10/04/open-space.html)
  - [x] community calendar

# Invitation draft

```markdown
Title: Open Space

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday 2023-10-04, 19:15 CEST**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting.
It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- [Rust 1.73](https://releases.rs/docs/1.73.0/) (stable on Oktober 5th, shall we talk about it?)

**Comment by kawogi** [comment]
@Florob Shall we just schedule an open space meetup this time? Maybe explicitly invite the participants to bring their own topics.

**Comment by Florob** [comment]
@kawogi Let's try. Turnout seems to be a dice roll anyway.

**Comment by kawogi** [comment]
Done.
(I'm currently waiting for access to the community calendar …)
