### ISSUE TITLE
November 2023

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#111]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-11-01, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: None)
- [x] Final invitation (deadline **2023-10-25 T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/296540949/)
  - [x] [website](https://rust.cologne)
  - [x] [community calendar](https://www.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)

# Invitation draft

```markdown
Title: Web-applications with axum: Hello CRUD!

Dear Rustaceans,

our next Meetup will be on **Wednesday 2023-11-01, 19:15 CET**.

In this Meetup grouvie will give us an introduction to the web application framework **axum**. First we'll learn how to set up a basic web application in the tradition of a _Hello, World!_ implementation. The second part will cover the creation of a simple ticket system to set a base for real-world applications.

As usual, the remaining time will be available for talking about random topics. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.

```

# Meetup placeholder (maybe add to this template)

```
Dear Rustaceans,

our next Meetup will be on Wednesday 2023-10-01, 19:15 CET.

Topics are yet to be determined. You can make suggestions and requests in our [planning-issue](https://github.com/Rustaceans/rust-cologne/issues/111).

Yours,

Kai and Florian
```

# Rust News
- [new rust release?](https://releases.rs)

**Comment by kawogi** [comment]
@Florob Any ideas for topics, yet?

I don't have any at the moment. `async` has been asked a lot recently but I do not feel that I could have a talk about that.

Maybe we could talk about how `rayon` can be used to easily speed up things. It's something that is easy with Rust but hard in lots of other languages.

**Comment by grouvie** [comment]
Hi. I prepared two example [axum](https://github.com/tokio-rs/axum) applications and we could take a look at them together.
The first one is pretty straightforward; it's a Hello World app that prints request headers.
https://github.com/grouvie/header_test

The second one is a bit more complex. It demonstrates how to create, read, and delete tickets from a list:
https://github.com/grouvie/axum_tickets

Knowing a bit about `async` beforehand will help, as there's `async` and `await` all over the place.
If there's time and interest afterwards, I can also dive into my personal project, which is a bit more extensive.

**Comment by jvytee** [comment]
I'd be very interested in taking a look at some `axum` code :)

**Comment by kawogi** [comment]
@grouvie Sorry for the late reply. Thanks a lot for your input. I'll make that an official announcement then, ok?

The left-over questions about async/await can be tackled in the remaining discussion time :)

**Comment by kawogi** [comment]
@Florob Given that we have the first one on a wait list: shall we send a reminder to the others to revoke their RSVP if they're not going? Or just wait and see what happens?

**Comment by Florob** [comment]
@kawogi Wouldn't hurt to send a reminder I guess. The other option would be increasing the participant count, but from personal experience in the last weeks I wouldn't.
