### ISSUE TITLE
December 2023

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#112]
# ToDo

- [x] Settle for a date and location: **Wednesday 2023-12-06, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: None)
- [x] Final invitation (deadline **T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/297100007/)
  - [x] [website](https://rust.cologne)
  - [x] [community calendar](https://www.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)

# Invitation draft

```markdown
Title: Advent Of Rust

Dear Rustaceans,

our next Meetup will be on **Wednesday 2023-12-06, 19:15 CET**.

It's that time again! After talking about news in Rust of the recent weeks, we'll have a look at this year's [Advent of Code](https://adventofcode.com/) challenges. The first 6 tasks are usually beginner friendly.

Also, there will be `Some(Gluehwein)` (with/out alcohol). You enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](https://www.meetup.com/rustcologne/events/297100007/)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.

```

# Meetup placeholder (maybe add this to default template)

```
Dear Rustaceans,

our next Meetup will be on Wednesday 2023-12-06, 19:15 CET.

Topics are yet to be determined. You can make suggestions and requests in our [planning-issue](https://github.com/Rustaceans/rust-cologne/issues/112).

Yours,

Kai and Florian
```

# Rust News
- [new rust release?](https://releases.rs)

**Comment by Florob** [comment]
For the puns I could show my packet parsing stuff.
I've been meaning to do that for a while. Apart from packet parsing I think it is a good example of slightly advanced real world trait usage.

**Comment by kawogi** [comment]
`let _present = Box::new(Some(())).unwrap();`

Thanks for the proposal. Will we be serving Glühwein this year?
If so, we might want to have a _less serious_ topic and save your talk for a sober audience.

Alternatives I could imagine:
- advent of code
- programming something X-mas-ish

**Comment by mre** [comment]
Long time no see! I still watch this place, even though I didn't manage to visit the events in person lately.
I'd like to mention https://www.shuttle.rs/cch, which could be a complementary, lighthearted activity as well.

**Comment by tbshrst** [comment]
Same goes for me! In the future I want to attend more often.

Beside that, here is another proposal (if we're not too busy with Gluehwein or similar ;) ):

Maybe we could have a (deeper) look into the more intertwined traits that are used throughout the rust language. I'm thinking in particular of the traits from the std::{borrow, convert} modules.

**Comment by kawogi** [comment]
@Florob What's your opinion? Glühwein yes/no? Packet talk or more casual random advent stuff?

**Comment by Florob** [comment]
> @Florob What's your opinion? Glühwein yes/no? Packet talk or more casual random advent stuff?

Definitely Glühwein (and non-alcoholic alternative). I guess casual random advent stuff fits better then.

**Comment by kawogi** [comment]
@Florob I no longer see the option to "announce" the meetup on https://www.meetup.com/rustcologne/events/297100007/
Did they change something? I "Featured" that event, but I'm not sure what this is good for exactly.

Do you know if/how we can get some Rust stickers? I've heard there is demand ;)

**Comment by Florob** [comment]
Thank you for taking care of the announcement @kawogi. I'm sorry I've been so out of the loop lately.

> @Florob I no longer see the option to "announce" the meetup on https://www.meetup.com/rustcologne/events/297100007/ Did they change something? I "Featured" that event, but I'm not sure what this is good for exactly.

I think that might be one of the downsides of having "Save the Date" events. From what I recall you can't explicitly announce them a certain time before the event. I'm not sure if they automatically get announced at that time. I think that used to be the case. If it still is at least organizers apparently don't get a notification.

> Do you know if/how we can get some Rust stickers? I've heard there is demand ;)

I don't. The current trademark policy is apparently:
> Using the Rust trademarks on t-shirts, hats, and other artwork or merchandise, even in modified form, is allowed for your personal use or for use by a small group of community members, as long as they are not sold. If you want to distribute merchandise with Rust Trademarks at a Rust affiliated event, please contact us for permission.

So I suppose anyone selling them is breaking that policy and I'm not aware of anyone giving any away. I guess we could technically get a small batch made though and/or ask the Foundation.

**Comment by kawogi** [comment]
I'll be a little late (+0:30) due to weather issues …

**Comment by fhanrath** [comment]
Thanks for the preparation, Glühwein and the nice evening :)
