### ISSUE TITLE
January 2024

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#113]
# ToDo

- [X] Settle for a date and location: **Wednesday 2024-01-10, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **2024-01-03 T - 1 week**)
  - [ ] [meetup]
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: Game development in Rust

Dear Rustaceans,

our next Meetup will be on **Wednesday 2024-01-10, 19:15 CET**.

This time we'll talk about game development in Rust. We'll address questions like: What are Rust's strengths and weaknesses when it comes to writing a game or an engine? What parts can be used off-the-shelf and what parts are still in the works? Which platforms are supported, which are missing? Are there any notable games written in Rust, yet?

Kai will show a little 3D-demo written in Rust + wgpu which runs natively on the system and in the browser.

Did you try to create a game or an engine on your own? Let us know how it turned out!

You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- [new rust release?](https://releases.rs)

**Comment by Florob** [comment]
Tentative idea for the meetup was Rust game engines.

I'll try to get us the 2nd Wednesday (January 10th) again, assuming that people would not want to attend a meetup even closer to new year. Does that work for you @kawogi?

**Comment by kawogi** [comment]
Jan 10th sounds good. I think I can come up with some content for "rust-gaming".

**Comment by kawogi** [comment]
@Florob Are we ready to send an invitation?

**Comment by Florob** [comment]
> @Florob Are we ready to send an invitation?

I think so. The 10th is cleared. I suppose you have the details on what exactly "rust-gaming" means.

**Comment by kawogi** [comment]
For some definition of "exactly" :)
I'll prepare something.

**Comment by kawogi** [comment]
@Florob Do you remember who offered to talk about "Bevy" at the last meetup?
Hope the announcement is ok. I kept it a little vague because the precise topics will be very likely determined by the participants.

**Comment by Florob** [comment]
> @Florob Do you remember who offered to talk about "Bevy" at the last meetup? Hope the announcement is ok. I kept it a little vague because the precise topics will be very likely determined by the participants.

I think @grouvie offered to talk about Bevy, but I might be misremembering.

The announcement looks good to me. I'll add it to Meetup and the website.

**Comment by kawogi** [comment]
Given that we're already overbooked, the expectations in this meetup might exceed my preparations XD
I'll ask on meetup if there are special interests or offers for a talk.

**Comment by grouvie** [comment]
I completely forgot about Meetup. :sweat_smile: 
I would be happy to give an introduction to Bevy and show some of the stuff I played around with. :)

**Comment by kawogi** [comment]
@grouvie Very appreciated!

**Comment by grouvie** [comment]
I have found out why exactly the Without was necessary in the one Query. It's a typical Rust explanation. :D

https://bevy-cheatbook.github.io/programming/paramset.html

**Comment by kawogi** [comment]
That totally makes sense in hindsight! Thanks for looking it up.
