### ISSUE TITLE
February 2024

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#114]
# ToDo

- [ ] Settle for a date and location: **Wednesday 2024-02-07, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **2024-01-31 T - 1 week**)
  - [ ] [meetup]
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday YYYY-MM-DD, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting.
It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- [new rust release?](https://releases.rs)

**Comment by kawogi** [comment]
@Florob Do you want hold you packet talk on this meetup?

**Comment by Florob** [comment]
> @Florob Do you want hold you packet talk on this meetup?

I think I'd prefer presenting a version that is a bit cleaner than what I have now.
However, I would like to talk about the embedded-hal 1.0 release. Or rather, revisit the embedded Rust ecosystem on this occasion. Probably going a bit more in the direction of drivers than you did last time around.

**Comment by kawogi** [comment]
Sounds good to me. Could you write the invitation for that?

**Comment by grouvie** [comment]
I set up one of my projects as a cargo workspace and build/ run the rust binaries/ libraries with [bazel](https://bazel.build/). Bazel for sure is not useful for most people, but cargo workspaces might be something interesting to take a quick look at.

**Comment by Florob** [comment]
> I set up one of my projects as a cargo workspace and build/ run the rust binaries/ libraries with [bazel](https://bazel.build/). Bazel for sure is not useful for most people, but cargo workspaces might be something interesting to take a quick look at.

I'm a bit confused. Looking at bazel (or rather the rust rules for it) I'm under the impression that it does not use cargo, except for non-local dependencies. So I don't see how cargo workspaces could be related.

If you want to do a quick intro to cargo workspaces that would be great.

**Comment by grouvie** [comment]
You can use it without cargo. Probably nice for companies with mono repos where not every dev wants to install cargo but still run rust applications. I have bazel setup in a way to use my cargo workspace for the build dependencies.

**Comment by kawogi** [comment]
Thank you both!
