### ISSUE TITLE
March 2024

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#115]
# ToDo

- [X] Settle for a date and location: **Wednesday 2024-03-06, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [X] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **??? T - 1 week**)
  - [x] [meetup](https://www.meetup.com/de-DE/rustcologne/events/299530888/)
  - [x] [website](https://rust.cologne/2024/03/06/macros-by-simple-example.html)
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: Macros by simple Examples

Dear Rustaceans,

our next Meetup will be on **Wednesday 2024-03-06, 19:15 CET**.

Florob will give you a introduction on Macros by Example. You'll learn how they work, what they are good for and what their limitations are. We'll talk about the differences to C-macros and other macros techniques Rust has to offer (proc and derive macros).

In the remaining time we'll talk about whatever Rust-related topic you like. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- [new rust release?](https://releases.rs)

**Comment by kawogi** [comment]
Wanna try to make the "Open Space" more attractive?

Maybe we could be more detailed on the options:

- Live-coding
- Explain recent changes in the compiler
- Write idiomatic code
- Performance optimizations
- …

Something that's always kind of valid but triggers more people than just saying: _Something about Rust_

**Comment by kawogi** [comment]
@Florob Any idea about the agenda for the upcoming week?

**Comment by Florob** [comment]
@kawogi Unfortunately not really. I was thinking I could talk about macro by example macros. Just basic usage though, not brain bending token munchers. I think that'd amount to at least half a meetup.

**Comment by kawogi** [comment]
That would be great. I'm certain we can fill the other half with a spontaneous topic.
Would you write a matching invitation?

**Comment by kawogi** [comment]
@Florob I suggested an invitation text. Can you have a look, soon?

**Comment by Florob** [comment]
@kawogi Thank you. I wouldn't have gotten around to it until this evening. Text looks mostly good to me. I made some minor edits.

**Comment by Florob** [comment]
@kawogi: Just to avoid collisions: I'll add the invitation to meetup and the website now. Thanks again for writing the invitation.
