### ISSUE TITLE
April 2024

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#116]
# ToDo

- [#] Settle for a date and location: **Wednesday 2024-04-10, 19:15 CEST** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2023-04-10 T - 1 week**)
  - [x] [meetup](https://www.meetup.com/de-DE/rustcologne/events/300191375/)
  - [x] [website](https://rust.cologne/2024/04/10/this-month-in-rust.html)
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

## This Month In Rust, April

_(The meetup will likely be held in German but we'll switch to English if needed.)_

Dear Rustacean,

our next Meetup will be on **Wednesday 2024-04-10, 19:15 CEST**.

You're new to Rust, tried it out with some private projects or are already working professionally with it for years? You're in good company! Whether you want to speed up your python code, write a web service, need interop with your C++-codebase, cross-compile for a microcontroller, write an emulator, … we've got you covered!

We commonly open up with a brief summary of noteworthy changes in the Rust ecosystem. Be it updates to the language itself, public events, its impact on other projects and languages, …

After that we often have volunteers talking about specific topics or personal projects, but in general the remaining time is about whatever _you_ want to talk about!

Always wanted to know why Rust is harder to learn than other popular languages or why it lacks a certain feature? When is it appropriate to rewrite a project in Rust? Is the compiler really that slow and are the binaries really that big? Do all those safety guarantees have an impact on the performance? Fetch a drink and let's find it out.

**[You can register here](...)**.

See you soon!

Yours,
Florian and Kai
- - -
If you have a topic you'd like to talk about, please [let us know in advance](…). This way we can make sure there's a time slot for you and maybe announce it officially. Thank you.

# Rust News
- Rust 1.77.0
    + [Blog Post](https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html)
    + [Release Notes](https://releases.rs/docs/1.77.0/)
    + C-string literals: `c"hello world"` with type `&'static CStr`
    + `async` functions can now be called recursively (if their type does not become recursive as a consequence)
    + `offset_of!(StructName, field)`
    + strip by default in release profiles (libstd is shipped with debug symbols)
- Rust 1.77.1
    + Disables stripping for MSVC windows (apparently always uses a separate file anyway)
- Rust 1.77.2
    + CVE: `Command` arguments not sufficiently escaped on Windows
    + Windows API + cmd.exe weirdness
    + [Context](https://flatt.tech/research/posts/batbadbut-you-cant-securely-execute-commands-on-windows/)

**Comment by kawogi** [comment]
@Florob  I won't be able to attend on the 3rd of April.
I could be there on the 10th of April, but if any preparation from my side is needed I have to complete it during the course of the upcoming week.

Maybe just an open space with an improved description?

**Comment by Florob** [comment]
@kawogi I'd be more than happy to move it up to the 10th. That way I also don't have a meeting immediately preceding the meetup. I'll confirm with the space tomorrow, but since the conflicting meetup no longer exists I don't think it'll be a problem.
We can try open space with improved description. Would you want to draft an invitation for that?

**Comment by Florob** [comment]
Forgot to update this issue. As expected we can do April 10th.

**Comment by kawogi** [comment]
@Florob I took the liberty to suggest something completely new from scratch and your feedback is appreciated.

The general structure is (even though it's mostly obvious):

- metadata (date, topic)
- appetizer
- agenda (transitioning from formal to open space)
- invitation
- footer

I tried to include some common topics, interests and pre-Rust experiences to make it easier for people to check whether this their cup of tea and maybe lower the bar to participate. The examples aim to make it interesting, yet generic enough to not have the obligation to prepare anything specific.

If we have a talk to offer it should easily fit into the draft without having to re-write the most of it.

I removed the COVID-disclaimer because the topic didn't come up in the recent months. OTOH I added a general invitation to support us with talks.

I removed the markdown-codeblock so that it's easier to preview on GitHub.

I moved the _language selection algorithm_ to the top to hopefully lower the barrier for people who feel their English skills might not be sufficient.

**Comment by kawogi** [comment]
Do you want to permanently move to the second Wednesday if that's less stressful for you?

**Comment by kawogi** [comment]
@Florob Can I get your feedback soon?

**Comment by Florob** [comment]
> @Florob Can I get your feedback soon?

 @kawogi Sorry, my days have been rather long lately. I like the text. Thank you for putting in the time. I'm not entirely sure what the general part and the meetup specific bit is, but we can discuss that at another time.

> Do you want to permanently move to the second Wednesday if that's less stressful for you?

I thought about that, but since one is "every other week" and the other "every nth Wednesday" it turns out that wouldn't really change much long term.
