### ISSUE TITLE
June 2024

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#118]
# ToDo

- [x] Settle for a date and location: **Wednesday 2024-06-05, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **??? T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/301423137/)
  - [x] [website](https://rust.cologne/2024/06/05/getting-started.html)
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

## June: Getting started with Rust

_(The meetup will likely be held in German but we'll switch to English if needed.)_

Dear Rustaceans,

join us for our upcoming Rust Meetup on **Wednesday 2024-06-05, 19:15 CEST**.

If you've been waiting to explore Rust, this is your opportunity!
This month's meetup will feature an introductory talk about Rust, showcasing its approach to combining speed with safety, while eliminating many common errors found in other low-level languages.

After that there will be time to answer questions, discuss Rust, or just fetch a drink and mingle.

**[You can register here](...)**.

See you soon!

Yours,
Florian and Kai
- - -
If you have a topic you'd like to talk about, please [let us know in advance](https://github.com/Rustaceans/rust-cologne/issues/118). This way we can make sure there's a time slot for you and maybe announce it officially. Thank you.
# Rust News
- [Rust 1.78](https://releases.rs/docs/1.78.0/)
    + [Blog Post](https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html)
    + [Release Notes](https://releases.rs/docs/1.78.0/)
- [Blog: "The borrow checker within"](https://smallcultfollowing.com/babysteps/blog/2024/06/02/the-borrow-checker-within/)
- [Softwerkskammer @ REWE digital: Testing in Rust](https://www.meetup.com/softwerkskammer-koln/events/300415441/) on June 10th

**Comment by Florob** [comment]
It's already getting awfully late for this month meetup invitation. I would still like to keep it on the 5th as the 12th is fairly inconvenient for me.
I would like to give a basic introductory talk to Rust. We once said we'd do that about once a year, and it looks like the last time was at our physical reboot (2022).

@kawogi Can you review the invitation draft in the issue description?

**Comment by grouvie** [comment]
Looking good! Have been lurking here every day for the next announcement. :D

**Comment by kawogi** [comment]
> @kawogi Can you review the invitation draft in the issue description?

Thanks for caring and sorry that I didn't find the time to do this by myself :(

Announcement looks good to me.

When I get home, I'll try to inform the participants of the May-meetup about the event. Maybe this way we can get some more attention.
