### ISSUE TITLE
July 2024

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#119]
# ToDo

- [X] Settle for a date and location: **Wednesday 2024-07-03, 19:15 CEST** at C4 (default: first Wednesday each month)
- [X] Send "Save the Date" info (with link to this ticket)
- [X] Basic Agenda (default: Open Space)
- [X] Final invitation (deadline **2023-06-26 T - 1 week**)
  - [X] [meetup]
  - [x] [website]
  - [ ] [community calendar]

# Invitation draft

## Rust in July: Gam3du - a Game Engine to learn programming

_(The meetup will likely be held in German but we'll switch to English if needed.)_

Dear Rustacean,

our next Meetup will be on **Wednesday 2024-07-03, 19:15 CEST**.

You're new to Rust, tried it out with some private projects or are already working professionally with it for years? You're in good company! Whether you want to speed up your python code, write a web service, need interop with your C++-codebase, cross-compile for a microcontroller, write an emulator, … we've got you covered!

We commonly open up with a brief summary of noteworthy changes in the Rust ecosystem. Be it updates to the language itself, public events, its impact on other projects and languages, …

Then Kai will give a short introduction about the newly started [`Gam3du`](https://github.com/gam3du/gam3du)-project. The project's goal is to serve as an open source platform and ecosystem to teach and learn programming on all levels: Scripting, shaders, systems programming, cross platform development, web technologies, networking, …. Even though it's still in an very early PoC stage, it can already be used for very simple tasks.

As usual: the remaining time is about whatever _you_ want to talk about!

Always wanted to know why Rust is harder to learn than other popular languages or why it lacks a certain feature? When is it appropriate to rewrite a project in Rust? Is the compiler really that slow and are the binaries really that big? Do all those safety guarantees have an impact on the performance? Fetch a drink and let's find it out.

**[You can register here](...)**.

See you soon!

Yours,
Florian and Kai
- - -
If you have a topic you'd like to talk about, please [let us know in advance](https://github.com/Rustaceans/rust-cologne/issues/119). This way we can make sure there's a time slot for you and maybe announce it officially. Thank you.

# Rust News
- Rust 1.79
  - [Blog Post](https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html)
  - [Release Notes](https://doc.rust-lang.org/nightly/releases.html#version-1790-2024-06-13)

**Comment by kawogi** [comment]
I started working on an educational game engine written in Rust with some students and teachers: https://github.com/gam3du/gam3du
There's not a lot to show, yet but I can certainly talk about the current state and maybe make this a discussion topic for the evening.

**Comment by kawogi** [comment]
@Florob If you don't have anything to add to the agenda I'll try to motivate me to send an invitation in time :)

**Comment by Florob** [comment]
> @Florob If you don't have anything to add to the agenda I'll try to motivate me to send an invitation in time :)

I have nothing to add. Indeed it would be good to get the invitation out early.

**Comment by grouvie** [comment]
Looking forward to it. :)

Was the presentation from last month uploaded somewhere? @Florob

**Comment by Florob** [comment]
> Was the presentation from last month uploaded somewhere? @Florob

Yes, they're at [RC-2024-06-05-rust-intro.pdf](http://babelmonkeys.de/~florob/talks/RC-2024-06-05-rust-intro.pdf). Now also linked from [rust.cologne](https://rust.cologne/2024/06/05/getting-started.html).

**Comment by grouvie** [comment]
Fun project that reminded me of one of your ideas @kawogi 
https://github.com/patryk27/kartoffel

**Comment by grouvie** [comment]
Forgot about this during the meetup, but this also was quite interesting.
https://blog.devgenius.io/master-rust-by-playing-video-games-cf5f7d8b1e28
