### ISSUE TITLE
August 2024

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#120]
# ToDo

- [ ] Settle for a date and location: **Wednesday 2024-08-14, 19:15 CEST** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2024-07-31 T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/302674635/)
  - [x] [website](https://rust.cologne/2024/08/14/this-month-in-rust.html)
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday YYYY-MM-DD, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting.
It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- [Rust Project goals for 2024H2](https://blog.rust-lang.org/2024/08/12/Project-goals.html)
- [withoutboats blog posts](https://without.boats/blog/)
- [Rust 1.80.0](https://releases.rs/docs/1.80.0/)
- [Rust 1.80.1](https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html)

**Comment by kawogi** [comment]
@Florob Too late for announcing a meetup for this Wednesday?
I'm super busy at the moment so I wouldn't mind if we skip this month.

**Comment by Florob** [comment]
@kawogi Not sure if there really is a too late. I've also been busy, away on a work trip etc. I wouldn't particularly mind skipping this month. We can also try to move it to next week, would that be better for you? Rust 1.80 certainly has various things to talk about, so that might be sufficient as topic.

**Comment by kawogi** [comment]
Moving to next week would be ok - would you confirm the reservation with the C4?

We'll send a standard invitation I guess?

**Comment by Florob** [comment]
I'll confirm, not before Tuesday evening though. But then we're at least announcing a week before the event. Probably a standard announcement, maybe a short mention of the release.

**Comment by kawogi** [comment]
Thanks a lot for scheduling!

**Comment by grouvie** [comment]
Found these weird rust expressions:
https://github.com/rust-lang/rust/blob/master/tests/ui/weird-exprs.rs

And a quiz on some similar things:
https://dtolnay.github.io/rust-quiz/

**Comment by kawogi** [comment]
I failed the first two tests - it can only get better :D

**Comment by Florob** [comment]
One more https://www.reddit.com/r/rust/comments/8p013f/rusty_riddle_what_does_it_print/
