### ISSUE TITLE
September 2024

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#121]
# ToDo

- [x] Settle for a date and location: **Wednesday 2024-09-11, 19:15 CEST** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2024-08-28 T - 1 week**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/303259164)
  - [x] [website](https://rust.cologne/2024/09/11/more-than-a-filter.html)
  - [ ] [twitter]
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday 2024-09-04, 19:15 CEST**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting.
It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
COVID-19 measures: We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.
Feel free to privately send us a message if you think that more safety measures are required.
```
# Rust News
- [RustConf 2024](https://rustconf.com/)
- [2024 Leadership Council Survey Results](https://blog.rust-lang.org/2024/08/26/council-survey.html)
- [Embedded WG Survey](https://blog.rust-lang.org/inside-rust/2024/08/22/embedded-wg-micro-survey.html)
- [Async Closures MVP: Call for Testing](https://blog.rust-lang.org/inside-rust/2024/08/09/async-closures-call-for-testing.html)
- [Ralf Jung: What is a place expression?](https://www.ralfj.de/blog/2024/08/14/places.html)
- [Save the Date: Rust All Hands 2025](https://blog.rust-lang.org/inside-rust/2024/09/02/all-hands.html)

**Comment by kawogi** [comment]
Can we move this to the 11.09.? I might not be able to attend on the 04.09.

**Comment by Florob** [comment]
> Can we move this to the 11.09.? I might not be able to attend on the 04.09.

Probably. I'll know tomorrow evening.

**Comment by mdm** [comment]
I started preparing a talk on "Exploring eBPF with Rust". The idea is to have a short intro to eBPF in general (that part is mostly finished) and then look at some examples written in Rust (still working on that). I'm aiming at around 30 minutes, but the nature of the second part might make it a little bit more open-ended. 11.09. would be more comfortable for me, too, though.

**Comment by Florob** [comment]
As expected, the 11th is fine. So let's move the meetup then.

**Comment by SantaClaas** [comment]
There is an embedded Rust micro survey currently running which might be worth shouting out for anyone who has feelings about embedded Rust. It runs until September 19th.

[Survey](https://www.surveyhero.com/c/uenp3ydt)
[Blog](https://blog.rust-lang.org/inside-rust/2024/08/22/embedded-wg-micro-survey.html)

**Comment by jvytee** [comment]
> I started preparing a talk on "Exploring eBPF with Rust". The idea is to have a short intro to eBPF in general (that part is mostly finished) and then look at some examples written in Rust (still working on that).

I'd be interested in that topic! :)

**Comment by kawogi** [comment]
@mdm Are we ready to announce your eBPF talk?

**Comment by mdm** [comment]
> @mdm Are we ready to announce your eBPF talk?

Sure. I finished preparing it. Do you need more details than the title to announce it?

**Comment by Florob** [comment]
> > @mdm Are we ready to announce your eBPF talk?
> 
> Sure. I finished preparing it. Do you need more details than the title to announce it?

A short abstract would be helpful.

**Comment by mdm** [comment]
Exploring eBPF with Rust

eBPF is a technology that allows small programs to run inside the operating system kernel. Common applications are in networking, security, and observability. The talk will give a short, general introduction to eBPF and then dive into a few concrete examples written in Rust leveraging the tooling developed by the Aya project.

**Comment by Florob** [comment]
Meetup is announced on website and meetup (links in the issue).
Thanks @mdm for the talk and abstract.

**Comment by kawogi** [comment]
Thank you all!

**Comment by grouvie** [comment]
https://rust-book.cs.brown.edu/experiment-intro.html

Interesting rust book alternative with quizzes.

And aquascope is quite interesting, too.

https://cel.cs.brown.edu/aquascope/

**Comment by grouvie** [comment]
Totally forgot this yesterday. 
Played this a few month ago. It's really well made.

https://oort.rs/
