### ISSUE TITLE
October 2024

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#122]
# ToDo

- [x] Settle for a date and location: **Wednesday 2024-10-02, 19:15 CEST** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: "This Month in Rust")
- [x] Final invitation (deadline **T - 10 days**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/303646676)
  - [x] [website](https://rust.cologne)
  - [ ] [community calendar]

# Invitation draft

Title: This Month in Rust, October

_(The meetup will likely be held in German but we'll switch to English if needed.)_

Dear Rustacean,

our next Meetup will be on **Wednesday 2024-10-02, 19:15 CEST**.

You're new to Rust, tried it out with some private projects or are already working professionally with it for years? You're in good company! Whether you want to speed up your python code, write a web service, need interop with your C++-codebase, cross-compile for a microcontroller, write an emulator, … we've got you covered!

We commonly open up with a brief summary of noteworthy changes in the Rust ecosystem. Be it updates to the language itself, public events, its impact on other projects and languages, …

After that we often have volunteers talking about specific topics or personal projects, but in general the remaining time is about whatever _you_ want to talk about!

Always wanted to know why Rust is harder to learn than other popular languages or why it lacks a certain feature? When is it appropriate to rewrite a project in Rust? Is the compiler really that slow and are the binaries really that big? Do all those safety guarantees have an impact on the performance? Fetch a drink and let's find it out.

**[You can register here](https://www.meetup.com/rustcologne/events/303646676)**.

See you soon!

Yours,
Florian and Kai
- - -
If you have a topic you'd like to talk about, please [let us know in advance](https://github.com/Rustaceans/rust-cologne/issues/122). This way we can make sure there's a time-slot for you and maybe announce it officially. Thank you.

# Rust News
- [new rust release?](https://releases.rs)

**Comment by Florob** [comment]
Looks like we've been busy with other things again.
@kawogi Shall we go for a standard/"open space" announcement?

**Comment by kawogi** [comment]
Yes. I'll do the announcement (with the other not yet saved template).

**Comment by kawogi** [comment]
I finally updated that template. The draft is in rendered markdown now which should make it easier to copy the formatted version over to Meetup.

Also I upped the meetup duration from 2 to 3 hours, which seems more realistic in my experience.
The start time in Meetup was set to 19:00 somehow - I changed that back to 19:15. Hope this is ok.

**Comment by kawogi** [comment]
(Note to myself) Topic suggestions:

- How to destructure a `Vec`?
- How to reduce dependencies?
- Talk about "mystery segfault in debug mode"
