### ISSUE TITLE
This Month in Rust, `November 2024`

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#123]
# ToDo

- [x] Settle for a date and location: **Wednesday 2024-11-06, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: "This Month in Rust")
- [x] Final invitation (deadline **T - 10 days**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/####)
  - [x] [website](https://rust.cologne)
  - [ ] [community calendar]

# Invitation draft

Title: This Month in Rust, `November`

_(The meetup will likely be held in German but we'll switch to English if needed.)_

Dear Rustacean,

our next Meetup will be on **Wednesday 2024-11-06, 19:15 CET**.

You're new to Rust, tried it out with some private projects or are already working professionally with it for years? You're in good company! Whether you want to speed up your python code, write a web service, need interop with your C++-codebase, cross-compile for a microcontroller, write an emulator, … we've got you covered!

We'll talk about the [new Rust release](https://releases.rs/docs/1.82.0/) and other noteworthy changes in the Rust ecosystem. Be it updates to the language itself, public events, its impact on other projects and languages, …

After that we often have volunteers talking about specific topics or personal projects, but in general the remaining time is about whatever _you_ want to talk about!

Always wanted to know why Rust is harder to learn than other popular languages or why it lacks a certain feature? When is it appropriate to rewrite a project in Rust? Is the compiler really that slow and are the binaries really that big? Do all those safety guarantees have an impact on the performance? Fetch a drink and let's find it out.

**[You can register here](https://www.meetup.com/rustcologne/events/####)**.

See you soon!

Yours,
Florian and Kai
- - -
If you have a topic you'd like to talk about, please [let us know in advance](https://github.com/Rustaceans/rust-cologne/issues/####). This way we can make sure there's a time-slot for you and maybe announce it officially. Thank you.

# Rust News
- [new rust release?](https://releases.rs)

**Comment by kawogi** [comment]
@Florob default invitation or do you have some topic in mind?

**Comment by Florob** [comment]
@kawogi Default invitation I think. Maybe mention the new release?

**Comment by SantaClaas** [comment]
Maybe newsworthy: [Announcing Toasty, an async ORM for Rust](https://tokio.rs/blog/2024-10-23-announcing-toasty) from Tokio

**Comment by grouvie** [comment]
https://crates.io/crates/thiserror (v2.0.0)
