### ISSUE TITLE
This Month in Rust, December 2024

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#124]
# ToDo

- [X] Settle for a date and location: **Wednesday 2024-12-04, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: "This Month in Rust")
- [ ] Final invitation (deadline **T - 10 days**)
  - [ ] [meetup](https://www.meetup.com/rustcologne/events/####)
  - [ ] [website](https://rust.cologne)
  - [ ] [community calendar]

# Invitation draft

Title: Rust in December: Advent of Code

_(The meetup will likely be held in German but we'll switch to English if needed.)_

Dear Rustacean,

our next monthly Meetup will be on **Wednesday 2024-12-04, 19:15 CEST**.

You're new to Rust, tried it out with some private projects or are already working professionally with it for years? You're in good company! Whether you want to speed up your python code, write a web service, need interop with your C++-codebase, cross-compile for a microcontroller, write an emulator, … we've got you covered!

We open up with a brief summary of noteworthy changes in the Rust ecosystem. Be it updates to the language itself, public events, its impact on other projects and languages, …

After that there will be **Glühwein**! Ah, and we'll have a look at the **[Advent of Code puzzles](https://adventofcode.com/)**. This is expected to be a very beginners-friendly topic and you're invited to compare the solutions in Rust with any other programming language you're familiar with.

**[You can register here](https://www.meetup.com/rustcologne/events/304760521)**.

See you soon!

Yours,
Florian and Kai
- - -
If you have a topic you'd like to talk about, please [let us know in advance](https://github.com/Rustaceans/rust-cologne/issues/124). This way we can make sure there's a time-slot for you and maybe announce it officially. Thank you.

# Rust News
- [new rust release?](https://releases.rs)

**Comment by kawogi** [comment]
@Florob usual data/time/agenda for December? Shall we announce this early (if you think the draft is ok)?

(I'll double-check with my calendar, but I think it'll be ok)

**Comment by Florob** [comment]
@kawogi I'd be fine with announcing soon-ish. Announcement looks good to me.
Aside: Can you think of a way to make the month specific part stand out a bit more? I think that would improve things for regular visitors/invitation readers.

**Comment by kawogi** [comment]
Do you need help or financial support with the Glühwein-logistics?

**Comment by Florob** [comment]
> Do you need help or financial support with the Glühwein-logistics?

Not with actually acquiring the beverages, but it turns out I'll have to be in a meeting the hour immediately preceding the meetup. So if you could turn up a bit earlier to get started heating up the Glühhwein that would help.

**Comment by kawogi** [comment]
I'll do my best. Fingers crossed that DB is on time for once …

**Comment by grouvie** [comment]
I'm looking forward to your day 2 part 2 solution without bruteforcing it. @kawogi :D

**Comment by kawogi** [comment]
Dang, I just opted for brute-forcing 😂
Maybe I invest some more time to provide a better solution.

**Comment by kawogi** [comment]
Thanks for holding my beer @grouvie  :smirk: 
I'll bring a solution that is single-pass, streaming, allocation-free, multi-threaded, almost readable, O(n) complexity, has unit tests and is cool in general :sunglasses:

See you then.

**Comment by kawogi** [comment]
@Florob looks like several trains will no be operating on Wednesday. I'll do my best, but I might not make it in time.
Maybe people will just have to wait a little longer for their beverage or just opt for the microwave then - no stress ;)

**Comment by Abdull** [comment]
at which time are doors open?

**Comment by kawogi** [comment]
around 19:00

**Comment by kawogi** [comment]
I'd be interested in a cleaner solution for Day 3 Part 2

**Comment by SantaClaas** [comment]
Random thing I saw https://github.com/michidk/rost 😆

**Comment by grouvie** [comment]
I first used nom for day 3 and then was convinced to switch to winnow. Was told the performance is 30% better. :D
My solution probably also isn't that clean, but very readable.
https://github.com/grouvie/aoc_24/blob/master/three%2Fsrc%2Fmain.rs#L53

**Comment by kawogi** [comment]
@grouvie My solution of day 2, Part 2 as promised:

```rust
#![warn(clippy::pedantic)]

use rayon::{iter::ParallelIterator, str::ParallelString};

const MAX_DIFF: i64 = 3;

/// Using an enum instead of an integer to make reasoning about possible states easier
#[derive(Default, Clone, Copy)]
enum FillLevel {
    #[default]
    Empty,
    One,
    Full,
}

#[derive(Debug, Default, PartialEq, Clone, Copy)]
enum Fix {
    #[default]
    None,
    RejectedC,
    RejectedBOrC,
    Fixed,
    Fubar,
}

#[derive(Default)]
struct Validator<const ASCENDING: bool> {
    history: [i64; 2],
    fill_level: FillLevel,
    fix: Fix,
}

impl<const ASCENDING: bool> Validator<ASCENDING> {
    fn update(&mut self, value: i64) -> Fix {
        self.fix = self.update_fix(value);

        // shift left
        self.history = [self.history[1], value];

        self.fix
    }

    fn update_fix(&mut self, value: i64) -> Fix {
        match self.fill_level {
            // first value is always ok
            FillLevel::Empty => {
                assert_eq!(self.fix, Fix::None);
                self.fill_level = FillLevel::One;
                Fix::None
            }
            // second value never causes abort but could be a fixable error
            FillLevel::One => {
                assert_eq!(self.fix, Fix::None);
                self.fill_level = FillLevel::Full;
                if Self::is_valid_sequence(self.history[1], value) {
                    // all good
                    Fix::None
                } else {
                    // we only have two values; removing either of them would help
                    Fix::RejectedBOrC
                }
            }
            // now for the hard part …
            FillLevel::Full => {
                // some aliases to the recent three values to improve readability
                let a = self.history[0];
                let b = self.history[1]; // previous value
                let c = value; // most recent
                match self.fix {
                    // no problems so far
                    Fix::None => {
                        if Self::is_valid_sequence(b, c) {
                            // still all good
                            Fix::None
                        } else {
                            // B and C are conflicting; let's check whether removing B could help
                            if Self::is_valid_sequence(a, c) {
                                // yup, that would help
                                Fix::RejectedBOrC
                            } else {
                                // nope, C is still invalid
                                Fix::RejectedC
                            }
                        }
                    }
                    // we already decided to ignore the recent value (which was C and is now B)
                    Fix::RejectedC => {
                        if Self::is_valid_sequence(a, c) {
                            // Ignoring C (now B) was good enough to continue but we remember the fix
                            Fix::Fixed
                        } else {
                            Fix::Fubar
                        }
                    }
                    // we found that either B or C (now A or B) should be removed
                    Fix::RejectedBOrC => {
                        if Self::is_valid_sequence(b, c) {
                            // Ignoring B (now A) was good enough to continue but we remember the fix
                            Fix::Fixed
                        } else if Self::is_valid_sequence(a, c) {
                            // Ignoring C (now B) was good enough to continue but we remember the fix
                            Fix::Fixed
                        } else {
                            Fix::Fubar
                        }
                    }
                    // we fixed some error in the past
                    Fix::Fixed => {
                        if Self::is_valid_sequence(b, c) {
                            // value is ok without requiring another fix
                            Fix::Fixed
                        } else {
                            // enough is enough!
                            Fix::Fubar
                        }
                    }
                    Fix::Fubar => {
                        // the horse is dead, give it up already!
                        Fix::Fubar
                    }
                }
            }
        }
    }

    #[inline]
    const fn is_valid_sequence(left: i64, right: i64) -> bool {
        if ASCENDING {
            left < right && (right - left) <= MAX_DIFF
        } else {
            left > right && (left - right) <= MAX_DIFF
        }
    }
}

#[expect(
    clippy::trivially_copy_pass_by_ref,
    reason = "required signature by the consumer"
)]
fn validate_line(line: &&str) -> bool {
    let mut ascending_validator = Validator::<true>::default();
    let mut descending_validator = Validator::<false>::default();
    for number in line.split(' ').map(|number| number.parse::<i64>().unwrap()) {
        let fix_ascending = ascending_validator.update(number);
        let fix_descending = descending_validator.update(number);
        if matches!((fix_ascending, fix_descending), (Fix::Fubar, Fix::Fubar)) {
            return false;
        };
    }
    // no validator complained
    true
}

fn main() {
    let input = include_str!("02.txt");
    let valid_count = input.par_lines().filter(validate_line).count();
    println!("{valid_count}");
}

#[cfg(test)]
mod tests {
    use crate::validate_line;

    #[test]
    fn test() {
        // 7 6 4 2 1: Safe without removing any level.
        // 1 2 7 8 9: Unsafe regardless of which level is removed.
        // 9 7 6 2 1: Unsafe regardless of which level is removed.
        // 1 3 2 4 5: Safe by removing the second level, 3.
        // 8 6 4 4 1: Safe by removing the third level, 4.
        // 1 3 6 7 9: Safe without removing any level.
        assert!(validate_line(&"7 6 4 2 1"));
        assert!(!validate_line(&"1 2 7 8 9"));
        assert!(!validate_line(&"9 7 6 2 1"));
        assert!(validate_line(&"1 3 2 4 5"));
        assert!(validate_line(&"8 6 4 4 1"));
        assert!(validate_line(&"1 3 6 7 9"));
    }
}
```
