### ISSUE TITLE
This Month in Rust, `January 2025`

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#125]
# ToDo

- [x] Settle for a date and location: **Wednesday 2025-01-08, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: "This Month in Rust")
- [x] Final invitation (deadline **T - 10 days**)
  - [x] [meetup](https://www.meetup.com/rustcologne/events/####)
  - [x] [website](https://rust.cologne)
  - [ ] [community calendar]

# Invitation draft

Title: Rust in January: How to (not) structure your Rust projects 

_(The meetup will likely be held in German but we'll switch to English if needed.)_

Dear Rustacean,

our next Meetup will be on **Wednesday 2025-01-08, 19:15 CET**.

You're new to Rust, tried it out with some private projects or are already working professionally with it for years? You're in good company! Whether you want to speed up your python code, write a web service, need interop with your C++-codebase, cross-compile for a microcontroller, write an emulator, … we've got you covered!

We commonly open up with a brief summary of noteworthy changes in the Rust ecosystem. Be it updates to the language itself, public events, its impact on other projects and languages, …

After that we will talk about the challenges of creating complex workspaces with mixed targets (e.g. WASM or embedded) and how to appropriately set up rust-analyzer and an IDE of your choice. As usual, the remaining time is about whatever _you_ want to talk about!

Always wanted to know why Rust is harder to learn than other popular languages or why it lacks a certain feature? When is it appropriate to rewrite a project in Rust? Is the compiler really that slow and are the binaries really that big? Do all those safety guarantees have an impact on the performance? Fetch a drink and let's find it out.

**[You can register here](https://www.meetup.com/rustcologne/events/####)**.

See you soon!

Yours,
Florian and Kai
- - -
If you have a topic you'd like to talk about, please [let us know in advance](https://github.com/Rustaceans/rust-cologne/issues/####). This way we can make sure there's a time-slot for you and maybe announce it officially. Thank you.

# Rust News
- [new rust release?](https://releases.rs)

**Comment by kawogi** [comment]
I'd like to hear a talk on C++/Rust interop, but I don't know anyone who's familiar with both languages.

**Comment by grouvie** [comment]
We discussed this yesterday with a few people. Maybe interesting to someone.
calisti: https://github.com/rust-lang/rust/issues/134554

**Comment by kawogi** [comment]
@Florob Happy new Announcement!

I'd like to dedicate the next meetup to the topics around cargo/workspaces/mixed targets/rust-analyzer and stuff as I'm permanently facing problems with that. Any objections/additions? (I updated the annoucement accordingly)

**Comment by Florob** [comment]
@kawogi Happy new year!

I was otherwise going to talk about using the zerocopy crate for binary format parsing. But I can also do that next month with more preparation. Whichever you prefer.

Announcement looks good to me.

**Comment by SantaClaas** [comment]
Hey there, I think the meetup title still has December in it but it should be January.

And happy new year 😄

**Comment by SantaClaas** [comment]
Also axum had a release with some interesting (breaking) changes which might be worth covering at the beginning  https://tokio.rs/blog/2025-01-01-announcing-axum-0-8-0

**Comment by kawogi** [comment]
> Hey there, I think the meetup title still has December in it but it should be January.
> 
> And happy new year 😄

Oops, thank you. Fixed now!
