### ISSUE TITLE
Rust Code Sprint Weekend - Novemb.rs

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#14]
I'd like us to take part in this year's Rust Code Sprint, codename Novemb.rs.
It will happen on the 19th/20th November.

The idea is to have a a distributed Rust code sprint where people start new projects, work on their current ones or get involved in new ones. 
Two other places are already confirmed (Berlin & Paris), but the idea is to get more people in as well, at best everything from UTC -1 to the UTC +4 (roughly the European and African continent).

Can we use the C4 space or should we look out for a different venue?
It's not clear if there's sponsorship possible, but if so we might as well get some food or drinks payed.

http://novemb.rs/
# ToDos
- [x] Settle for a date: **2016-11-19 to 20**
- [x] Find a space: C4
- [x] Deciding on rough times: noon to (at least) 10pm on each day
- [x] At least one organizer must be present at all times.
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Beginner friendly material (tutorials, small challenges, ..)
  - http://community.rs/resources/
  - http://intorust.com
  - https://rosettacode.org/wiki/Category:Rust
- [x] Final invitation (deadline ~ 2016-11-07 ?)
  - [x] meetup (http://www.meetup.com/RustCologne/events/235374218/)
  - [x] website (http://rust.cologne/2016/11/19/novemb-rs.html)
  - [x] twitter
  - [x] community calendar
  - [x] reddit
  - [x] rust-lang forum (https://users.rust-lang.org/t/7905)
  - [x] rustplatz (https://forum.rustplatz.de/t/185)

# Invitation draft

``` markdown
Title: CGN #31: Weekend Special: Novemb.rs Code Sprint sponsored by Mozilla

Hello Rustaceans,

big news for you: This month we will have yet another really exciting Rust Special,
which you should not miss!

The goal of [novemb.rs](http://novemb.rs) is to start new projects, work on your current ones or get involved in new ones.
The event is open to beginners interested in learning Rust while building a small project.
This may also be your chance to join someone else's project or vice versa

We will meet on the 3rd weekend in November (**2016-11-19 and 2016-11-20**) from noon to (at least) 10pm on each day (feel free to come and go as you please).

Our agenda is as simple as:
* be there, hack on Rust
* have fun and eat free Pizza. :-)

Important: Make sure to bring your programming equipment plus project ideas and some
time.

This is our first event sponsored by Mozilla and we are very proud about that. This is only
possible due to all of your previous great contributions to and participation in our meetups,
which keep this community alive and growing. So thank you for all of that and hoping to
see you at our Rust Code Sprint.

**[You can register here](http://www.meetup.com/RustCologne/events/235374218)**.
Let's make this one memorable!

Note:
* You can speak German and/or English during the event - depending on your conversation
partners, of course. ;-)
* The [Rust Code of Conduct](https://www.rust-lang.org/conduct.html) applies to this event.

Yours,
Jan-Erik, Pascal, Florian and Colin

PS: Make sure to also check out our other great
[Rust Audio Special](http://www.meetup.com/RustCologne/events/234651810/)
three days before on Wednesday **2016-11-16**. 
```

**Comment by colin-kiegel** [comment]
Sounds good. Do you know what we need to do apart from sending invitations and organising some space?

Are there any guidelines we have to follow or criteria to meet?

**Comment by colin-kiegel** [comment]
PS: Thank you for the initiative :-)

**Comment by badboy** [comment]
Nope, it will be a pretty open format. Be there, hack on Rust. It's basically a nice excuse to have a hacking weekend.
We should however make sure to have at least some beginner material around in case some beginner shows up.

**Comment by colin-kiegel** [comment]
Do you mean tutorials or rosetta-style problems by beginner material?

These are lovely introductions by Niko Matsakis for people completely new to Rust :-)
http://intorust.com

**Comment by xetra11** [comment]
Honest answer please. will novize rustaceans be of help or more be like a crutch for the team? I have no problem with that! I'd like to take part but don't want to slow down the others with my endless questioning

**Comment by colin-kiegel** [comment]
@xetra11 I think the journey is our goal. So as long as you enjoy yourself I see no reason why you should not participate. As @badboy suggested we will look into having some beginner friendly material ready, too. :-)

**Comment by colin-kiegel** [comment]
I put the usual todo list in the first post.

@Rustaceans/organizers-cologne 
- Who of you would like to participate?
- Do you think we should try to organize some mentorship?
- What about the time? Shall we select a time or shall we include a survey in the registration for that meetup? (like (a) how long do you want to participate per day (2h/4h/..)? (b) which time window would generally be ok for you (start - end)?

I would like to participate if some minimum of 5 people would be around. I can only mentor with very basic stuff, since I don't code Rust very often.

**Comment by killercup** [comment]
Hey, I'll absolutely be there!

---

> Do you think we should try to organize some mentorship?

I would love to see people new to Rust join us and dig into projects of their own. "Code sprint" does not sound like "beginners workshop" to me, though. In other words: I expect the format to be "People work on projects and learn (more) Rust along the way".

I think this is also what http://novemb.rs means by:

> The goal is to start new projects, work on […] current ones or get involved in new ones.
> 
> […]
> - Mentors ready to take newcomers questions

---

> What about the time? Shall we select a time or shall we include a survey in the registration for that meetup?

Ideally, we have an open location where people can just come and go (assuming at least one person with a key is present). Per my personal biorhythm I'll probably not arrive before 1pm though 😉

**Comment by xetra11** [comment]
Questions:
- is this an evolving event ? Like meet as often as possible to keep up the progress ?

**Comment by colin-kiegel** [comment]
We (=@Rustaceans/organizers-cologne) discussed whether we should explicitly offer mentoring:
- Beginners will be just as welcome as more experienced people. :-)
- But we will not offer whole workshops or mentoring for beginners, because we believe that most people will help each other voluntarily - since the possibility to _discuss problems together_ is kind of the essence of coding together vs. coding alone at home.
- Also everyone should just decide on their own at any time, if he/she is available for questions, or instead wants to focus on their own stuff for a while.

The current idea is to start around noon and end in the evening on both days. We still need to figure out, who will be able to watch out for the key etc. at which time exactly (adding that to todos).

@Florob Is the C4 available on both days?

PS: I generally like the idea of alternating the location, even if the C4 was available. (Having fixed screens sounds good). But we may need to do a more thourough cleaning afterwards than in C4 and I don't know whether it will be as communicative as C4.

**Comment by Florob** [comment]
AFAIK the C4 is not taken on the weekend in question. I'll verify this tomorrow evening. To me the most relevant features of the C4 seem to be the large fridge, and enough room to get out of each others way, if necessary. I'm not sure to what extend this is available at the alternatives we have.

**Comment by Florob** [comment]
The C4 is available on November 19th/20th. We are free to use it if we want to.

**Comment by killercup** [comment]
@Rustaceans/organizers-cologne, I propose we announce this:
- happening at C4,
- from noon to (at least) 10pm on each day,
- welcoming any and all people interested in Rust regardless of level of expertise.

---

BTW, I just saw https://github.com/rust-community/novemb.rs/issues/9. We would love to have you, @panicbit :)

**Comment by xetra11** [comment]
@killercup 
I did not fully understood this yet.
Does this already has started or is there a specific date to "launch" all Novemb.rs "workshops" ?

**Comment by killercup** [comment]
@xetra11 despite being called "novembe.rs" it's just an event on that one weekend.

I feel like the description of this event is a bit… complex (people on Reddit were complaining about it as well). It's just: Get together on the 19th/20th to work on some Rust-related project. In contrast to working on the same stuff at home, here you can talk to people with similar interests in real life. :)

**Comment by xetra11** [comment]
Ah...okay 🗡

**Comment by Florob** [comment]
@killercup That proposal sounds fine to me.

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne please have a look at the invitation draft above. 
- I know we are having a discussion about which CoC to refer to in #15. But for this event I would go with the standard Rust CoC, because this is also what is referenced in [novemb.rs](http://novemb.rs) (at the very bottom).

**Comment by colin-kiegel** [comment]
It was already stated that the title and/or description of the event is confusing. 

Ok we have different options for the title, which one do you think is better:
a) Novemb.rs Rust Code Sprint Weekend Special - sponsored by Mozilla
b) Rust Code Sprint Weekend Special Novemb.rs - sponsored by Mozilla
c) Rust Code Sprint Weekend Special - sponsored by Mozilla

I prefer (b) or (c), because it puts the most important information to the front. What do you think?

PS: Added 'Special' - because this will not happen regularly.

**Comment by killercup** [comment]
I'd change the sentence with the date in it to:

> We will meet on the 3rd weekend in November (2016-11-19 and 2016-11-20) from noon to (at least) 10pm on each day (feel free to come and go as you please).

I also took the liberty to adjust the formatting on meetup.com :)

IMHO, the title should contain: "special", "novembe.rs code sprint" (the official name, even though I don't like calling this a "sprint"), and "Mozilla". My suggestion is an adaptation of @colin-kiegel's (b):

d) Rust Cologne Weekend Special: Novembe.rs Code Sprint sponsored by Mozilla

**Comment by colin-kiegel** [comment]
I like the direction of (d).

Just something minor: It's **[novemb.rs](http://novemb.rs)** instead of novembe.rs.

Another thing is: when posting on forums I usually prefixed the title with `CGN` like the cologne airport code - hoping that some people might get the idea or at least recognize this pattern for our Cologne meetups after a while. So `#10: Compiling Rust to your Browser` on meetup would become `CGN #10: Compiling Rust to your Browser` on users.rust-lang.org. I felt like this information was only relevant when posting outside of meetup / our website or maybe twitter.

This is side tracking quite a bit, but should we try to have a generic approach to this?
1) prefixing with `CGN` is very short, but not everyone will get the meaning the first time.
2) prefixing with `Rust Cologne` matches our meetup name, but could be repetitive in some title like `Rust Cologne #10: Compiling Rust to your Browser` (2x `Rust`)
3) prefixing with `Cologne` might be some middle ground. With this general rule Pascals title might read as `Cologne #13 - Rust Weekend Special: Novemb.rs Code Sprint sponsored by Mozilla` on external channels.
4) No prefixing rules - i.e. different solutions for each announcement and channel.

The other question is: Do we want to keep track of the meetup number in the title? So far I did, when I made announcements.

It's not super important now, but a general idea might make it easier in the future. :-)

Any spontaneous feelings about this one?

**Comment by killercup** [comment]
> It's novemb.rs instead of novembe.rs.

Lol, I never realized. After Web 2.0 I never was quite the same again…

> when posting on forums I usually prefixed the title with CGN like the cologne airport code

That's really clever! Maybe we can add that to #11? (Also, should we write down't those decisions somewhere more permanent/visible than closed issues? Directly in the repo on an 'about' page, maybe?)

> 3) prefixing with Cologne might be some middle ground. With this general rule Pascals title might read as Cologne #13 - Rust Weekend Special: Novemb.rs Code Sprint sponsored by Mozilla on external channels.

I'm not sure the `#13` is really valuable information to anyone. Does it matter if this is the first or the 32th meetup? Especially since this is a special event – does it even count as a meetup?

**Comment by killercup** [comment]
FYI, I added the event with the current description to the website (after changing the start page logic to be able to deal with ≥1 event in the future). Feel free to update it.

**Comment by colin-kiegel** [comment]
Ok, ich habe wieder meetup und die beiden Foren übernommen und für Rustplatz auch wieder auf Deutsch übersetzt..

Will wieder jemand anderes Twitter, Reddit und die Webseite übernehmen? Dankeschön... ;-)

(PS: Ich konnte mich irgendwie noch nicht von dem Zähler verabschieden. Braucht ihr aber auf den anderen Kanälen nicht so machen, wir können die Diskussion ja noch woanders weiterführen). ^^

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne We haven't checked this checkbox yet:
-  At least one organizer must be present at all times.

What are your plans on this weekend, will you all be there from noon to 22 pm in the evening on both days, or not, or something in between?

I will try to be around for roughly 50% of the time. I can still shuffle this around a bit if needed, but I would not yet commit for 100%. What about you?

**Comment by badboy** [comment]
I'm in all the time. (Still need to figure out if I have to go back to aachen that night)

**Comment by killercup** [comment]
I was gonna close this, but: @Rustaceans/organizers-cologne, do you want to recap something/some projects from the weekend?

**Comment by badboy** [comment]
I want/need to write something up anyway, so we could quickly collect a few of the things we did/talked about:

- Some audio/midi processing
- Flif decoder by @panicbit & @killercup 
- OpenSSL buffering by @Florob 
- Builder/Setters/Getters by @colin-kiegel 
- rustaceans.org by @badboy
- @colin-kiegel helped @sangyye get started with Rust

**Comment by colin-kiegel** [comment]
It was fun. Thank you for suggesting to do this in the first place. :-)

@badboy what about the pictures you have taken: Would you mind to upload some of them on meetup and/or twitter (and maybe link them here)?

**Comment by badboy** [comment]
Following up on this one (I know, it's late): I'm writing a short post today and publish it on my blog (including photos). We can then also link to that from our online presences or put that up on the site as well.

**Comment by badboy** [comment]
https://fnordig.de/2016/11/29/novemb-rs-code-sprint-weekend-2016-retrospective/

**Comment by killercup** [comment]
Thanks for the follow-up, @badboy!

(I assume you are going to add links to the website etc., right? Do you want to close this issue?)

**Comment by badboy** [comment]
First the links, then the closing.
