### ISSUE TITLE
March 2017 Meetup

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#24]
# Todo

- [x] Settle for a date: **2017-03-01**?
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline **2017-02-15**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/237423265/)
  - [x] [website](http://rust.cologne/2017/03/01/web-dev.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/833281681754845184)
  - [x] [community calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MWkzYWkydHVvYXU0ZzVpYThtMXZiM2psc28gYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/5uxxfk/join_us_on_march_1_in_cologne_for_a_meetup_about/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/9540)
  - [x] [rustplatz](https://forum.rustplatz.de/t/koeln-meetup-web-entwicklung-mit-rust/195)

# Invitation draft

```markdown
Title: CGN: Web Development with Rust

Does Rust have the neccessary ingredients for web development (yet)? Let's find out in our next meetup on **Wednesday 2017-03-01, 19:15 CET**, which _might_ turn into a series.. ;-)

**Agenda**

* **What's so hard about writing a Slack client in Rust?** – by Matthias Endler
> "I'll just write a simple API wrapper for that. Give me two hours." Does that sound
> oddly familiar? Don't be fooled: writing an easy to use, idiomatic abstraction layer
> is a lot of work - in any language. I want to tell you my story about writing a Slack
> client in Rust. From documentation to testing and error handling there's a lot of
> pitfalls to avoid and laughs to share.

* **Diesel – Type Safe SQL** – by Pascal Hertleif
> Better refuel before we get started, this is a "Choose Your Own Adventure" talk
> — where the audience decides into which rabbit hole(s) we go down. Writing an
> actual app? Sure! Type system excursions? Always! Or maybe something about
> our test shenanigans? And of course fields of generated code as far as the eye
> can see!

Enjoy some drinks, meet nice people and discuss with us about Rust!

**[You can register here](https://www.meetup.com/RustCologne/events/237423265/)**.

We are looking forward to seeing you. :-)

Yours,
Jan-Erik, Pascal, Florian and Colin

―  
The meetup will likely be held in German, we will however reevaluate this at the
beginning of the evening and may switch to English if needed.
```

# <a id="news">News</a>

- First off: We have a glorious new logo! Someone should make t shirts! And cups! And mouse pads! And stickers! (Also, we should gift one of each to Chief Executive Logo Designer Matthias)
- New Rust release on March 16, [Release Notes PR](https://github.com/rust-lang/rust/pull/39835)
- Rustfest on April 30 in Kyiv
  - Tickets: 199€ (supporter, available now), 89€ (regular, first batch starts Friday), 49€ (student)
  - CFP open till Sunday
- Libs
  - Rocket 0.2
  - Chrono 0.3
  - (more on Diesel 0.11 later)
  - [Pathfinder](https://pcwalton.github.io/blog/2017/02/14/pathfinder/) seems fun
- RFCs
  - new one for [const types](https://github.com/rust-lang/rfcs/pull/1931) (a.k.a. dependent types, a.k.a. Π types, a.k.a. `fn<const n: usize>(input: [u8; n])`)
  - RFCs for varargs make a comeback as well with https://github.com/rust-lang/rfcs/pull/1935 after https://github.com/diesel-rs/diesel/pull/747
- [Underhanded.rs](https://underhanded.rs/en-US/)
- Rust SF meetup 2.3. (https://github.com/rust-community/talks/issues/37#issuecomment-283099104) – including Rocket.rs, will be recorded

**Comment by killercup** [comment]
@Rustaceans/organizers-cologne, any ideas about topics we want to cover?

Lukas (at least I think it was him) asked if I want to talk a bit about Diesel, which I'd be up to.

**Comment by colin-kiegel** [comment]
I generally like the idea to find pairs of talks or activities with a common overall story. Of course that's not a necessity. But a while ago we had the idea to have an arewewebyet themed evening, or even a series of events. Can we make the diesel talk be part of a larger picture somehow?

Alternatively we could always throw in another openspace meetup to buy us more time to prepare something else.

**Comment by colin-kiegel** [comment]
PS: Diesel would definitely be an interesting topic. Would you like to focus more on use cases, or the inner workings?

**Comment by badboy** [comment]
Just a heads up: 2017-03-01 is Aschermittwoch. So most of Karneval is over by then.

I'd very much like putting on the arewewebyet story. Diesel would fit right in. 
We should try to encourage attendees to give talks as well instead of us though!

**Comment by killercup** [comment]
Having two talks with an overarching theme is great. I'd also focus on having that first; if there are two other talks proposed that fir together, I have no problem putting a Diesel talk off for a month or two. Luckily, there are a lot of aspects of Diesel I can talk about, though!

- Using diesel: Basically the Getting Started guide. Might involve live coding.
- Secrets of a query builder: Mapping types and carrying bindings, with all the derive schema magic
- Using Diesel to discover the limits of the type system
- Sup dawg I herd u like traits
- Going Meta: Exploring some more possible topics for Diesel talks (:trollface:)

Do you think anyone wants to talk about rocket.rs?

**Comment by colin-kiegel** [comment]
Shall we make an announcement via our mailinglist that we are _looking for talks_ for an arewewebyet themed meetup series?

**Comment by killercup** [comment]
Sound good to me.

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne I drafted an email to send via our mailinglist. Please have a look and feel free to edit.

I am undecided whether we should link to this ticket - or a new one. Especially if we are planning to have a _series_ of web meetups it might be clever to pool ideas separately - what do you think?
```
Dear fellow Rustaceans,

we want to prepare a meetup series focused on web development soon,
possibly starting in March. .. But we need your help, to make it happen. ^^

We are looking for talks and general ideas of activities that would fit
into that topic:
- are you working on a web project?
- would you like to show us a cool library?
- do you want to tell us about general architecture?

Whatever your ideas are, please let us know what you would like to see,
hear or talk about yourself. :-)

github: [[link to new github issue]]
or send us an email.

Yours,
Jan-Erik, Pascal, Florian and Colin
---
PS: A good reference for Rust web-libraries is http://www.arewewebyet.org/
```

**Comment by colin-kiegel** [comment]
PS: I added ` .. But we need your help, to make it happen. ^^`

**Comment by killercup** [comment]
Nice. I'd try to ask for ideas in general, but also for talks _for a specific date._ Having someone commit to "talking about this in a few months" is probably not as helpful as having a second talk on March 1. Thus, I'd link to this issue. If there are too many proposal, I'll personally copy-paste them into a new one :)

I adjusted your text a bit:

```markdown
Fellow Rustaceans,

We feel like the time is right to have a meetup around web development in Rust.
And we need your help to make it happen!

We are looking for talks and general ideas of activities that would fit that
topic. For example:

- Are you working on a web project?
- Would you like to present a cool library?
- Do you want to tell us about general architecture?

We would love it if you send us an email, comment on Meetup.com, or if you chime
in on our planning discussion on Github:
<https://github.com/Rustaceans/rust-cologne/issues/24>

Thank you!

Yours, Jan-Erik, Pascal, Florian and Colin

---

P.S.: Have you seen http://www.arewewebyet.org/ yet?
```

**Comment by colin-kiegel** [comment]
ok, I sent both (a) our usual 'save-the-date' info and (b) the call for help announcement. I hope it makes sense this way - but meetup doesn't allow that much text in event notifications. ;-)

**Comment by mre** [comment]
Hey, I could give a talk about the current status of my Rust slack client. Don't expect anything outstanding, though. It's more like a rundown of pitfalls you might want to avoid when writing such a library. 😁 Interested?

**Comment by killercup** [comment]
Sure! Added anything fancy recently? (Like the new version of
derive-builder *hint* *hint* ;))

Matthias Endler <notifications@github.com> schrieb am Mi. 8. Feb. 2017 um
14:55:

**Comment by mre** [comment]
I'll try to integrate the newest version of derive_builder until the talk.
Also: error_chain, code generation, json schema parsing, testing and serde_urlencoded and some more.

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne

I suggest that we send the final invitation this weekend. IMO we have two options (a) have the diesel and slack API talks or (b) wait until we have more web related talks to start a series of meetups and do something openspace like first.

cc @killercup @mre I think we should hear your preferences first. ;-)

Everyone else reading this, feel free to suggest other talks here, even if you would not do it in march, but later.

**Comment by mre** [comment]
@colin-kiegel both is fine with me. Even if the talks might be short I guess we won't run out of topics afterwards. There's just too many good Rust libraries out there. 😉

**Comment by killercup** [comment]
I agree, let's go with (a). We can always let the meetup turn into an openspace after the talks.

**Comment by colin-kiegel** [comment]
ok @mre @killercup what's the title of your talks? :-)

**Comment by badboy** [comment]
Vote for `Option<A>` as well!

**Comment by mre** [comment]
Let's call mine **_What's so hard about writing a Slack client in Rust?_**

**Comment by killercup** [comment]
@colin-kiegel feel free to pick one from <https://github.com/Rustaceans/rust-cologne/issues/24#issuecomment-277190082>! 😄 Or go with

> Diesel – Type Safe SQL
>
> Better refuel before we get started, this is a "Choose Your Own Adventure" talk—where the audience decides into which rabbit hole(s) we go down. Writing an actual app? Sure! Type system excursions? Always? Or maybe something about our test shenanigans? And of course fields of generated code as far as the eye can see!

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne I updated the invitation draft - let's get it out this weekend. ;-) Do you want to add/change something?

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne ping :-)
https://github.com/Rustaceans/rust-cologne/issues/24#issue-204898529

**Comment by killercup** [comment]
Invite LGTM but maybe @mre wants to add a short description? Or, just leave
out mine.

Colin Kiegel <notifications@github.com> schrieb am Sa. 18. Feb. 2017 um
21:43:

**Comment by mre** [comment]
@killercup good idea! Here we go:

> "I'll just write a simple API wrapper for that. Give me two hours." Does that sound oddly familiar? Don't be fooled: writing an easy to use, idiomatic abstraction layer is a lot of work - in any language. I want to tell you my story about writing a Slack client in Rust. From documentation to testing and error handling there's a lot of pitfalls to avoid and laughs to share.

**Comment by colin-kiegel** [comment]
@killercup I sent most invitations. Do you want to do reddit again? Also the text on the website is not up-to-date.

**Comment by killercup** [comment]
Thanks! Just got the invite email myself. I'll update both.

**Comment by colin-kiegel** [comment]
@killercup @mre There is interest in recordings of these talks in the [Rust forum](https://users.rust-lang.org/t/cgn-meetup-web-development-with-rust/9540/2). Do you want to record them?

@Florob Would you like to organize the recording?

**Comment by killercup** [comment]
I'm okay with recording my talk. Just as a head up: It might get pretty Q&A-y, so we'll probably need mic(s) for the audience. (But this was pretty good in the past.)

**Comment by mre** [comment]
Yup, I'm also fine with it.

**Comment by Florob** [comment]
I'm happy to do recordings again. We have a hand-held microphone for Q&A, the biggest problem is usually getting people to use it consistently.

**Comment by killercup** [comment]
I added a few more things under "Rust News". Feel free to expand :)

**Comment by killercup** [comment]
Notes/suggestions for next meetups:

- IDE setup night
- another OpenSpace
- [crate polishing](https://llogiq.github.io/2017/02/27/cpw.html)
- mob programming style crate polishing
- watch existing talk and add comments
- hacking game battleship competition
- start with simple fns and add rust concepts
- channel/network stuff, maybe with tokio
- hack weekend again, maybe a workshop

**Comment by killercup** [comment]
@mre, do you want to publish your slides? Which were brilliantly hilarious, by the way!

**Comment by mre** [comment]
@killercup yes sure. Uploaded to [Speaker Deck](https://speakerdeck.com/mre/whats-so-hard-about-writing-a-slack-client-in-rust). Feel free to move it around. 
Edit: Updated link.
