### ISSUE TITLE
Rust 2nd Anniversary - Part I

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#26]
Rust 1.0 was [released on May 15th 2015](https://blog.rust-lang.org/2015/05/15/Rust-1.0.html).

Last year we had two fabulous anniversary meetups, a spectacular :birthday: cake (by @fyl2xp1) and a special guest from the Dev Team
- https://www.meetup.com/de-DE/RustCologne/events/230641335/
- https://www.meetup.com/de-DE/RustCologne/events/231135785/

@Rustaceans/organizers-cologne do you know any special guests we could invite this time? Mozilla devs travelling through Europe by any chance? ;-)

Ok, let's brainstorm what we could do:
- take a look back and ahead again
- maybe print some stickers (anyone interested in T-Shirts?)
- order "Pizza Rustica" somewhere
- or maybe ask our user group if someone is interested in baking a cake again
- ...

# ToDo

- [x] Settle for a date: **2017-05-03**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline **2017-04-19**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/ctcbwlywhbfb/)
  - [x] [website]
  - [x] [twitter]
  - [x] [community calendar]
  - [ ] [reddit] 
  - [ ] [rust-lang forum]
  - [ ] [rustplatz]

# Invitation draft

```markdown
Title: CGN: Rust 2nd Anniversary

Another years has (almost) gone by since Rust's 1.0 release, and we want to celebrate this at our next meetup on **Wednesday 2017-05-03, 19:15 CEST**.

For this meetup we would like to take a look at the features Rust has gained over the course of its existence.
To do this we will discuss various features, either stable or planned, in smaller groups.
What is it exactly? What have you used it for? Are there aspects you're still having problems with?
So bring your favorite Rust feature and let's talk about it!

**[You can register here](https://www.meetup.com/de-DE/RustCologne/events/239100622/)**.

We are looking forward to seeing you. :-)

Yours,
Jan-Erik, Pascal, Florian and Colin
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Rust News

- [rust 1.17 release](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
- [RLS available via rustup](http://www.jonathanturner.org/2017/04/rls-now-in-nightly.md.html)
- [Serde 1.0](https://github.com/serde-rs/serde/releases/tag/v1.0.0)

**Comment by killercup** [comment]
The regular dates are **May 3** and **June 7**. So, we'll have the chance to stretch our celebration out over two meetups (May and June) once again.

Some of us will be at Rustfest on April 30, so the May meetup will also be a chance to recap that event. (I assume @badboy will be there, and I will be as well. Anyone else? We should ask at the next meetups.)

I'd really love some sweet Rust Cologne t-shirts or stickers. Maybe we can create/order some in April and have some gifts to unwrap in May? Does anyone have experience with this? I made some t-shirts a decade ago on Spreadshirt, but we'd better not rely on my artistic talent 😅

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne I think we already settled on the date. Shall we send the save-the-date info with link to this ticket?

**Comment by killercup** [comment]
@colin-kiegel sounds good to me!

Any news regarding RustCologne swag, @badboy?

**Comment by badboy** [comment]
I sent edunham a mail, didn't hear back yet, but afaik she gave a timeframe in IRC. Will check.

**Comment by mre** [comment]
Would also be interested in a T-Shirt!
We could either go with the Rust Cologne logo, or print something more generic.
I really liked the [steampunk design](https://devswag.com/products/rust-t-shirt) from Rust 1.0.

I could create a simple artwork based on these free vector graphics:
* [octopus](http://www.freepik.com/free-vector/background-of-hand-drawn-octopus-with-gears_958929.htm#term=steampunk&page=1&position=3)
* [gears](http://www.freepik.com/free-vector/background-of-machine-gear_956706.htm#term=steampunk&page=1&position=42)

In any case, it's a lot of work, so I would like to know upfront if you are interested in that. If so, which design do you prefer?

**Comment by colin-kiegel** [comment]
I'd be interested in the gears one (though I can't participate in the next two meetups). :-)

**Comment by killercup** [comment]
Nice! I like the steampunk style and think the octopus looks quite cool;
might be hard to add a rust flavor, though (aside from the cogs).

That reminds me, did you all see the cyberpunk style of the reddit on April
1st? Might also be cool to do something like that. (Which is also
historically accurate, as cyberpunk came after steampunk after all!)

Matthias Endler <notifications@github.com> schrieb am Mo. 10. Apr. 2017 um
11:57:

**Comment by mre** [comment]
> That reminds me, did you all see the cyberpunk style of the reddit on April 1st? 

Unfortunately not. Could you post a screenshot?

**Comment by killercup** [comment]
This should work: http://archive.is/A0stm

Matthias Endler <notifications@github.com> schrieb am Di. 11. Apr. 2017 um
20:17:

**Comment by mre** [comment]
Sooo, you like the 80's style logo?

Like [this](https://de.pinterest.com/pin/294774738084037269/), [this](https://www.google.de/imgres?imgurl=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2F736x%2F0a%2F08%2F2a%2F0a082ad60878b2d7a24c35d3fda0ce80.jpg&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fadoraattack%2F80sretroelectro%2F&docid=8yBGIjekIySggM&tbnid=JtQEEVYiGQts7M%3A&vet=10ahUKEwiey7Ppk53TAhUD6xQKHbX8A1kQMwhJKBgwGA..i&w=500&h=400&client=firefox-b-ab&bih=787&biw=1203&q=miami%20vice%20logo%20style&ved=0ahUKEwiey7Ppk53TAhUD6xQKHbX8A1kQMwhJKBgwGA&iact=mrc&uact=8) and [that](https://www.google.de/imgres?imgurl=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fy8brTm5aslo%2Fmaxresdefault.jpg&imgrefurl=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dy8brTm5aslo&docid=QPBZ0Cx0w0D3FM&tbnid=jnTfvHdqQmplyM%3A&vet=10ahUKEwiey7Ppk53TAhUD6xQKHbX8A1kQMwhtKDwwPA..i&w=1920&h=1080&client=firefox-b-ab&bih=787&biw=1203&q=miami%20vice%20logo%20style&ved=0ahUKEwiey7Ppk53TAhUD6xQKHbX8A1kQMwhtKDwwPA&iact=mrc&uact=8)?
There's a [video tutorial](https://www.youtube.com/watch?v=y8brTm5aslo) for that.

That said, not a big fan to be honest. People might confuse it with GTA Vice City fan shirts. On the other side... maybe that's exactly your point?
In case you mean the "Matrix" and "Hackers" photos as well, that's gonna be a bit tricky on colored shirts, I guess.

**Comment by killercup** [comment]
It's final invitation time! (And I'll probably not have time to contribute anything here today)

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne: As already mentioned, I can not participate in the next two meetups. Therefore I'd prefer to (mostly) stay out of the preparation this time. I think you should determine the agenda without me. But if you want me to help, I could offer to send out invitations again (given the agenda is ready). :-)

**Comment by Florob** [comment]
Most important question to settle right now is probably what we want to do.
I'd suggest having one of the anniversary Meetups rather open, and one with talks.
Considering the timeline this one is probably going to be the open one.

Straw man: Shall we do an open-space-ish meetup and ask everyone to "bring" their favourite stable, or upcoming Rust feature. We could have small groups explaining the feature to newcomers, discussing use-cases, talking about problems people have had with them…

I can probably come up with some text later this evening.

**Comment by killercup** [comment]
@Florob great idea! Feel free to update the website as well.

By the way: You can `rustup component add rls` now, and this meetup will be right after RustFest.

**Comment by badboy** [comment]
I really like @Florob's idea. "Everyone's favorite Rust feature"

**Comment by Florob** [comment]
I've updated both meetup and the website.

I'm now
* thoroughly confused about time zones
* not entirely sure how/to whom we usually send the meetup mail

Help with the latter would be appreciated.

**Comment by colin-kiegel** [comment]
@Florob I like the invitation text.

Hm, looks like the timezone should be CEST instead of CET. Is that the confusion?

You can send the Meetup reminder via group administration > mail to members. Then either pick "everyone interested in mails from organizers" or "mailing list". Both should be roughly equivalent. 

Meetup mails sometimes behave surprisingly with regard to formatting of new lines. I'd advise you to click the preview button. Another formatting quirk is, that bold usually does not appear in the preview, but in the final mail. ;-)

This is different from our first announcement of the meetup, where you can just select a meetup and "publish" it. This will trigger a different kind of invitation mail, which is only possible once per meetup. Usually we "publish" an event early as our save-the-date invitation. The second more detailed invitation is just a plain mail to all members.

Hope that helps. Anything else unclear?

**Comment by Florob** [comment]
@colin-kiegel Thanks.
The time zone confusion is mostly that on the website we had "MEST" until March, and then changed to "MEZ" for April.

**Comment by killercup** [comment]
The invitation text is great! 👍 

FYI, the timezone ~~confusion~~ magic is probably caused by [this](https://github.com/Rustaceans/rust-cologne/blob/b9e3c15fe5631f60985daf00dcd2d173dccb0709/_config.yml#L30), as it tries to be clever and always use the current timezone and the output does not include the time zone…

**Comment by Florob** [comment]
@killercup Define "magic". IMHO the date field in a lot of the posts markdown is just plain wrong. Are you saying this is intentional so the time is displayed correctly?

**Comment by killercup** [comment]
@Florob lol, you're right, I was thinking of a different problem I recently had with a ruby app, but what we have here is copypasta at it's finest. I'm pretty sure I initially tested what time formats worked (it was also a matter understanding how Jekyll deals with post's dates and of making sure that they are _not_ treated as publication dates) and for some reason I settled on "MESZ". Looking at this now, the posts after that all carry the same time zone, sometimes dropping the S to arrive at MEZ. This is weird, and I'd write CE(S)T or +01:00 (or +02:00) now. We can fix this if needed.

What baffles me is that some of them are wrong, but they are all displayed correctly ([archive](http://rust.cologne/archive/)). Maybe the current Jekyll version doesn'T understand ME(S)Z and ignore it, treating it as a date-time in the 'local' timezone (which the config sets to Berlin)?
