### ISSUE TITLE
April 2017 Meetup

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#29]
# ToDo

- [x] Settle for a date: **2017-04-05**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline **2017-03-18**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/ctcbwlywgbhb/)
  - [x] [website](http://rust.cologne/2017/04/05/crate-polishing.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/843979412475461632)
  - [x] [community calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=YW5kcnAxdmh0czB2cjg5ajJnNXZsZnRuOTQgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/60kfku/crate_polishing_meetup_on_april_5_2017_in_cologne/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/cgn-crate-polishing-workshop-special-guest/10018)
  - [x] [rustplatz](https://forum.rustplatz.de/t/koeln-crate-polishing-workshop-special-guest-2017-04-05/203)

# Invitation draft

```markdown
Title: CGN: Crate Polishing Workshop + Special Guest?..

Fellow Rustaceans,
 
Our next meetup is set for the first Wednesday in April: **2017-04-05, 19:15 CET**.
 
Based on your feedback at the end of the last meetup, we have decided to try a
**Crate Polishing Meetup** this time around. This basically means we will choose a
crate we consider important and try to make it better/nicer to use. Whether that
means adding documentation, examples, or fixing bugs is up to you. Which crate
to polish will be decided at the beginning of the meetup.

If you have a suggestion, feel free to comment in our planning issue [1]. Don't
be shy to suggest your own crates – it's even better if the maintainer/author is
present!
 
Oh, and before we forget: This is actually a preliminary plan! Do you remember how
last year we had Alex Crichton, a member of the Rust core team, celebrate Rust's
1.0 anniversary with us [2]? We might have another visitor from the core team in
April this time! We can't make any promises, but will let you know as soon as we
have more details!
 
**[You can register here](https://www.meetup.com/RustCologne/events/ctcbwlywgbhb/)**.

See you soon!
 
Your Rust Cologe Organizers,
Colin, Florian, Jan-Erik, and Pascal
―  
The meetup will likely be held in English, due to our potential special guest.
 
[1]: https://github.com/Rustaceans/rust-cologne/issues/29
[2]: http://rust.cologne/2016/06/06/rust-anniversary-part-2.html
```

# Agenda

## Announcements

- http://2017.rustfest.eu/ April 30th, 2017 - Kyiv, Ukraine (who's going?)
  - @killercup has a coupon for 15% off, ask him if you plan on buying a ticket
- Embedded Systems: Is there interest to have access to Hail (and imix) systems at the c4? https://www.tockos.org/hardware/
- Other announcements from our members?

## Rust News

- [rust 1.16](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
 - [`cargo check`](https://github.com/rust-lang/cargo/pull/3296) typecheck without building
- [Improvement of RUST_BACKTRACE merged on latest nightlies](https://users.rust-lang.org/t/improvement-of-rust-backtrace-merged-on-latest-nightlies/9735)
- [`pretty assertions`](https://github.com/colin-kiegel/rust-pretty-assertions): Overwrite `assert_eq!` with a drop-in replacement, adding a colorful diff.
- [Rust is the most loved language in Stack Overflow Developer Survey, again](https://stackoverflow.com/insights/survey/2017/#most-loved-dreaded-and-wanted).
- Other news from our members?

## Actual meetup

- @killercup will give a talk about 'rustic APIs' at Rustfest, could give a sneak preview (≤20min) if wanted, maybe reduced to stuff relevant to crate polishing (to be determined what that is)
- Crate polishing: Which crate should be polish?
  - cf. #30
  - Collect names and "pitches" on whiteboard, allow people to mark the ones they find interesting (maybe limit this to 2-3 marks per person)

**Comment by colin-kiegel** [comment]
We already collected some ideas [during the last meetup](https://github.com/Rustaceans/rust-cologne/issues/24#issuecomment-283467751). I'll just copy paste them here:

- IDE setup night
- another OpenSpace
- [crate polishing](https://llogiq.github.io/2017/02/27/cpw.html)
- mob programming style crate polishing
- watch existing talk and add comments
- hacking game battleship competition
- start with simple fns and add rust concepts
- channel/network stuff, maybe with tokio
- hack weekend again, maybe a workshop

Most ideas require _some_ degree of preparation by someone. Unless someone steps up to do a talk/etc., my preference would be to keep it simple and do a OpenSpace meetup. :-)

@Rustaceans/organizers-cologne The most important part would be to send a save-the-date reminder as soon as we settled on the date. I think we already did yesterday - but I'll wait until tomorrow, in case anyone wants to stop me. ;-)

**Comment by killercup** [comment]
I think we all agreed to April 5. Or, at least, nobody objected. And it's the first Wednesday in April.

Re topic: What would you be up to? I'm skeptical of everything that takes time to prepare (blame my own laziness), but would love to get my hands dirty writing code for unfamiliar areas (like, something with tokio). I see two semi-related options:

- Doing another Open Space. Maybe tuned a bit differently than last time, with stricter timing and maybe rearranging tables to form areas for 2–4 people to sit together. We have a lot of ideas/topics and I think it's a good option to make many people happy.
- Try mob programming/polishing something. With 1–2 groups, this is like an OpenSpace in that it is determined ad-hoc what we'd do, but with more people per group, and basically no time limit.

**Comment by colin-kiegel** [comment]
Yes I think crate polishing is good in many regards.
* We regularly have people quite new to Rust - so I think it's good to actually get our feet wet from time to time.
* It's easy to prepare, we basically only need to prepare a list of crates that need polishing and are actively maintained (and maybe already had PRs accepted in the past).

@Llogiq did a great job at [documenting](https://llogiq.github.io/2017/02/27/cpw.html) the experience of the Rust Darmstadt Meetup with this. :+1: :-)

PS: I have a slight preference for crate polishing over open space. And people interested in "what IDEs do other people use" will get this question answered both ways - which was a request last meetup.

**Comment by llogiq** [comment]
As I wrote, it's a big plus in interactivity to have the crate maintainer attending. If you do it, tell me how it went.

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne Updated the invitation draft! I also included the mentioning of our potential special guest as @killercup proposed! Let's get this out. :-)

I am looking forward to our meetup. To bad @badboy will not be there.

**Comment by colin-kiegel** [comment]
Update: changed the footnote
> The meetup will likely be held in English, due to our potential special guest.

**Comment by badboy** [comment]
prelimary -> preliminary

**Comment by badboy** [comment]
While we're at it regarding crate polishing: https://github.com/brson/rust-cookbook

**Comment by colin-kiegel** [comment]
Almost all invitations sent, again except website + reddit, cc @killercup? 

Hm .. forgot to mention that everyone should bring their equipment, but that _should_ be obvious. :-) Really looking forward to it.

**Comment by killercup** [comment]
All done!

**Comment by colin-kiegel** [comment]
@killercup any news from our guest yet? *crossing fingers*.

**Comment by killercup** [comment]
I hope to get an answer before the end of next week!

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne 
- I have included some news in the first post which I think are noteworthy, feel free to add additional entries. 
- I have also included a reminder to ask about interest in Hail (and imix) systems.

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne Hooray, **Gary Newvan** will indeed join us. Ok, I sent an update about Gary joining us via meetup, both forums and twitter. Would anyone do the website and reddit again?

Can't wait. :-)

**Comment by brakmic** [comment]
Hi all,

Call me "outdated" but why is there a link to some gaming platform called "HumbleBundle".

Do we advertise them...I hope not.

Regards,

**Comment by brakmic** [comment]
I think the special guest's family name is "Newman" not "Newvan".

https://www.meetup.com/RustCologne/events/238165412/

https://twitter.com/garrynewman

**Comment by colin-kiegel** [comment]
In case you wonder - the whole Gary Newvan thing was just an April Fools' joke. We are looking forward to some nice crate polishing with you (without a special guest). ;-)

**Comment by killercup** [comment]
Updated the description above with a few more links and grouped the agenda with headlines. Primary changes:

- I have a coupon for 15% off Rustfest tickets especially for use in our meetup!
- Suggested way to determine the crate we polish (short pitch + add to whiteboard, members add check marks to the suggestions they like)

**Comment by colin-kiegel** [comment]
Notes: Todays picks

- Kebab Land (turkish charcoal grill)
- [Rust Study Group Dortmund](https://users.rust-lang.org/t/rust-study-group-in-dortmund-ger/10230)
- spacemacs
- [static site generator **gutenberg**](https://github.com/Keats/gutenberg)
- http://2017.rustfest.eu/ April 30th, 2017 - Kyiv, Ukraine (who's going?)
  - @killercup has a coupon for 15% off, ask him if you plan on buying a ticket
- [neovim remote](https://github.com/mhinz/neovim-remote)
- [completion for neovim](https://github.com/Shougo/deoplete.nvim)
- [assert_cli](crates.io/crates/assert_cli) / [pretty_assertions](crates.io/crates/pretty_assertions)
- ghost in the shell movie

News:
- [first rust game on steam greenlight: shar](https://www.reddit.com/r/rust/comments/62gvay/the_first_known_game_on_steam_using_rust_shar/)

Other:
- Interest in embedding programming: roughly 4 out of 14 people are generally interested
