### ISSUE TITLE
Rust 2nd Anniversary - Part II

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#31]
Rust 1.0 was [released on May 15th 2015](https://blog.rust-lang.org/2015/05/15/Rust-1.0.html).

Last year we had two fabulous anniversary meetups, a spectacular :birthday: cake (by @fyl2xp1) and a special guest from the Dev Team
- https://www.meetup.com/de-DE/RustCologne/events/230641335/
- https://www.meetup.com/de-DE/RustCologne/events/231135785/

@Rustaceans/organizers-cologne do you know any special guests we could invite this time? Mozilla devs travelling through Europe by any chance? ;-)

Ok, let's brainstorm what we could do:
- take a look back and ahead again
- maybe print some stickers (anyone interested in T-Shirts?)
- order "Pizza Rustica" somewhere
- or maybe ask our user group if someone is interested in baking a cake again
- ...

# ToDo

- [x] Settle for a date: **2017-06-07**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline **2017-05-24**)
  - [x] [meetup](https://www.meetup.com/de-DE/RustCologne/events/239100643/)
  - [x] [website](http://rust.cologne/2017/06/07/rust-2nd-aniversary-part-2.html)
  - [x] [twitter]
  - [x] [community calendar]
  - [ ] [reddit] 
  - [ ] [rust-lang forum]
  - [ ] [rustplatz]

# Invitation draft

```markdown
Title: CGN: Rust 2nd Anniversary Reloaded

Dear Rustaceans!

It is official: It's been two years since Rust's 1.0 release! And that means we
need *two* meetups to celebrate that – good thing we already had a test run for
that last year!

That's why we invite you to join us **on June 7 at 19:15 CEST**!

Our agenda so far is this:

* A short summary of what happened the last year in Rust. If you have something
that really excited you and that you want to share, you are very welcome to do so!
* Florian will talk about Inline Assembly. Rust's support for inline assembly is currently
unstable. The talk will give an overview of the current unstable implementation in Rust,
as well as inline assembly support available in other programming languages.
~~This will lead into a discussion of the question what a sensible design that Rust could 
stabilize would be. ~~
This will lead into a discussion about a sensible design for this feature and a way to stabilize this eventually.

Oh, and also, there will be pizza!

**[You can register here](https://www.meetup.com/de-DE/RustCologne/events/239100622/)**.

We are looking forward to seeing you. :-)

Yours, Jan-Erik, Pascal, Florian and Colin

---

The meetup will likely be held in German, we will however reevaluate this at the
beginning of the evening and may switch to English if needed.
```

# Rust News

- [1.18: tomorrow](https://github.com/rust-lang/rust/blob/f73f675a864e966aedde79f8d2a8c821128e6b10/RELEASES.md#version-1180-2017-06-08)
  - `pub(crate)`
  - perf: rustc 15%-20% faster, grand enum optimizations (https://github.com/rust-lang/rust/pull/40377)
- beginners? look at issues from libz blitz: https://internals.rust-lang.org/t/rust-libz-blitz/5184/53
- Rust Conferences
    - RustConf, Portland, USA, 18-19 August, **CfP is open**
    - RustFest, Zürich, CH, September
    - RustBeltRust, Columbus, USA, 27-28 Oct
- RustFest Kyiv Videos are online! [Online Playlist](https://www.youtube.com/playlist?list=PL85XCvVPmGQhvs1Rnet_24B-AI3YSM2YG)

**Comment by badboy** [comment]
What do you think about having a remote speaker give a talk?

There are folks from parity.io (Ethereum, Blockchain) and Maidsafe (https://maidsafe.net/, SAFE Network) who might be up to it.
If that's less of an interest, I could potentially reach out to others as well.

**Comment by kawogi** [comment]
Thanks for the kudos @Florob but I don't think I will make the effort to redo that cake - unless Rust changes the logo into a circle :)

For a shirt (or button) I forgot to suggest the phrase "In mod we Rust!"

Maybe someone is interested in "plush ferris"? I might be able to bring some with me.
http://edunham.net/2016/04/11/plushie_rustacean_pattern.html

+1 for Pizza.

**Comment by Florob** [comment]
@fyl2xp1 You have to thank @colin-kiegel for the kudos, this is the text from last month's ticket I copied.

I'm not sure "In `mod` we Rust!" is a good idea. Rust's module systems seems like one of the parts people tend to dislike. Though maybe that just makes it an even better pun…

@badboy As I've already said in person I'm increasingly hesitant about talks on blockchain technology, but I've no strong opinion on it.

If there is any interest, I could do either of the two following talks:
* Inline Assembly — Mostly a survey of the design space, I'm trying to write a pre-RFC and would be happy to have some discussion
* The Importance of Caches — Not exactly Rust specific, but relevant to systems programming in general

**Comment by kawogi** [comment]
I'd happily vote for Inline Assembly *and* Caches :)

**Comment by badboy** [comment]
*Inline Assembly Caches!*

I'm all in favor in having local speakers, but I don't think having two talks by the same person is a good idea.

Soooo .... who wants to do the second one?

**Comment by killercup** [comment]
-1 for remote speakers this time. I don' think having a remote speaker for the first time at the anniversary meetup is a good idea.

+1 for Pizza Rustica. And/or pizza with a big R made out of olives. And/or other pizza.

+1 for inline assembly, as we tend to have a lot of folks interested in low-level things.

I'm not sure we need a second talk, but we should have a "this year in Rust" thing. Maybe we can collect a list of features (from release notes, official anniversary blog post), and switch up our introduction round to have everyone pick a piece of paper from an urn with one "this changed in Rust in the last year" item on it, and present that one.

- - -

FYI and before I forget, @nhellwig talked about tokio-cassandra at the last meetup (#26) and mentioned he might also be up to talk more about that in the future. Maybe we can do a networking/tokio meetup soon?

**Comment by badboy** [comment]
omnomnom 🍕 
I like the idea of talk & "this year in Rust"

**Comment by killercup** [comment]
Okay, June is less than two weeks away, we should probably announce the meetup this weekend!

I propose we go with this agenda:

0. Introductions
1. This year in Rust
2. Pizza (sponsored by Mozilla, @badboy?)
3. @Florob's talk

Preliminary invitation:

```markdown
Title: CGN: Rust 2nd Anniversary Reloaded

Dear Rustaceans!

It is official: It's been two years since Rust's 1.0 release! And that means we
need *two* meetups to celebrate that – good thing we already had a test run for
that last year!

That's why we invite you to join us **on June 7 at 19:15 CEST**!

Our agenda so far is this:

* A short summary of what happened the last year in Rust. If you have something
that really excited you and that you want to share, you are very welcome to do
so!
* Florian will talk about […]

Oh, and also, there will be pizza!

**[You can register here](https://www.meetup.com/de-DE/RustCologne/events/239100622/)**.

We are looking forward to seeing you. :-)

Yours, Jan-Erik, Pascal, Florian and Colin

---

The meetup will likely be held in German, we will however reevaluate this at the
beginning of the evening and may switch to English if needed.
```

- - -

@Florob, you proposed two talks, and I think so everyone liked both. :) Which one do you want to give? Maybe you can expand/adapt/throw-away-and-rewrite the invite text above and add a short summary for your talk?

**Comment by badboy** [comment]
I'll check with Mozilla

**Comment by Florob** [comment]
I've updated the issue with a current invitation draft. @Rustaceans/organizers-cologne feel free to correct any typos, or issues, and flesh it out further if necessary.
I went with Inline Assembly somewhat arbitrarily (i.e. because @killercup technically +1ed Inline Assembly, but not Caches when I tallied the votes)

**Comment by badboy** [comment]
Request for sponsorship: ✓

**Comment by badboy** [comment]
Changed the last sentence in the description of Flo's talk (marked the old one with ~~, but sadly inline-code markdown doesn't show it as crossed-out).
Otherwise it's good to go. @killercup can you add it on meetup and get this rolling?

**Comment by killercup** [comment]
Nice. "Free" is one of my favorite flavors of pizza ;)

Can you send out the invitation? I'm a bit busy right now, and would probably only get around to it this evening/tomorrow morning.

**Comment by badboy** [comment]
weeeell. can't promise "free" just yet, but we're on a good way there.

Let me frickle with meetup and figure this out.

**Comment by badboy** [comment]
Took care of meetup, website, twitter and the calendar now. Let's hope for signups!

**Comment by killercup** [comment]
Awesome, thanks!

**Comment by badboy** [comment]
Pizza is a go.
