### ISSUE TITLE
July 2017 Meetup

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#34]
# ToDo

- [x] Settle for a date: 2017-07-05
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline **2017-06-30**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/240619280/)
  - [x] [website](http://rust.cologne/2017/07/05/live-coding.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/878613243379556352)
  - [x] [community calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MmloOWpudGVxbThkMjJpYTg5bWNmcGU2anUgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/6j8x0m/meetup_in_cologne_on_20170705_rust_livecoding/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/11524)

# Invite draft

```markdown
Title: CGN: Rust Live-Coding (Newbies are very welcome!)

Hello everyone!

Are you new to Rust?

No matter if yes or no, we welcome you to our next meetup.

Matthias Endler is going to pick a beginner-friendly problem
and do some live coding for us. So you can just watch, listen
and ask questions about it.

After that we will have our usual discussions about Rust. You
can bring your questions + problems and see if someone can help.

**Wednesday 2017-07-05, 19:15 CET**

Agenda
* live coding
* discussion / drinks / fun :-)

**[You can register here](https://www.meetup.com/RustCologne/events/240619280/)**.

We are looking forward to seeing you. :-)

Yours,
Jan-Erik, Pascal, Florian and Colin
―  
The meetup will likely be held in German, we will however
reevaluate this at the beginning of the evening and may
switch to English if needed.
```

# Rust news

* RustConf program
* [`rustfmt` changes](https://users.rust-lang.org/t/rustfmt-releases/11357)
* [Rust 1.18.0](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
* [hyper 0.11: "The async release"](http://seanmonstar.com/post/161786147642/hyper-v011)

# Ideas for future meetups

* embedded on ARM
* parsing (nom, …)
* other ideas?

**Comment by killercup** [comment]
As mentioned yesterday, neither @badboy nor myself can attend on the first Wednesday in July. While I'll be hanging out in Hamburg (and maybe crash a meetup there?), Jan-Erik will apparently be in an induced coma after submitting his Master's thesis. [Edit:] We **don't** ask you to move the date, though.

I only ask one thing: If you move the meetup to a beach bar—and it's awesome—can we repeat that in August?

**Comment by colin-kiegel** [comment]
I'm ok with another date in July, I'm flexible. I suggest we pick another day of the week, too. E.g. Monday, so people with busy Wednesdays can attend more easily this time. What do you think?

**Comment by Florob** [comment]
From what I've heard in person I suspect @killercup meant "We don't ask you to move the date".
I'm personally fine with doing Monday, I'm not sure how much that "helps" though. @badboy will certainly still be busy writing/reviewing his thesis and I don't know about @killercup's travel arrangements.

At any rate we should probably settle on a date, or (as was also suggested) on taking a summer break, soonish.

**Comment by killercup** [comment]
Ohh, yes! I meant to write "**don't** ask you"! So sorry! That's a typo with quite the impact 😅

**Comment by badboy** [comment]
Right, this time you definitely should not worry about my attendance. Even shifting would not help much, as I will be busy both the week before and after.

Nonetheless, we should make _some_ decision soon and communicate that.

**Comment by badboy** [comment]
Any decision yet?

**Comment by badboy** [comment]
We should really find a solution here or officially cancel the July meetup (Summer Break!)

**Comment by colin-kiegel** [comment]
Hello everyone, I just arrived this week from my vacation. :-)

@Florob It seems to be you and me for July. Right now I am a bit out of the Rust loop. And I don't really know, what we could offer in July without you guys. I am slightly in favour of skipping the next meetup then. What do you think?

PS: In the first week of _August_ I will be on another vacation, so I cannot attend the second meetup from now. But I could help with brainstorming on the agenda and sending the invitations.

**Comment by mre** [comment]
For what it's worth I just came back from trivago's internal conference and I did some Rust live coding there. Although it was pretty basic, I've received quite some positive feedback. If you guys are interested, I could do the same at Rust Cologne. Either first week of July or in August.

**Comment by colin-kiegel** [comment]
@mre That sounds very good to me. IMO we could do that first week of July. If it's basic that's good too. I was thinking about having some kind of beginner oriented meetup once in a while.

Do you have any idea what your live coding could be about?

**Comment by mre** [comment]
@colin-kiegel sounds great. At the conference I implemented [bubblesort](https://github.com/mre/the-coding-interview/blob/master/problems/bubble-sort/bubble_sort.rs)  and [closed_loops](https://github.com/mre/the-coding-interview/tree/master/problems/closed-loops).

Bubblesort was a nice introduction to ownership, borrowing, and traits. Closed-Loops introduced some functional concepts, expressions, and `match`. 

My idea was to implement a [binary tree check](https://github.com/mre/the-coding-interview/tree/master/problems/binary-search-tree-check) and compare it with my Python solution. It want to explain why Rust is more explicit in some cases compared to a dynamically typed language.
Afterwards I wanted to pick any random task go from there. Usually this is the most fun part.

**Comment by killercup** [comment]
That sounds pretty cool, @mre! I have tremendous respect for anyone who even tries to live-code something in front of an audience! :) I'm sad to miss it.

Another topic that was mentioned a bunch of times in recent meetups was IDE support. The RLS integration in vscode is good and the installation using rustup has become pretty smooth (the only thing I needed to change was setting the executable path to `rustup run rightly rls` to get the right env vars). Maybe that's something you could talk about as well, in case the live coding doesn't take all evening.

**Comment by colin-kiegel** [comment]
@mre + @Rustaceans/organizers-cologne: I've written the [invitation draft](https://github.com/Rustaceans/rust-cologne/issues/34#issue-234593515). Do you approve this text?

**Comment by mre** [comment]
Perfect. Approved. 😃

**Comment by badboy** [comment]
✓

**Comment by colin-kiegel** [comment]
Ok, I'll update the meetup text and send invitations. :-)

**Comment by colin-kiegel** [comment]
Ok, _mostly_ done. Website and reddit still missing (@killercup?.. ^^)

**Comment by killercup** [comment]
Added to the website and posted to Reddit.

Feel free to expand the description on the website (just edit [this file](https://github.com/Rustaceans/rust-cologne/blob/gh-pages/_posts/2017-07-05-live-coding.md)), I've only copied the invitation text.

**Comment by colin-kiegel** [comment]
I'd say, we had a very nice meetup with a lot of new faces. @mre, thx again for the live coding. :+1:
