### ISSUE TITLE
August 2017

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#35]
# ToDo

- [x] Settle for a date: **2017-08-02**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline **2017-07-23**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/241358482/)
  - [x] [website](http://rust.cologne/2017/08/02/crate-polishing.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/887223596216717316)
  - [x] [community calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=YzlucTUxMWszaWF2czhuazFyZ3VtamVvbzggYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/6nzes8/another_crate_polishing_meetup_in_cologne_2nd/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/another-crate-polishing-meetup-in-cologne-2nd-august-7pm/11897)

# Invitation draft

```markdown
Title: CGN: Crate Polishing Workshop

Fellow Rustaceans,
 
our next meetup is set for the first Wednesday in August: **Wednesday 2017-08-02, 19:15 CEST**.
 
Based on the positive feedback in April, we will do another **Crate Polishing
Meetup**.

But this time, we'd like to skip the search for crates and issues: Instead, we
want to use the list of issues (and guidelines!) the Rust Libs Team's new [Libz
Blitz] initiative has created over the last months, and dive right into fixing
and improving code. You can, of course, work in teams.

One bonus for working on these issues: You can win RustFest Zürich tickets
(incl. travel and accommodations)! See [the RustFest announcement][rustfest] for more details.

If you have a suggestion, feel free to comment in our [planning issue].

[Libz Blitz]: https://internals.rust-lang.org/t/rust-libz-blitz/5184
[rustfest]: http://blog.rustfest.eu/libz-blitz
[planning issue]: https://github.com/Rustaceans/rust-cologne/issues/35

**[You can register here](https://www.meetup.com/RustCologne/events/241358482/)**.

See you soon!
 
Yours,
Jan-Erik, Pascal, Florian and Colin
―  
The meetup will likely be held in German, we will however reevaluate this at the
beginning of the evening and may switch to English if needed.
```

# Rust News

- [Rust 1.19](https://blog.rust-lang.org/2017/07/20/Rust-1.19.html)
  * `union`s
  * `loop {}` can `break` with a value
  * `eprintln!()`
- [stack probes on x86](https://github.com/rust-lang/rust/pull/42816)
- [top 100 crates available on the playground](https://users.rust-lang.org/t/the-official-rust-playground-now-has-the-top-100-crates-available/11817)

**Comment by colin-kiegel** [comment]
Ok, here we go. August is approaching!

At the last meetup we asked what everyone would be interested in for future meetups. We got these responses:
- How-to work with macros (introductory level)
- Interacting with the OS
- Best practices
  - How to structure Rust crates
  - API design
  - How to define errors
- Live coding with Rosetta code
- Crate polishing e.g. sth. from the most recent [_This Week in Rust > Call for Participation_](https://this-week-in-rust.org/blog/2017/07/04/this-week-in-rust-189/#call-for-participation)

Right now I don't know of anyone, who would be interested in giving a talk. Because of the limited time for preparation, I would suggest one of the following
- Crate polishing
- Open space

@Rustaceans/organizers-cologne I'll not be around in the first week of August, but I can help a little with the usual stuff like sending out the invitations and brainstorming. What do you guys want to do in August?

**Comment by killercup** [comment]
> At the last meetup we asked what everyone would be interested in for future meetups.

Thanks for the great summary, @colin-kiegel!

To collect ideas for talks/topics outside of these event-focused issues I've created [this project board](https://github.com/Rustaceans/rust-cologne/projects/1) and added Colin's points from above as well as some of the previously suggested/used topics. If you think this is a good idea, let me know. Oh, and feel free to add/move/edit items! :)

> Right now I don't know of anyone, who would be interested in giving a talk.

@Florob, are you still interested in talking about caches? This is something I'd personally be interested in, but the list from above doesn't really have any low-level things (may depend on the audience though).

> Crate polishing

Maybe we can combine this with the sponsoring of [15 free Rustconf tickets for Libz Blitz participants](http://blog.rustfest.eu/libz-blitz)!

**Comment by Florob** [comment]
I'm happy to talk about caches eventually. Not necessarily at the upcoming meetup though. I'm still not entirely sure where to strike the balance on low vs. high level topics. Similarly we should find a beginner/advanced balance somewhere.
I think crate polishing would be nice for the next meetup. Maybe someone wants to give a quick overview over some API conventions before we dig in.

**Comment by colin-kiegel** [comment]
Hey @Rustaceans/organizers-cologne, I just sent the save-the-date reminder as the date seemed fixed already and it was about time. :-)

I updated the invitation draft to reflect the idea to make a crate polishing workshop. Please review, if you like it this way. It's based on the last crate-polishing-invitation with minor modifications (no special guest this time ;-))..).Please remember, that I will not be present at the meetup itself - I'm just helping out with the invitations.

I'd target next weekend to send the final invitation, ok?

**Comment by badboy** [comment]
Sorry for not jumping in earlier. Thanks, @colin-kiegel for taking care of the invitation.
I'll review the content later today.

**Comment by killercup** [comment]
Thanks @colin-kiegel! I was about to suggest sending the invitation out tomorrow with the beginning of the new week.

I think I'd focus more on the libz blitz issues and mention the possibility of winning a RustFest ticket:

```markdown
Based on the positive feedback in April, we will do another **Crate Polishing
Meetup**.

But this time, we'd like to skip the search for crates and issues: Instead, we
want to use the list of issues (and guidelines!) the Rust Libs Team's new [Libz
Blitz] initiative has created over the last months, and dive right into fixing
and improving code. You can, of course, work in teams.

One bonus for working on these issues: You can win RustFest Zürich tickets
(incl. travel and accommodations)! See [here][rustfest] for more details.

If you have a suggestion, feel free to comment in our [planning issue].

[Libz Blitz]: https://internals.rust-lang.org/t/rust-libz-blitz/5184
[rustfest]: http://blog.rustfest.eu/libz-blitz
[planning issue]: https://github.com/Rustaceans/rust-cologne/issues/35
```

**Comment by colin-kiegel** [comment]
@killercup cool, I like it. Feel free to update the draft. :-)

**Comment by badboy** [comment]
I like it as well!
small change:

```patch
- See [here][rustfest] for more details.
+ See [the RustFest announcement][rustfest] for more details.
```

**Comment by killercup** [comment]
I changed the invite in the issue description. Anyone else want to add something? I think it's good to go. (I'll only have time to send it out this evening; if you want to, feel free to send it out earlier.)

**Comment by killercup** [comment]
Sent an email and ticked some boxes. Anyone else want to have some social media flavored fun? 😄

**Comment by badboy** [comment]
calendar, reddit done. Next: urlo

**Comment by badboy** [comment]
urlo done

**Comment by killercup** [comment]
So, to prepare for tomorrow, let's gather some issues!

- [error_chain things, incl. many easy issues](https://github.com/rust-lang-nursery/error-chain/milestone/1)
- [same file](https://github.com/BurntSushi/same-file/issues/15)
- [walkdir](https://github.com/BurntSushi/walkdir/issues/47)
- [memmap](https://github.com/danburkert/memmap-rs/issues/38)
- [flate2](https://github.com/alexcrichton/flate2-rs/issues/89)

Or, how about an ad hoc evaluation? Just grab the [API guidelines](https://github.com/brson/rust-api-guidelines) and a crate like

- [deflate](https://github.com/oyvindln/deflate-rs/issues/19)
- [fnv](https://github.com/servo/rust-fnv)
- [tar](https://github.com/alexcrichton/tar-rs)
- a bit larger but already underway: https://github.com/kbknapp/clap-rs/issues/950

Or: Contribute to [the Rust Cookbook](https://github.com/rust-lang-nursery/rust-cookbook/issues?q=is%3Aissue+is%3Aopen+label%3Aeasy).

[Even more stuff!](https://github.com/issues?utf8=✓&q=%22libz+blitz%22+is%3Aissue+is%3Aopen)

**Comment by KodrAus** [comment]
Thanks for getting on board with this. You guys are totally awesome! :100:

**Comment by killercup** [comment]
Thank you all for coming tonight!
