### ISSUE TITLE
September 2017

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#37]
# Talks talks talks

We are looking for (you guessed it) talks!

**If you'd like to give a lightning talk at this meetup, just write a comment!**

Talks we have so far:

- @mre: [RFC 2052: Evolving Rust through Checkpoints](https://github.com/rust-lang/rfcs/pull/2052)
- @badboy: [RFC 2116: fallible collection allocation 1.0](https://github.com/rust-lang/rfcs/pull/2116)

Other people who've expressed interesting in giving a talk:
- @killercup [RFC 1946: Intra Rustdoc Links](https://github.com/rust-lang/rfcs/pull/1946)
- @colin-kiegel [RFC 2126: Clarify and streamline paths and visibility](https://github.com/rust-lang/rfcs/pull/2126)
- @florob [RFC 1228: Placement left arrow](https://github.com/rust-lang/rfcs/pull/1228)

# ToDo

- [x] Settle for a date: **Wed, 2017-09-06, 19:15 CEST**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline ???)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/mtcmwmywmbjb/)
  - [x] [website](http://rust.cologne/2017/09/06/lightning-rfcs.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/899719385421688834)
  - [x] [community calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MjZmdnA1Y2hrY2FmcGdzYzB2N2ZwOG5wanUgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/6v9zlo/rust_cologne_rfc_lightning_talks/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/cgn-rfc-lightning-talks/12480)

# Invitation draft

```markdown
Title: CGN: ???

Fellow Rustaceans,
 
our next meetup is set for ???.
 
???

**[You can register here](https://www.meetup.com/RustCologne/events/mtcmwmywmbjb/)**.

See you soon!
 
Yours,
Jan-Erik, Pascal, Florian and Colin
―  
The meetup will likely be held in German, we will however reevaluate this at the
beginning of the evening and may switch to English if needed.
```

# Rust News

- [Rust 1.20](https://blog.rust-lang.org/2017/08/31/Rust-1.20.html)
  * associated constants
  * stack probes
- Rust confs tickets and stuff
- [builtin `Copy` types now implement `Clone`](https://github.com/rust-lang/rust/pull/43690)

# last month Rust News
- [Rust 1.20](https://blog.rust-lang.org/2017/08/31/Rust-1.20.html)
  * associated `const`s
- [Rust 1.19](https://blog.rust-lang.org/2017/07/20/Rust-1.19.html)
  * `union`s
  * `loop {}` can `break` with a value
  * `eprintln!()`
- [stack probes on x86](https://github.com/rust-lang/rust/pull/42816)
- [top 100 crates available on the playground](https://users.rust-lang.org/t/the-official-rust-playground-now-has-the-top-100-crates-available/11817)
- [crates.io renders readmes](https://github.com/rust-lang/crates.io/pull/869)

**Comment by killercup** [comment]
At the August meetup (#35) we discussed the idea of having a round of "RFC lightning talks", where a bunch of people present their favorite/exiting RFCs in 5 minutes each.

If we want to do that, I'd say we need at least 3 talks by the beginning of the last week in August. This is also most likely not a question of find stuff to talk about together (we could probably even reduce the scope to "already merged but not yet implemented RFCs" and still have no trouble of finding topics for 10 talks) but of finding speakers and tie them down for a talk.

**Comment by badboy** [comment]
Date would 6.9., which works for me

**Comment by badboy** [comment]
Should we get started with this, e.g. sending out the save the date, etc?

**Comment by killercup** [comment]
Sure. Do we want to go ahead with the RFC plan, @colin-kiegel, @Florob? Maybe we can even send out an extra-early invite :)

**Comment by Florob** [comment]
I'm fine with sending out an early invite for the "RFC plan". I guess even if no-one else has something to present we should find 3 talks among the four of us.

**Comment by badboy** [comment]
Yup, I'd be fine with it as well and I would happily prepare something to start of

**Comment by killercup** [comment]
Let's just write some new RFCs and present those! Kidding aside, I'd be
happy to present a RFC as well.

Is the format okay? 5min lightning talks?

Jan-Erik Rediger <notifications@github.com> schrieb am Fr. 11. Aug. 2017 um
10:35:

**Comment by colin-kiegel** [comment]
Hey, I like the idea.

If we have three 5-minute talks plus discussion, the official part might be over after one hour. Should we do one round of open-space afterwards, or just leave it to spontaneous activities?

**early-invitation**: IMO an announcement via the mailing list is much more visible than just "publishing" the event. Usually we just publish the event to send our save-the-date reminder, but this is only good for headlines. If we want to send more text (like "please tell us if you want to give a talk ..."), we should do this in a regular mail before/after publishing the event. Does that make sense to you? :-)

**Comment by colin-kiegel** [comment]
Oh and by the way in July someone told me, that it's difficult for him to attend on Wednesdays due to a hobby (singing in a choir every wednesday). I still believe that we should do irregular exceptions to our _first-wednesday-each-month_ rhythm to attract different people once in a while.

So, what about Tuesday 05.09. instead?
@Florob: Most important question is, on which evenings is the C4 available?

**Comment by killercup** [comment]
> If we have three 5-minute talks plus discussion, the official part might be over after one hour.

that's why I wrote

> we need **at least** 3 talks

:)

I think we should aim for 3 to 5 talks and 5min talk + 5min discussion (with hard cuts if necessary).

> So, what about Tuesday 05.09. instead?

Everything but Friday works that week for me. (That way I might even be able to go to the Elixir meetup on the 6th ~~to infiltrate their ranks to copy all their good ideas for make benefit glorious meetup of Rust Cologne!~~)

**Comment by badboy** [comment]
The alternative date would work even better for me.

**Comment by Florob** [comment]
The C4 is taken on Tuesdays. We could probably do Monday the 4th if that works for people.

Personally I'd plan a bit more than 5 minutes for discussion, but we can probably vary that depending on the number of RFCs we actually have.

**Comment by colin-kiegel** [comment]
I don't know yet if I can attend on Monday. But if it works for everyone else that would be ok for me.

**Comment by killercup** [comment]
So Monday or Wednesday? Both work for me.

- - -

> Personally I'd plan a bit more than 5 minutes for discussion

Yep, I'd aim for 5+5 to keep things moving, but not cut off discussions.

- - -

Invite text proposal (feel free to change; get the markdown source be editing my comment; I went with the default Wednesday date for now):

> Fellow Rustaceans,
>  
> Our next meetup is set for **Wednesday, September 6th, 2017**.
>  
> This time, we want to talk not about the Rust we _currently_ know and love, but about the Rust we want to have next year! And how do we know what will happen in Rust over the next year? (Aside from wild speculation, ~~stainless steel~~ crystal balls, and actual time travel that is.) All significant changes to Rust—the compiler, the language, and the ecosystem—are publicly proposed and discussed in form of RFCs (request for comments). You can find the currently open, as well as all accepted and rejected RFCs in the [rust-lang/rfcs][rfcs] repository.
> 
> And boy are there _tons_ of RFCs! So we'd like to try a slightly new format: We invite _you_ to give lightning talks about specific RFCs. Which ones? You decide. The only requirement is that you need to have fun talking about it! We'll try to have 3 to 5 talks, each one up to 5 minutes longs plus 5 additional minutes for discussion.
> 
> If that sounds like something you'd like to do: Awesome! Just comment on [the Github issue for this meetup][gh37], [on meetup.com][meetup] (or contact us some other way) and let us know what you'd like to talk about! :)
> 
> **[You can register here][meetup]**.
> 
> See you soon!
>  
> Yours,
> Jan-Erik, Pascal, Florian and Colin
> ―  
> The meetup will likely be held in German, we will however reevaluate this at the
> beginning of the evening and may switch to English if needed.
> 
> [rfcs]: https://github.com/rust-lang/rfcs
> [gh37]: https://github.com/Rustaceans/rust-cologne/issues/37
> [meetup]: https://www.meetup.com/RustCologne/events/mtcmwmywmbjb/

- - -

Totally OT: I just saw https://twitter.com/bpdp/status/895419283307495425 and I want to have an infographic like that for us as well because it's so pretty but I have no idea why we'd need it 😄

**Comment by colin-kiegel** [comment]
ok, +1 for wednesday. :-)

I also like the invitation text.

**Comment by badboy** [comment]
"And boy are there ..." - I don't like this. Can we change that slightly?

Should we stay strict to the 5min+5min? Or relax it slightly even in writing (I know that for the discussion it's not a hard hard limit)

**Comment by killercup** [comment]
> "And boy are there ..." - I don't like this. Can we change that slightly?

Sure! How about we go all British and say "But, blimey, there are _many_ RFCs!" or stay classy and say "But there sure are _a lot_ of RFCs!"

**Comment by killercup** [comment]
Oh, and I'd want to stay rather strict on the 5min limit. If that leads to people compressing there talk down to most interesting parts… well, I won't complain. If bad comes to worse they can always ask for a few more minutes (and we can decide ad-hoc).

**Comment by badboy** [comment]
5min it is then!

**Comment by badboy** [comment]
I'd say go the (boring|classy|simple) way.

**Comment by colin-kiegel** [comment]
Hehe, I spontaneously liked the enthusiasm of "And boy ..." ;-)

I think one reason for people to come to our meetup is if they expect other people to be enthusiastic about Rust. But don't get me wrong, I don't want to argue over this sentence - I'm perfectly ok with a simple variant, too. I just want to note, that _generally_ I am in favour of enthusiastic, vivid and playful wording (if it doesn't obstruct the message). ^^

**Comment by colin-kiegel** [comment]
Ok, I just sent the pre-invitation and updated the description on meetup! :-)

**Comment by killercup** [comment]
Thanks! Do you also want to announce the meetup? Or wait for a bit before doing that (and probably sending another mail)?

**Comment by colin-kiegel** [comment]
I would wait a few days (maybe until next week), because it's not possible to silently publish the meetup. ^^

Although unpublished, it's already possible to RSVP.

**Comment by colin-kiegel** [comment]
all invitations sent, except for **reddit**

**Comment by badboy** [comment]
will take care of reddit

**Comment by diovudau** [comment]
I'm coming, but as a pure passive visitor.

**Comment by mre** [comment]
If it's okay, I would like to pick [Evolving Rust through Checkpoints](https://github.com/rust-lang/rfcs/pull/2052), since it's one of the most discussed RFCs so far.

**Comment by killercup** [comment]
@mre YES!

…
…
…

You owe me a talk anyway 😉

**Comment by killercup** [comment]
By the way, @Rustaceans/organizers-cologne, should we maybe ping some folks and ask if they want to talk about an RFC they were heavily involved in? Because my fallback idea was to talk about 1946 if we don't have enough other RFCs :) Maybe you feel similarly.

**Comment by badboy** [comment]
We should!
I have 1 or 2 RFCs in mind to do myself, so let's start a list!

**Comment by colin-kiegel** [comment]
@badboy: @killercup already started a list in the first post https://github.com/Rustaceans/rust-cologne/issues/37#issue-247543666 :-)

**Comment by badboy** [comment]
Ok, I will talk about either:

* [2116: fallible collection allocation 1.0](https://github.com/rust-lang/rfcs/pull/2116)
* [2129: Crate changelogs](https://github.com/rust-lang/rfcs/pull/2129)

Which do you prefer?

**Comment by colin-kiegel** [comment]
nice. My vote for fallible collection allocation. :-)

**Comment by badboy** [comment]
as you wish *goes reading*

**Comment by colin-kiegel** [comment]
I could imagine talking about [RFC #2126: Clarify and streamline paths and visibility](https://github.com/rust-lang/rfcs/pull/2126). But the 5min-goal will likely be a challenge. :-)

@killercup I would like to hear about your https://github.com/rust-lang/rfcs/pull/1946.

**Comment by killercup** [comment]
Ohhh, 2126 is a good idea! I totally tuned out of that discussion a while ago 😄

Also: We should totally mention <https://request-for-explanation.github.io/podcast/>!

**Comment by Florob** [comment]
I'd like to talk about [RFC 1228: Placement left arrow](https://github.com/rust-lang/rfcs/pull/1228).
Probably also a case where fitting motivation and birds eye view of the RFC in 5 min will take some work though.

**Comment by killercup** [comment]
Thanks all!
