### ISSUE TITLE
October 2017

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#39]
# ToDo

- [x] Settle for a date: **Wed, 2017-10-04, 19:15 CEST**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [ ] Final invitation (deadline ???)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/243156120)
  - [ ] [website]
  - [x] [twitter](https://twitter.com/RustCologne/status/912796031150063617)
  - [x] [community calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=NGRtdGVwMDRnOG00M2RjYmhscTdpNnYxdGkgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [ ] [reddit]
  - [x] [rust-lang forum](https://users.rust-lang.org/t/cgn-open-space-meetup-wed-2017-10-04/13066)

# Invitation draft

```markdown
Title: CGN ###: Open Space

Hey everyone,

it's time to talk Rust again! :-)

**Wed, 2017-10-04, 19:15 CEST**

This time we will do another round of **open space** discussions. In the beginning we will collect ideas for discussion topics or other activities. Then you are free to join other people on one of these discussions or activities. Which one? You choose.

It's quite informal, and it's a lot of fun!

[You can register here](https://www.meetup.com/RustCologne/events/243156120).

**We are looking forward to seeing you**. :-)

Yours,
Jan-Erik, Pascal, Florian and Colin
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne It has been suggested to try another **Crate Polishing Workshop** in October. However last time, one month ago, we had only very few participants.

_Alternatively_, we could try some kind of **open-space** like meetup again. In other words, be spontaneous in small groups with a fancy name.

=> What would you prefer? Do you have other suggestions?

**Comment by colin-kiegel** [comment]
I just sent our save-the-date announcement via meetup, did anyone get it? Because I'm still waiting for it...

.. any thoughts on what you guys want to do on our October meetup?

**Comment by killercup** [comment]
@colin-kiegel yep, got the mail at 10pm sharp.

So, this meetup might be tricky for me time-wise. I'm quite busy the next weeks and looking at the meetup date, I'll only get back from RustFest Zürich the night before and will need to be in Düsseldorf the next morning. Thus, I'd be very okay with this being a low maintenance event :)

If someone's interested, I can always talk about the kickoff of the impl period in Zürich.

**Comment by colin-kiegel** [comment]
@killercup Ok, good to know. Because I still didn't get any mail. Looks like meetup just got smarter, not to send the mail to the sender. :-)

I think open-space is about as low maintenance as we can get.
EDIT: And it could also be an umbrella for both some crate-polishing and short talks in smaller groups.

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne Hm, we're a bit overdue with our final invitation... I'm very busy this week. Any help welcome. If no one else has time, I think I will have some spare time tomorrow late evening. ;-)

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne I sent most invitations (as usual except reddit+website).

**Comment by killercup** [comment]
Thank you so much Colin!

Colin Kiegel <notifications@github.com> schrieb am Di. 26. Sep. 2017 um
23:55:

**Comment by colin-kiegel** [comment]
@killercup Since we don't have a lot of rsvps yet, I'm thinking if we should tease about you talking a little bit about RustFest on Wednesday - Maybe something like this (via our mailinglist):

```markdown
PS: If you couldn't make it to **RustFest** in Zurich, you can get some
first hand impressions from Pascal at our next _open space_ meetup
this Wednesday, Oct 4th, 19:15 CEST:
https://www.meetup.com/RustCologne/events/243156120
```

 What do you think?

**Comment by killercup** [comment]
Sure, sounds good!

**Comment by killercup** [comment]
Did we ever add this to the website? If not, can anyone do that? Otherwise I'll probably only get around to it on the weekend. Feel free to close this issue afterwards.

**Comment by colin-kiegel** [comment]
Nope, we didn't. And I will not have time before the weekend either.. We could also combine this with announcing our next meetup. IMO a few days more or less are not very significant anymore, now that this meetup is already over.

**Comment by killercup** [comment]
Indeed. Alright, let's do it when we have a new announcement.

Colin Kiegel <notifications@github.com> schrieb am Do. 5. Okt. 2017 um
10:51:
