### ISSUE TITLE
November 2017

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#40]
# ToDo

- [x] Settle for a date: ~~Wed, 2017-11-01, 19:15 CEST~~ **Thu, 2017-11-02, 19:15 CEST**
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [ ] **Find a location** :warning: 
- [ ] Final invitation (deadline ???)
  - [ ] [meetup]
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

**Comment by badboy** [comment]
The November would fall on the 1st November, which is a holiday.
Mozilla is planning a [Dev Roadshow](http://mzl.la/devroadshow) around that time and Sandra asked if we would like to make this a joint-thing with Rust Cologne.
We could potentially look for other (bigger) venues and Mozilla would probably sponsor a bit.

**Comment by killercup** [comment]
Oh, nice! Then we need an especially spectacular topic for November!

**Comment by badboy** [comment]
and speakers! But ... given Mozilla's involvement, maybe another special guest?

**Comment by Florob** [comment]
So… I'm a bit confused. What exactly is the Dev Roadshow? The page @badboy linked is a bit opaque. From <https://medium.com/@SandraPersing/its-all-about-the-developer-roadshow-31736d2f0556> I gather Sandra plus some developers are touring North America and Europe presenting $things? In that case that doesn't sound like "special guest" would be a question mark.

**Comment by badboy** [comment]
The Dev Roadshow is a moving meetup trying to provide evenings dedicated to Mozilla-related technologies. For the first few rounds they had a couple of known faces giving talks, but they also try to source local folks if possible. Sandra will probably not be there for Cologne, but will remotely help with up-front organisation (plus swag & hopefully sponsorship).

This is only an offer, we don't _have_ to do this. This is a Mozilla marketing event in the end.

**Comment by colin-kiegel** [comment]
I like the general idea of co-op meetups, and even more so if it is with Mozilla. So if we say yes, which I think we do, then Sandra would make some agenda suggestions and help looking for speaker(s), right?

**Comment by badboy** [comment]
Right. I'll put you in touch with here via email (as I'm on vacation for the next few weeks)

**Comment by Florob** [comment]
Just as a general remark/reminder: If we're going with November 2nd we **have to** find a different location.

**Comment by colin-kiegel** [comment]
I've added _finding a location_ to our todo list. From what we know so far it should be at least the size of our usual C4 location.

Something a bit more fancy would be very nice for this meetup. Maybe we could ask some tech-oriented companies in the Cologne Rheinauhafen area?

**Comment by Florob** [comment]
Updating the ticket with the current status:
This is apparently not happening, due to a lack of speakers.
Generally I'd be into at least doing an OpenSpace meetup with little organization overhead, but the 1st is a holiday, and on the 6th which I'd otherwise suggest the C4 happens to be occupied.
So likes are not looking that bright for November I guess.
22nd or 29th would work, but I guess generally it's not looking too bright for November.

**Comment by colin-kiegel** [comment]
Ok, I removed the meetup `save-the-date` placeholder - since we don't have a date and it would be misleading if we kept it saying "Nov 1st". If we still decide to organize something for november, we can still create a new event on meetup.
