### ISSUE TITLE
December 2017 - impl Glühwein?

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#42]
# ToDo

- [x] Settle for a date: **2017-12-06, 19:00 CET**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline **???**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/244487721)
  - [x] [website](http://rust.cologne/2017/09/06/impl-gluhwein.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/927991563917152257)
  - [x] [community calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=M2pxc3U4dGNlbTBiNzZvdTQ4bGxtMzNvYTIgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [ ] [reddit]
  - [x] [rust-lang forum](https://users.rust-lang.org/t/cgn-meetup-impl-gluhwein-wine-glass/13747)

# Invitation draft

see https://github.com/Rustaceans/rust-cologne/issues/42#issuecomment-342156207

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne 
- who is interested to go?
- would December 6th (first Wednesdasy) be a good date?

**Comment by badboy** [comment]
I'm in! I'd be happy to meet and 6.12. would work for me.

**Comment by killercup** [comment]
Ah, thanks for reminding me! I'm in, too, and the 6th works for me! Do you have an idea for a location? A Christmas market (like last year), or self-made Glühwein (and other beverages) at the C4?

**Comment by badboy** [comment]
It will be quite full at the market, just as last time.
A glühwein- (and alcohol-free punsch-) themed evening sounds good to me as well.

**Comment by colin-kiegel** [comment]
@killercup: You have a slightly more informal style to write meetup invitations - and I think that would be quite fitting for this kind of meetup. Do you want to give it a go? ;-)

**Comment by killercup** [comment]
Voilà (thanks @badboy for reminding me):

> Dear fellow lovers of programming languages with lifetimes, fungi, and/or iron oxide,
> 
> The time has come to invite you all to our annual Holiday-themed meetup! This year, we are pleased to announce that instead of going to an ~~overcrowded~~ cozy Christmas market, our December meetup will be at our usual location, the C4, on December 6. There, we'll enjoy Glühwein, and self-made (non-alcoholic) punch, as well as the usual Rust discussions. The festivities begin at 7pm and while we do not have a formal dress code, people wearing Santa hats will most likely get their drinks first.
> 
> We hope to see you all in December!
> 
> Yours,
> Jan-Erik, Pascal, Florian and Colin
> 
> - - -
> 
> The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed. Depending on the number of attendees and the rate of Glühwein consumption, we may also gradually switch to shorter sentences in whatever language we settled on as the evening progresses.

**Comment by colin-kiegel** [comment]
Haha, great. :+1:

I can send the invitation tomorrow, if noone else does this before.

Who wants to buy the Glühwein / Punch?

**Comment by killercup** [comment]
lol #rust-community

```
[21:33:27]  <&badboy>	impl Glühwein is coming! https://twitter.com/RustCologne/status/927991563917152257
[22:02:23]  <~Manishearth>	badboy: im sorry non ascii identifiers are not allowed on stable rust
[22:02:38]  <&badboy>	Manishearth: and that's a shame
[22:02:40]  <@carols10cents>	Manishearth: the party is clearly nightly only
```

**Comment by badboy** [comment]
As I'm traveling from far I can't bring (much) Glühwein with me. 
There's a supermarket next door. Given the season we might get unlucky if we turn up there shortly before the meetup though.

**Comment by Florob** [comment]
If someone wants to help me estimate an amount I am happy to get some beforehand and probably store it at the space.

**Comment by colin-kiegel** [comment]
@Florob: When do you need the estimate? We can monitor the number of rsvps.

**Comment by colin-kiegel** [comment]
@Florob: I would say 300ml Glühwein + 100ml Punsch per Person will be _more_ than sufficient on average. And we can donate any leftovers to the C4. ^^

PS: And IMO it's not a drama either if we have to switch to other drinks after this.

**Comment by Florob** [comment]
@colin-kiegel: Which getting closer to the event leaves the question of what to actually buy.
The announcement promises self-made Punch. Is anyone actually going to make good on that promise, and what would be the required ingredients?
Is there a Glühwein Brand that actually tastes decent (I'm told we actually still have plenty of disgusting Glühwein at the C4), or do we want to make that ourselves too?
I can somewhat easily get stuff beforehand, I can't really be there early to "cook" things though.

**Comment by colin-kiegel** [comment]
I'd be ok with buying bottled stuff. Uhm @killercup, you wrote self-made.. do you know how? ^^

**Comment by killercup** [comment]
Haha, I did, didn't I? It just felt right to write it this way… but okay, seems like I have to live with the consequences, then.

Luckily, Punch seems easy to make. The typical recipe is: Put twice as much apple juice as grape juice in a bowl, heat it up without boiling, add some Christmas-typical spices (cinnamon, orange). I have no problem making that (I'd rather drink the Glühwein myself though).

**Comment by badboy** [comment]
Proven to be pretty good Glühwein: ![glühwein](https://tmp.fnordig.de/dsh/Photo-2017-11-17-00-14.jpg)

**Comment by colin-kiegel** [comment]
Another recommendation would be organic companies like Voelkel, Rabenhorst, etc. - they're usually more on the quality side. Even those more costly ones will be cheaper than the ones from christmas market stalls.

**Comment by Florob** [comment]
Status update:
There are 4.5L Glühwein at the C4. Those are not new, i.e. they have been at the space for a while and weren't bought by me. Ike and me tried some (that's where the 0.5L come from) and decided it's alright. We can have that at the usual price for drinks and it fits the 0.3L per person calculation. If you guys feel uncomfortable with that I can still get some within the next two days.

For punch I got a nice recipe of my mother that uses tea instead of letting spices simmer in juice for hours. @killercup unless you have plans/ingredients already, I'd just get ingredients for that so we have a quick-ish way to make punch.

**Comment by killercup** [comment]
Thanks for the update, @Florob!

I didn't buy any ingredients yet (and I don't think I own any we could
use). A recipe you got from your mom sounds much more trustworthy than what
I found on Chefkoch.de so let's go with that! I still feel responsible for
making self-made punch, so I'll try to stop by a bit earlier on Wednesday
to help set things up and prepare whatever we need to help make our thirsty
and cold visitors feel welcome. (I'm not bringing any Santa hats though.)

Florob <notifications@github.com> schrieb am So. 3. Dez. 2017 um 23:14:

**Comment by badboy** [comment]
Sounds good. I try to be there early as well.

**Comment by mre** [comment]
Let's all bring some cookies and chocolate! 🍪 I'll bring some gingerbread.

**Comment by killercup** [comment]
Great idea! I don't have anything I baked myself (which is almost likely
better for everyone anyway) but I'll make sure to pick something up in my
way to the C4!

Matthias Endler <notifications@github.com> schrieb am Di. 5. Dez. 2017 um
18:04:
