### ISSUE TITLE
January 2018

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#44]
# ToDo

- [x] Settle for a date: **Wednesday 2018-01-08**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline **???**)
  - [x] [meetup](https://users.rust-lang.org/t/cgn-rust-open-space-monday-january-8th/14757)
  - [x] [website](http://rust.cologne/2018/01/08/open-space.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/947448427885006848)
  - [x] [community calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=MHV2cXBvbjcxanRhN3N2MTU3OWRkMmVvODIgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/7nvza8/open_space_meetup_rust_cologne_monday_8th_january/)
  - [x] [rust-lang forum](https://www.meetup.com/RustCologne/events/245799713/)

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Monday 2018-01-08, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](https://www.meetup.com/RustCologne/events/245799713/)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- [Rust 1.23](https://blog.rust-lang.org/2018/01/04/Rust-1.23.html)
- [Blog: Rust in 2017: what we achieved](https://blog.rust-lang.org/2017/12/21/rust-in-2017.html)

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne 
- Yesterday we agreed to do another informal meetup in January, due to the winter holidays. What do you think about ordering pizza in the beginning? We could call it "Rust and Pizza" meetup then, just to add a little variation. ;-)
- And we still need a date in January - what about second week? @Florob is there a chance to get the C4 room?

**Comment by colin-kiegel** [comment]
@Florob *ping* on what dates can we use the C4 location in January? :-)

**Comment by Florob** [comment]
If we're going for the second week, we'd have to do Monday.
We can probably have pretty much any Monday in January.
Wednesdays are more problematic, the 2nd and 3rd are always taken and I don't think we want to be any later in the month.

**Comment by colin-kiegel** [comment]
@killercup, @badboy 
- what's better for you, Monday 8th or 15th?

@Rustaceans/organizers-cologne 
- do you want to do an open space meetup (without pizza), which could then serve as our new "invitation template"? Or do you want to do another informal meetup, like "Pizza + Rust"?

**Comment by killercup** [comment]
I'm fine with either date. And I wouldn't say no to pizza!

**Comment by badboy** [comment]
I see people are already RSVPing to the save the date, which is currently set for the 3rd. Should we advance with either of the Monday dates?

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne I suggest to go with **Monday 8th** then, just to get things moving again. BUT I will most likely not be there myself - so _please_ feel free to overrule my suggestion! I will start sending out invitations tomorrow, if no one stops me. ;-)

**Comment by badboy** [comment]
Works for me!

**Comment by colin-kiegel** [comment]
Ok, done - except Website and Reddit.

**Comment by killercup** [comment]
Quite a good meetup! I think we might have figured this open space thing out now ;)

We should probably make the Topic Suggestion and Prioritization Process™ a bit more clear. A visible timer might also help.
