### ISSUE TITLE
February 2018

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#46]
# ToDo

- [x] Settle for a date and location: **Wednesday 2018-02-07, 19:15 CET** at C4 _(default date)_
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **2018-01-24**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/kfkwcpyxcbfb/)
  - [x] [website](http://rust.cologne/2018/02/07/open-space.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/956151271152672773)
  - [ ] [community calendar]
  - [ ] [reddit]
  - [x] [rust-lang forum](https://users.rust-lang.org/t/rust-cologne-february-2018-meetup/15247)
  - [ ] [rustplatz]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday 2018-02-07, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Rust News
- [Rust Belt Rust Recordings are available](https://www.youtube.com/playlist?list=PLgC1L0fKd7Ul71lD_cImGuMxsZ6J8fa06)
- FOSDEM Rust Devroom
  - [was pretty crowded](https://twitter.com/matthiasendler/status/960152437217775616)
  - [had a queue](https://twitter.com/nbaksalyar/status/960098618853163008)
  - [Recordings are available](https://www.youtube.com/playlist?list=PL85XCvVPmGQjBZGvlsXmiT8UAHKUddrI9)
- [Lots of #Rust2018 blog posts were written](https://readrust.net/rust-2018/)
- [Rust 2018 Roadmap RFC is open](https://github.com/rust-lang/rfcs/pull/2314)
- cargo (nightly) gained an offline mode `-Z offline`

**Comment by killercup** [comment]
Some notes:

- this is the Wednesday right after FOSDEM
  - @killercup and @mre will give talks at rust dev room there
  - we might want to mention the event in the invite Mail for people who spontaneously want to attend :)
- Kai ~~might want to~~ should talk about his Raspberry-Ambilight project!
- Rust 2018 roadmap RFC might still be open

**Comment by killercup** [comment]
Hey @Rustaceans/organizers-cologne! We should send out an invite this week!

Do you want to proceed with he default template and the default date?

**Comment by Florob** [comment]
I think it's going to be the default template/date for next month.
I'll try to get us a speaker for March though, I'd hate if we never did anything different.

**Comment by killercup** [comment]
Sounds good! We can mention a FOSDEM recap, I'd be happy to give a short
summary of the Rust-specific talks.

Want to send out the invite? (I won't have time to do so before tonight and
I expect more people to read it if we send it in the afternoon.)

Florob <notifications@github.com> schrieb am Mi. 24. Jan. 2018 um 09:31:

**Comment by Florob** [comment]
I can try to wrap my head around the meetup interface during lunch.
Did we send the Save the Date? I.e. is this a proper announcement, or an update?

**Comment by Florob** [comment]
Website and Twitter are done.
Meetup may be done. I did "announce" the meetup, but didn't get a mail. That may be by design though.

**Comment by killercup** [comment]
Great! Just got an email announcing the meetup.


Florob <notifications@github.com> schrieb am Mi. 24. Jan. 2018 um 14:08:

**Comment by mre** [comment]
https://play.rust-lang.org/?gist=03d2af4ad747adf197bc17fa5fe7f547&version=stable

**Comment by m0ppers** [comment]
https://stackoverflow.com/questions/47529643/how-to-return-a-string-or-similar-from-rust-in-webassembly

**Comment by mre** [comment]
Sorry for the spam. We abused this issue for link-sharing during the meetup yesterday. 😉

**Comment by killercup** [comment]
That's a totally valid use for this ticket :) Hope you had fun!
