### ISSUE TITLE
March 2018

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#48]
# ToDo

- [x] Settle for a date and location: **Monday 2018-03-12, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline ~~**2018-02-21**~~ yesterday)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyxfbkb/)
  - [x] [website](http://rust.cologne/2018/03/12/what-are-you-plotting.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/968887452197941248)
  - [x] [community calendar]
  - [x] [reddit](https://www.reddit.com/r/rust/comments/81454s/next_rust_cologne_meetup_is_on_march_12_with/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/next-meetup-in-cologne-on-march-12-2018-audio-analysis-and-cpu-caches/15922)
  - [x] [rustplatz](https://forum.rustplatz.de/t/koeln-naechstes-meetup-am-12-maerz-2018-mit-talks-zu-audio-analysis-und-cpu-caches/212)
- [x] Add @Florob's recording

# Invitation draft

```markdown
Title: CGN 027: Is that a spectrum, or memory access timings?

Dear Rustaceans,

our next Meetup will be on **Monday 2018-03-12, 19:15 CET** at the C4. Yes, a Monday!

We'll have two short talks for you, followed by the usual open discussion and mingling.

Agenda:

* Rust Audio analysis - A lightning talk about a personal project for analyzing audio files

  Rust can be used in many ways. One area is for working with audio data.
  I always wanted a real-time tool to analyze the sound spectrum in front of my apartment door.
  In particular, I'm interested in the number of car honks throughout the day and its distribution.
  So I read an audio stream, split it into small chunks, and run a Fourier analysis on it.
  My assumption is, that you can see a higher amplitude in a certain band of frequencies when a car honk occurs.
  Let's see how it turns out.

* Caches and You

  One of the great things about Rust is that it gives you a lot of control if you need it.
  Amongst other things it gives you control over memory. How big is your data structure really, and where should it be allocated.
  This talk will look at caching in modern CPUs in conjunction with Rust data types and data structures.
  We will see how efficient code can be written to best utilize the cache. 

**[You can register here](https://www.meetup.com/RustCologne/events/vnwndpyxfbkb/)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Rust News

- [Rust 1.24](https://github.com/rust-lang/rust/blob/d3ae9a9e08edf12de0ed82af57ba2a56c26496ea/RELEASES.md#version-1240-2018-02-15)
- [Rust 2018 Roadmap](https://github.com/rust-lang/rfcs/blob/master/text/2314-roadmap-2018.md)
- Working groups started!
  - CLI Survey! [bit.ly/rust-cli-survey](http://bit.ly/rust-cli-survey)
- CFPs! [RustFest](https://cfp.rustfest.eu/events/rustfest-paris) & [RustConf](https://cfp.rustconf.com)

**Comment by killercup** [comment]
Opened with default date. I have another thing on March 7 and may only be able to join the meetup around 20.30 or later.

**Comment by killercup** [comment]
FYI we are currently aiming for March 12 (2nd Monday in March), hoping we can get a bit of a program together and also see the "can't do Wednesdays" crowd again :)

**Comment by mre** [comment]
I guess I could do a presentation if you like.  

Have some stuff in the queue that I wanted to try/practice:
* Rust Ergonomics - How Rust has changed in 2017
* Rust Audio analysis - A lightning talk about a personal project for analyzing audio files.

Would that be of interested?

**Comment by Florob** [comment]
@mre That'd be great. I'm going to put an announcement together over lunch. I'll be doing a short talk about the importance of caches.
Can you write up a small abstract for your talk? Either is fine. Personally I'm more curious about audio analysis, but I have a hunch most people would benefit more from the Rust Ergonomics talk.

**Comment by mre** [comment]
Audio it is!
Here's the abstract:

Rust can be used in many ways. One area is for working with audio data. I always wanted a real-time tool to analyze the sound spectrum in front of my apartment door. In particular, I'm interested in the number of car honks throughout the day and its distribution. So I read an audio stream, split it into small chunks, and run a Fourier analysis on it. My assumption is, that you can see a higher amplitude in a certain band of frequencies when a car honk occurs. Let's see how it turns out.

**Comment by Florob** [comment]
@mre Thanks a bunch.

@Rustaceans/organizers-cologne The invitation draft is in the issue description. Improvements and corrections very welcome. I'll publish the invitation in the evening if no one beats me to it.

**Comment by killercup** [comment]
Invite text sounds good! I've added the event number (instead of `###`) and indented the text in the bullet points. I'll send out the invite in a minute.

**Update:** Invite sent and meetup announced on Meetup.com.

**Comment by killercup** [comment]
@badboy, can you add this event to the community event calendar?

(What's the deal with that calendar right now anyway? The last mail I got on the topic was from you saying (and I quote), "Will take care of that […]" ;))

**Comment by badboy** [comment]
:O did I not do it? taking care of it right now!

**Comment by badboy** [comment]
Took care of it, killercup got access and will add the new event

**Comment by Florob** [comment]
Usual question when we have talks: Do we want to record them? Always a bit of a different atmosphere in terms of speaker positioning/getting people to ask questions via mic.
I still think it's nice for the community at large.
@mre You proposed yours as a trial/practice run. How do you feel about recordings?

**Comment by killercup** [comment]
Thanks for thinking of asking this -- I would've totally forgotten about it.

Re Q&A: I'm totally fine with not having an "official" Q&A after the talks. People can go to the speaker after the talk and discuss stuff (and they'll do that anyway -- not everyone wants to have their question recorded). Downside is of course that potentially cool stuff will be missing in the video.

But I'm not giving a talk tomorrow. Do what feels right to you.

**Comment by mre** [comment]
@Florob the tiny bits I have to show are probably not worth recording. 😅

**Comment by mre** [comment]
So we ended up not recording my part yesterday, and I think that's okay. In the end it was more of a little hacking session than a talk.
That said, there was still an outcome! And that's a pull request to the project I'm using. You can find it [here](https://github.com/IGI-111/ghastly/pull/1). Apart from the things we found during the meetup, I also dug up a few more gems using clippy. Thanks everyone and enjoy!

**Comment by killercup** [comment]
Video now available: https://media.ccc.de/v/rustcologne.2018.03.caches-and-you

Let's close this issue and move towards the April event!

**Comment by badboy** [comment]
I also uploaded it to our YouTube channel and I am now waiting for the final processing before I hit the publish button.

**Comment by badboy** [comment]
And it's up: https://www.youtube.com/watch?v=GQBI-TcOTOk

**Comment by Florob** [comment]
@badboy Thank you! It's nice having this up on the Rust YouTube too. Would you mind making sure the license field is set to creative commons?

**Comment by badboy** [comment]
@Florob Oops, my mistake. Will adjust it.
