### ISSUE TITLE
April 2018

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#50]
# ToDo

- [x] Settle for a date and location: **Wednesday 2018-04-04, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2018-03-23**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyxgbgb/)
  - [x] [website](http://rust.cologne/2018/04/04/open-space.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/977151820354277377)
  - [x] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]
  - [ ] [rustplatz]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday 2018-04-04, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Rust News

- [Rust 1.25](https://blog.rust-lang.org/2018/03/29/Rust-1.25.html)
  - nested import groups `use std::{fs::File, io::Read, path::{Path, PathBuf}}`
  - docs now use CommonMark
  - `#[repr(align(16))]` for structs (cf. discussions at last meetup)
  - `cargo new` now generates binaries by default
  - `|` now allowed at the start of a match arm (so you'll never find the starts of your arms again ☹)
  - `-C lto=thin`, i.e. ThinLTO
- Rust All Hands in Berlin was the week before
- Rust's Reach was announced

**Comment by killercup** [comment]
Thanks all for coming!
