### ISSUE TITLE
May 2018

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#51]
# ToDo

- [x] Settle for a date and location: **Wednesday 2018-05-02, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2018-04-20**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyxhbdb/)
  - [x] [website](http://rust.cologne/2018/05/02/constrained-solving.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/988533784151814144)
  - [x] [community calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=MTNhZTJkNm9lMWhvOG84ODA4YjVmMjNmZDggYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/8etnl9/rustcologne_meetup_on_may_2_constrained_solving/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/rustcologne-meetup-on-2018-05-02-constrained-solving/17069)
  - [ ] [rustplatz]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next Meetup will be on **Wednesday 2018-05-02, 19:15 CET**.

This time around we've decided to test something new.
We'll try to solve a set of beginner level tasks, under different constraints:
write it in a functional style, get the shortest source code possible, make it as simple or convoluted as possible, and whatever else comes to mind.
The intend is that under these constraints we'll learn about new language features and library functions, from each other, as well as the documentation.

Depending on participation and experience we'll solve the tasks as one large group, or split up into smaller ones.
So don't be afraid to drop by even if your very new to Rust. However, if you're already fairly experienced, there may still be something new to learn.

**[You can register here](https://www.meetup.com/RustCologne/events/vnwndpyxhbdb/)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Rust News

- Accepted RFCs
  - [Allow access to enum variants through type alias](https://github.com/rust-lang/rfcs/pull/2338)
  - [Unnamed struct/union fields (FFI)](https://github.com/rust-lang/rfcs/pull/2102)
- Unapproved RFCs: Placement arrow
- [std_unicode merged into core](https://github.com/rust-lang/rust/pull/49698)
- [wasm-pack](https://hacks.mozilla.org/2018/04/hello-wasm-pack/)
- [Regexp 1.0](https://github.com/rust-lang/regex/releases/tag/1.0.0)
- [Networking WG](https://internals.rust-lang.org/t/announcing-the-network-services-working-group-wg-net/7354)

**Comment by Florob** [comment]
So, we are drawing close to our announcement deadline again.
I'm under the impression that we usually have many people relatively new to Rust. I was thinking something that might be interesting for newcomers as well as somewhat experienced people might be to do some coding challenges. I.e. solve some simple tasks under various constraints: Fastest program on system XY, code golf, most functional (as in programming, not as in working), easiest/hardest to understand.
The premise for this is that these constraints and reviewing code together would showcase various language features or library functions people might not have been aware of.
There are (depending on how confident people feel) various versions of doing this:
* as a large group
* split up in two groups (we should be able to get two rooms/projectors if we need them)
* small groups
* everyone by himself

Does this sound like a good idea, or is that e.g. to competitive?
I'm happy to come up with some tasks, though from experience things I come up with tend to be a bit on the math-heavy side.

**Comment by killercup** [comment]
Sounds like a cool idea to me, @Florob! I'd like to frame this in a non-competitive way, though, because we tend to have people completely new to Rust.

(Also just cc'd you on an email that may be relevant to some future meetups)

**Comment by Florob** [comment]
I've updated the ticket with a proposed Invitation. Proof reading and suggestions welcome.
I'd like to announce the meetup this evening, since we're already running a bit late.

**Comment by killercup** [comment]
Thanks! I was going to do something similar this evening :)

This reads pretty well! We can send it out like this, id you want.

One thing, though: Do you want to tease a bit what these "beginner level tasks" can be or do you want to give us another week to come up with something cool? In the latter case, we might also ask the community to drop by on this tracking issue with suggestions of their own.

**Comment by mre** [comment]
Hey I just heard beginner level tasks, and that's why I chime in here. 😉 

My [repo for simple coding tasks](https://github.com/mre/the-coding-interview) might come in handy. It's specifically *not* about coding puzzles, but about approachable tasks targeted at beginners.
There are still a lot of tasks left, which don't have a Rust solution, so it might be a good fit. What's also nice about it is, that there are solutions in other languages like Python, Go, or Javascript so everybody should feel right at home.

I'm biased of course, since it's my project so feel free to use something else. No hard feelings. 😀

**Comment by Florob** [comment]
I wouldn't really want to tease tasks yet, because I have not really come up with anything.
@mre's repo looks nice, from quickly scrolling through it.
I'm not opposed to inviting people here to suggest tasks either, OTOH they can always do that at the event too, of course.

**Comment by mre** [comment]
True. Maybe we should simply see how people team up during the event and keep my repo as a plan B in case we need some inspiration.

**Comment by TheRustyStorm** [comment]
https://play.rust-lang.org/?gist=2744095dbcf13a0577ce1c29a38d76ae&version=stable&mode=debug

The solution with "some" memory needed

**Comment by Florob** [comment]
https://play.rust-lang.org/?gist=7669d2108f715c30547e786c0100e786&version=stable&mode=debug

"Readable" solution.

**Comment by zgtm** [comment]
https://play.rust-lang.org/?gist=fde33f8e77e12b5ed6185defecfbe1cb&version=stable&mode=debug

The solution with the custom iterator

**Comment by killercup** [comment]
Thanks for the great meetup, folks! Hope to see you all again next month :)
