### ISSUE TITLE
June 2018

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#54]
# ToDo

- [x] Settle for a date and location: **2018-06-27, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2018-05-25**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyxjbjb/)
  - [x] [website](http://rust.cologne/2018/06/27/thoughtworks.html)
  - [x] [twitter]
  - [x] [community calendar]
  - [x] [reddit]
  - [ ] [rust-lang forum]
  - [ ] [rustplatz]

# Invitation draft

```markdown
Title: RustCologne: Save The Date

Dear Rustaceans,

Our next Meetup will be on **2018-06-27, 19:15 CET**. We are very happy to be
invited to a new location: The meetup will be at ThoughtWorks office in Cologne
(Lichtstraße 43i -- just 400m from the C4).

In addition to the new location, we're also quite excited to have two talks
prepared for you! the first one, by Sebastian Thiel is an introduction to "Share
Secrets Safely", and present a tool to share secrets within teams to avoid
plain-text secrets. In the second talk, Niko Hellwig will talk about "HUB", a
central entry point to your current project.

**[You can register here](https://www.meetup.com/RustCologne/events/vnwndpyxjbjb/)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian

- - -

The meetup will likely be held in German, we will however reevaluate this at the
beginning of the evening and may switch to English if needed.
```

# Rust News

- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
  - 1.26.0 and 1.26.1 with LOTS of awesome stuff 
  - ~~yes and it's gonna be great~~
  - rustfix/edition preview ~~hopefully~~

**Comment by ghost** [comment]
Here is a possible item for the agenda:

* **Title**
  * An introduction to 'Share Secrets Safely'
* **Summary**
  * 'Share Secrets Safely' scratches a particular itch as it provides the tooling required to use GPG in teams with great user experience, while providing all tooling necessary to introduce said shared secrets into their final destination without them ever touching disk. I will particularly highlight the way the project is structured, and tested, showing that 'journey' level testing is now affordable thanks to Rust.

**Comment by killercup** [comment]
Thanks all for coming! Looking forward to more events at the ThoughtWorks office!
