### ISSUE TITLE
July 2018 event

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#58]
# ToDo

- [X] Settle for a date and location: **Wednesday 2018-07-04, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2018-06-28**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyxkbgb/)
  - [x] [website](http://rust.cologne/2018/07/04/open-space.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1012296819781578752)
  - [x] [community calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjVxamg3amxpYjJjanFvc2E3OXJmNWc2c2UgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/8uitp6/rust_cologne_june_open_space_and_lightning_talks/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/cologne-germany-open-space-on-2018-07-04/18378)
  - [ ] ~~[rustplatz]~~

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday 2018-07-04, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](https://www.meetup.com/RustCologne/events/vnwndpyxkbgb/)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Agenda

- [Dresden meetup live](https://twitter.com/rustdresden/status/1014424184880009216)
- Intros
- Rust News
  - [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
  - 2018 preview
- Open Space
  - hyperjson

**Comment by killercup** [comment]
@Florob – let's send out an invite today!

**Comment by Florob** [comment]
@killercup Definitely, I feel like we agreed on that yesterday. Anything I can/need to do? I'm a bit busy today. Recording/streaming yet another talk after work.

**Comment by mre** [comment]
One sec, is it still encouraged to suggest talks?

Maybe anybody would like to show their current projects and gather feedback? We had some really nice conversations yesterday about people's Rust projects (e.g. Rust for Audio using WebAssembly).

Personally, I'd love to do a lightning-talk about [hyperjson](https://github.com/mre/hyperjson). Any interest? 😃

**Comment by killercup** [comment]
@mre, of course! We got some feedback from people that they'd really like to come to the regularly scheduled meetup next week (which we thought of skipping because it's so close to yesterday's), so we wanted to go with the default settings to get this out quickly.

Should we announce this as a "bring your own project" meetup or is this still "We have a talk and after that an Open Space"?

@Florob what do you think? (I can do all the managing)

Oh, almost forgot, [here's](https://i.pinimg.com/originals/dc/c4/1a/dcc41a308cf1a1e178f513a347d83c83.jpg) a shitty drive-by 90s techno pun just for you, Matthias!

**Comment by Florob** [comment]
I feel like "Bring your own project" might actually deter people, It would be better if we had multiple people that wanted to show their project and could frame this as "you can also present yours".
I think this also fits reasonably well into an Open Space. People have regularly given quick overviews of their projects in those. The timing being what it is, I think I'd prefer that approach.

**Comment by mre** [comment]
Oh! It's already next week. 😅 Then I suggest to keep the current open-space agenda and I can optionally do a quick talk if I can make it to the meetup (have to reschedule some stuff)? Would go nicely with the open-space setup, because we can talk about profiling Rust code and tricks to make it faster.

**Comment by killercup** [comment]
Sounds good.

Website, Meetup, Twitter, calendar updated.

@mre, do you have a few minutes and want to post links to this invite _everywhere_? Feel free to add a teaser about whatever you want to talk about!

**Comment by mre** [comment]
Sure! One sec.

**Comment by mre** [comment]
Announcements:
* [Reddit](https://www.reddit.com/r/rust/comments/8uitp6/rust_cologne_june_open_space_and_lightning_talks/)
* [Rust-lang forum](https://users.rust-lang.org/t/cologne-germany-open-space-on-2018-07-04/18378)
* forum.rustplatz.de seems to be down (?), so no announcement there.

**Comment by killercup** [comment]
For some reason we started designing t-shirts instead of Rust APIs…

- https://www.seedshirt.de/rust-cologne-boring-grey
- https://www.seedshirt.de/rust-cologne-grey-with-orange
