### ISSUE TITLE
August 2018 event

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#59]
# ToDo

- [x] Settle for a date and location: **Wednesday 2018-08-01, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2018-07-16**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyxlbcb/)
  - [x] [website](http://rust.cologne/2018/08/01/open-hyperspace.html)
  - [x] [twitter](
https://twitter.com/RustCologne/status/1022855591717490688)
  - [x] [community calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=MTl2NjZnZWJoNWhnYjlzZ3I3ZG05dGhvdDEgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/92e4pe/rust_cologne_august_1st_2018_open_hyperspace/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/rust-cologne-august-1st-2018-open-hyperspace/19144)

# Location

- Default: C4
- asked ThoughtWorks -> will go there next month (cf. #60)
- @uwearzt wanted to see if his office was available

# Invitation draft

(default)

```markdown
Title: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday 2018-08-01, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](https://www.meetup.com/RustCologne/events/vnwndpyxlbcb/)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Rust News

- [Rust 1.27.1](https://blog.rust-lang.org/2018/07/10/Rust-1.27.1.html): `match` borrowck fix + rustdoc security fix
- [Rust 1.27.2](https://blog.rust-lang.org/2018/07/20/Rust-1.27.2.html): `match` borrowck bugfix for a bug introduced with the 1.27.1 bugfix
- [clippy as rustup component](https://internals.rust-lang.org/t/clippy-is-available-as-a-rustup-component/7967)
- [State of Rust](https://forge.rust-lang.org/state-of-rust.html)
- [Rust 2018 Preview](https://internals.rust-lang.org/t/rust-2018-an-early-preview)
- [cargo fix upstream](https://github.com/rust-lang/cargo/pull/5723)

# Agenda

- possible talks
  - @mre wanted to talk about hyperjson in July but didn't get around to it

**Comment by killercup** [comment]
@Florob are we good to go with next Wednesday at the C4?

@mre want to talk about hyperjson or wait until #60?

**Comment by Florob** [comment]
It's the first Wednesday in the month, so we're good ;)

**Comment by mre** [comment]
Yup, would talk about hyperjson. 👍 Thanks for the reminder.

**Comment by killercup** [comment]
Alright, perfect!

@mre do you have an abstract we can put up? Otherwise I'll make one up and I can't promise I won't call it [hydrojson](https://i.ytimg.com/vi/QDUs-J51QEQ/maxresdefault.jpg)!

**Comment by mre** [comment]
How about this?

During a recent Python Hackathon in Düsseldorf, Matthias somehow managed to sneak in some Rust code while writing a fast, safe Python module for encoding and decoding JSON. It passes (most of) the Python test suite for the `json` module and was unreasonably pleasant to write. Listen carefully as he tells the story of a little side-project that got out of hand and how Rust can help speed up even the most boring, highly-optimized tasks like parsing file formats in the future.

**Comment by FichteFoll** [comment]
Sounds interesting, but I don't think I can make it. Will it be recorded?

**Comment by mre** [comment]
Only @Florob knows. Our faith is in his hands.

**Comment by Florob** [comment]
@mre I'll record if you let me :stuck_out_tongue:

**Comment by mre** [comment]
🌞 yup, let's do this.

**Comment by killercup** [comment]
Website is a go, will update meetup and announce event there, then post to twitter

*Edit:* Oh, I think the meetup is already announced? Well then, onwards to twitter.

**Comment by killercup** [comment]
If anyone wants magic internet points from reddit or the user forums, now is your chance to get them by posting a link to http://rust.cologne/2018/08/01/open-hyperspace.html :)

**Comment by mre** [comment]
We should start using [submit](https://github.com/hello-rust/submit) for the announcements.
Thinking about renaming the tool to "hello" for additional amusement.

**Comment by mre** [comment]
I actually submitted the link with `hello` (formerly `submit`):
https://www.reddit.com/r/rust/comments/92e4pe/rust_cologne_august_1st_2018_open_hyperspace/
Will take care of the forum now, but manually as `hello` can not do it (discourse only allows admins to create API tokens 😢)

**Comment by mre** [comment]
Link to forum: https://users.rust-lang.org/t/rust-cologne-august-1st-2018-open-hyperspace/19144

**Comment by mre** [comment]
Usage for future reference:

```
cargo install hello
hello reddit /r/rust "Rust Cologne, August 1st 2018: Open Hyperspace" http://rust.cologne/2018/08/01/open-hyperspace.html
```

**Comment by killercup** [comment]
Thanks all for coming!

Also thanks to Neal for that spontaneous talk on sequoia! You can read more about it here: https://www.reddit.com/r/rust/comments/93mng5/ann_sequoia_a_new_openpgp_implementation/

**Comment by Florob** [comment]
@FichteFoll @mre  Recording is available at https://media.ccc.de/v/rustcologne.2018.08.hyperjson

**Comment by mre** [comment]
This guy is fast. Thanks @Florob!

**Comment by killercup** [comment]
@mre I you push your slides somewhere I'd link them from the event page :) (or, just make a PR to this repo)

**Comment by mre** [comment]
Sure! https://speakerdeck.com/mre/hyperjson-the-journey-towards-faster-safer-json-parsing-in-python-using-rust
