### ISSUE TITLE
September 2018 Event

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#60]
# ToDo

- [x] Settle for a date and location: **Wednesday 2018-09-05, 19:15 CET** at ThoughtWorks (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2018-08-24**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyxmbhb/)
  - [x] [website](http://rust.cologne/2018/09/05/fun-traits.html)
  - [x] [twitter](
https://twitter.com/RustCologne/status/1034444878569197569)
  - [x] [community calendar]
  - [x] [reddit](
https://www.reddit.com/r/rust/comments/9b7zzn/rust_cologne_sept_5th_2018_fun_traits/)
  - [x] [rust-lang forum](
https://users.rust-lang.org/t/rust-cologne-sept-5th-2018-fun-traits/19945)
  - ~~[ ] rustplatz~~

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next Meetup will be on **Wednesday 2018-09-05, 19:15 CET** at the ThoughtWorks office Cologne.

The theme of the evening is traits. First, there will be a talk about traits in general and how to use them to make your code generic and composable. The second talk will present the Fn-traits in detail, and explain how you can properly accept functions and closures as function parameters, as well as give an overview about which closures implement which traits.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Location

- ThoughtWorks
  - with pizza!

# Rust News

- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
- Events
  - FrOSCon: Stickers and postcards still available!
  - RustFest Rome: Sat, November 24 + Sun, November 25

**Comment by killercup** [comment]
After talking with Tina, we can host this event at ThoughtWorks.

**Comment by killercup** [comment]
Does anyone want to do something that is not _Open Space_? :)

We should send out an announcement early next week.

**Comment by Florob** [comment]
I've been thinking I'd eventually like to do a talk on the `Fn*` family of traits. I.e. how to properly accept functions and closures as function parameters, and which closures implement what.
Ideally that wouldn't be the only thing on a meetup agenda though. Does anyone feel like doing e.g. a general quick intro to traits?

**Comment by killercup** [comment]
@Florob that sounds like an awesome talk! Having both a talk about traits and then Fn traits (and I assume also an intro to how closures work/are constructed?) might be a bit much for newcomers, though. Doesn't mean we shouldn't do it, but we should announce it as a "intermediate level rust" event, then.

(I have a "generic return type inference" talk I'd like to write at some point but it's not ready yet.)

**Comment by killercup** [comment]
Opened #64 with agenda from above.

@Florob can we try and send out the invite today?

**Comment by Florob** [comment]
Yes please.

**Comment by killercup** [comment]
Updated website and a bunch of stuff, but need to go now. @mre, does your hello script still work? :)

**Comment by mre** [comment]
It should. 😅 Any platform I should run it on? Or do you want to give it a shot and open issues for bugs? 😉

**Comment by mre** [comment]
(Yakshave: Would be fancy to add it to this repo as a release bot, similar to `bors`.)

**Comment by killercup** [comment]
@mre, well there are some unticked boxes in the issue description…

**Comment by killercup** [comment]
@mre I actually just wanted to ask yesterday if you'd like to (automatically) post this to reddit and the forums (for free internet points). Otherwise I'll do it tonight.

**Comment by mre** [comment]
Busy times, sorry. 😆 
Posted on reddit with the following command:
```
hello reddit /r/rust "Rust Cologne, Sept 5th 2018: Fun traits" http://rust.cologne/2018/09/05/fun-traits.html
```

**Comment by mre** [comment]
Discourse support is WIP (https://github.com/hello-rust/hello/pull/7), so I will submit it manually.

**Comment by mre** [comment]
Forum: https://users.rust-lang.org/t/rust-cologne-sept-5th-2018-fun-traits/19945

**Comment by mre** [comment]
rustplatz forum is offline? Only the [main website](rustplatz.de) seems to be active, but I can't find out how to post anything there...

**Comment by badboy** [comment]
@mre Yes, the rustplatz forum doesn't exist anymore. The main site doesn't really have any news section. So there's nothing to do.

**Comment by mre** [comment]
Ah okay, that explains. Thanks for the info and the [funny PR](#65). 😆

**Comment by killercup** [comment]
@Florob do you plan on recording the talks tomorrow? If so, do you need help to get the equipment from the C4 to ThoughtWorks? I can probably get to the C4 around 18:45

**Comment by Florob** [comment]
@killercup I was, yes. Some help carrying the equipment would be appreciated.

**Comment by killercup** [comment]
Added a bunch of signs [here](https://github.com/Rustaceans/rust-cologne/tree/5ff8ac8cfe8ee7f3cd60d9bc7d4fc851355301d3/meetup-orga) and printed two of each.

**Comment by killercup** [comment]
Great meetup! Let's close this issue once the recordings are online.
