### ISSUE TITLE
October 2018 Event 

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#63]
# ToDo

- [x] Settle for a date and location: **Wednesday 2018-10-10, 19:15 CET** at *Cisco Office Cologne*
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **???**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyxnbfb/)
  - [x] [website](https://rust.cologne/2018/10/10/at-cisco.html)
  - twitter
    - [x] [announce location](https://twitter.com/RustCologne/status/1048170241333886976)
    - [x] announce talk
  - [x] [community calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NGg0NXVkMjE0Y2ZpZ3Zja2NoMmtyZWNkOWUgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/9lljok/rust_cologne_oct_10th_2018_wayland_compositors/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/cologne-germany-open-space-on-2018-10-10/21014)

**Note:** This time, @uwearzt will organize the location

# Invitation draft

```markdown
Title: Rust Cologne: At Cisco

This time around, we are happy to invite you to new location:
The Cisco office Cologne, near Heumarkt.

## Agenda

We'll start the evening with a quick introduction round (if you have a good idea
to make this more interesting please talk to the organizers at the beginning
of the event.)

Then, Dorota will talk about Wayland, the display server (protocol) for Linux
desktops, and how to use Rust to write compositors and clients for it.

Afterwards, it's all up to you: Have an interesting piece of code you want to
discuss? Want some help fighting the borrow checker? You are very welcome to
stay, enjoy some drinks, meet nice people, and discuss all things Rust!

We are looking forward to seeing you. :-)

[**You can register here**.](https://www.meetup.com/RustCologne/events/vnwndpyxnbfb/)

- - -

The meetup will be held in English.

Your help is welcome: We are always looking for talks - just send us your idea! :-)
```

# Rust News

- releases
  - [ripgrep 0.10.0](https://github.com/BurntSushi/ripgrep/releases/tag/0.10.0)
    - libripgrep
    - PCRE2 support
    - multiline search
  - [Rust 1.29}(https://blog.rust-lang.org/2018/09/13/Rust-1.29.html)
    - `cargo fix`/`rustfix`
    - `cargo clippy`
    - `cargo doc --document-private-items`
    - `Iterator::flatten` is stable
    - `&str` and `OsString` have become comparable
  - [Rust 1.29.1](https://blog.rust-lang.org/2018/09/25/Rust-1.29.1.html)
    - Fixes a buffer overflow in `str::repeat`
  - [wasm-pack 0.5](https://rustwasm.github.io/2018/09/24/the-biggest-wasm-pack-release-yet.html)
    - incremental `wasm-pack build`
    - `wasm-pack test` to run tests with node.js or in headless browser
- media
  - [RustConf 2018 Videos](https://www.youtube.com/playlist?list=PL85XCvVPmGQi3tivxDDF1hrT9qr5hdMBZ)
  - Recordings from last meetup
    - [A generalist's view of traits](https://media.ccc.de/v/rustcologne.2018.09.generalists-view-traits)
    - [Fn traits](https://media.ccc.de/v/rustcologne.2018.09.fn-traits)
    - We also always publish to [YouTube](https://www.youtube.com/watch?v=bvJCMhJ3RnQ&list=PL85XCvVPmGQjMUncbxYjzS60zUSWoITrx) now 
- language
  - [`|` in irrefutable for-loop patterns](https://github.com/rust-lang/rfcs/pull/2530)

**Comment by uwearzt** [comment]
Because 2018-10-03 is public Holiday in Germany (Tag der Deutschen Einheit), the Meeting will be held 2018-10-10 at the 

Cisco Office Cologne
Grosse Sandkaul 2
50667 Cologne

https://www.google.de/maps/place/Große+Sandkaul+2,+50667+Köln
https://www.openstreetmap.org/search?query=grosse%20sandkaul%202%20k%C3%B6ln#map=19/50.93594/6.95709

Entrance: https://www.google.de/maps/@50.9358524,6.9569525,3a,75y,63.55h,87.81t/data=!3m6!1e1!3m4!1s7UDLvg6MOL23YR80ggcusw!2e0!7i13312!8i6656

Directions:

From Cologne Main Station:
https://www.google.de/maps/dir/Köln+Hauptbahnhof,+Trankgasse+11,+50667+Köln/Große+Sandkaul+2,+50667+Köln/@50.9400389,6.9537376,16z/am=t/data=!4m14!4m13!1m5!1m1!1s0x47bf25a52b498f99:0x95851446d3a4d890!2m2!1d6.9586017!2d50.9432141!1m5!1m1!1s0x47bf25b1f7514fa9:0x2fbe549a0325579e!2m2!1d6.9574592!2d50.9360583!3e3

from CCC Cologne:
https://www.google.de/maps/dir/Chaos+Computer+Club+Cologne+e.V.,+Heliosstraße+6A,+50825+Köln/Große+Sandkaul+2,+50667+Köln/@50.9452094,6.9167989,14z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x47bf25368b4b1855:0xaf4e14da6578f563!2m2!1d6.9130307!2d50.9504579!1m5!1m1!1s0x47bf25b1f7514fa9:0x2fbe549a0325579e!2m2!1d6.9574592!2d50.9360583!3e3

Website: https://www.cisco.com/c/de_de/index.html

The Office is in the same Building as the Dorint Hotel and the Hard Rock Cafe. The Entrance is on the West side of the building facing Saturn.

**Comment by uwearzt** [comment]
The conference room is equipped with a MX700 Telepresence system: https://www.cisco.com/c/en/us/products/collateral/collaboration-endpoints/telepresence-mx-series/datasheet-c78-731263.html. Both Monitors can be used as presentation screens.

We will have Coffee, cold beverages and some goodies available. Do we need something else?

**Comment by dcz-self** [comment]
I promised to do a talk, so I have 2 ideas I could follow:
- about Rust in the Wayland ecosystem
- about interfacing with C/C++

By default, I prefer to talk about interfacing, since it's easier for me, unless there's interest in Wayland?

**Comment by killercup** [comment]
@dcz-self both sound great! There are some talks and posts about C/C++ interfacing (e.g. @spacekookie's RustConf talk), but I haven't seen much about Rust and Wayland. Also: You don't have decide right now. We can easily put some placeholder in right now to reserve you a spot in the agenda. :)

**Comment by mre** [comment]
Yay @dcz-self. Looking forward to that! 🎉

**Comment by killercup** [comment]
@dcz-self did you settle on a topic? We can also announce the meetup without talks for now and you still decide on the stop, if and what you want to talk about.

**Comment by dcz-self** [comment]
@killercup I decided to go with your recommendation - sorry that I didn't say it explicitly. If you need a title, let's make it "Wayland + Rust"

**Comment by killercup** [comment]
Awesome! Can you give me a bit more info so it looks good on the website? I think we have title, your name, abstract (just a sentence is fine), and some links to where people can find you, and slides/videos (can be added later of course)

**Comment by dcz-self** [comment]
I'm probably going to deal with slides over the weekend.

I'll take some time to explain what is Wayland and why it's here to stay. Then, I'll give a high level overview of the state of Rust on Wayland: how to write servers and clients, and how far along we can get with Rust. I want to focus on [Smithay projects](https://github.com/Smithay/), and [wlroots-rs](https://github.com/swaywm/wlroots-rs).

People can find me on GitHub, and as *dcz* on IRC, as well as hanging out at my work [Matrix channel](https://matrix.to/#/#community-general:talk.puri.sm), which is open to all.

**Comment by killercup** [comment]
@dcz-self perfect! I've added it to #67. I hope to announce the meetup this evening.

As you might have seen, we are not at the C4 next week, but at Cisco near Heumarkt. Do you want to have your talk recorded? (If so, we might need to bring some equipment over.)

**Comment by dcz-self** [comment]
Yup, I'll grab the addess from the meetup announcement.

I don't care much about recording, I'll be happy if it doesn't end up being a total disaster ;)

**Comment by dcz-self** [comment]
Oh btw, credit me as Dorota.

**Comment by killercup** [comment]
Published website, updated meetup.com event description, and wrote a tweet.

@mre, since you did such an amazing job posting to the forums and reddit last time, want to do the honors again? :)

**Comment by mre** [comment]
Aye, can do.

**Comment by mre** [comment]
* [Reddit](https://www.reddit.com/r/rust/comments/9lljok/rust_cologne_oct_10th_2018_wayland_compositors/)
* [Forum](https://users.rust-lang.org/t/cologne-germany-open-space-on-2018-10-10/21014)

**Comment by killercup** [comment]
@dcz-self Someone on reddit [asked](https://www.reddit.com/r/rust/comments/9lljok/rust_cologne_oct_10th_2018_wayland_compositors/e84dfay/?context=3) for your slides. Do you want to post them anywhere? (Can be in this repo, just make a PR, we have a few already.)

@uwearzt @Florob what ever happend to that recording?

**Comment by dcz-self** [comment]
I figured this will be easier:

[presentation.zip](https://github.com/Rustaceans/rust-cologne/files/2507004/presentation.zip)

**Comment by mre** [comment]
I like to host mine on [speakerdeck](https://speakerdeck.com/). [Example here.](https://speakerdeck.com/mre)

**Comment by uwearzt** [comment]
Hi, sorry for the delay, here is the video:
https://www.dropbox.com/sh/wwrrpeppbjdaa57/AACHRP7oM_UwXakeqTigVODua?dl=0

Next time, we will also be able to record the speaker camera on our Video Conferencing system (and be much quicker with the Video). 

@Florob i guess you need to trim at both ends :)

**Comment by killercup** [comment]
Video is live at https://www.youtube.com/watch?v=oX5yVyLbLZE and link on the website!
