### ISSUE TITLE
November 2018 Event

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#68]
# ToDo

- [x] Settle for a date and location
  - default: **Wednesday 2018-11-07, 19:15 CET** at **C4** (first Wednesday of November)
  - alternatives: Cisco, ThoughtWorks
- [ ] ~~Send "Save the Date" info (with link to this ticket)~~
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2018-10-24**)
  - [x] [meetup](https://www.meetup.com/de-DE/RustCologne/events/vnwndpyxpbkb/)
  - [x] [website](https://rust.cologne/2018/11/07/freebsd-and-networking.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1054762475806171137)
  - [x] [community calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=N25rMHViZTN1MnAwNGZzOGNpbGtpMTByYXAgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/9qq0zi/rusty_freebsd_and_networking/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/cologne-germany-rusty-freebsd-and-networking-on-2018-11-07/21554)

# Invitation draft

```markdown
Title: Rust Cologne: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday 2018-11-07, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](https://www.meetup.com/de-DE/RustCologne/events/vnwndpyxpbkb/)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Rust News

- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
- Events
  - RustFest
  - RustRush

**Comment by killercup** [comment]
Maybe it's time to do a "Rust 2018" event? Otherwise we can do this in December right around the time of the actual release.

**Comment by pizzamig** [comment]
Because Matthias is always pushing me to do a talk about something, I'd offer 2 possible topics:
* my crate structopt-flags: a small presentation and code review + examples + discussion + ideas about its limitations
* Rust on FreeBSD: it would be more a talk about the how to create a package of a tool written in Rust on FreeBSD
@killercup if you prefer to do a Rust 2018 event in November, I can postpone my talk to the next event, I'm not in hurry

**Comment by killercup** [comment]
@pizzamig sounds great! I'm not married to the idea of doing a Rust 2018 event. I'd actually prefer it if we had some talks about stuff that is not what everyone else will be talking about anyway :) @Florob, what do you think?

- I've seen your structop-flags crate but just realized I've never talked to you about it, as there are some similar crates (by Yoshua) at https://github.com/rust-clique (IIRC they are called `clap-verbosity-*` because clap 3 will support stuctopt style).
- Personally, I'm very interested in FreeBSD support, too. Maybe also in regard to library support and common issues (I think I managed to build https://github.com/killercup/bitrust for FreeBSD but it was quite a hassle to get the crate wrapping libgit2 to compile).

Let me know what you think.

**Comment by gnunicorn** [comment]
> Wednesday 2018-11-07, 19:15 CET at C4 (first Wednesday of November)

I'll be around cologne at that time and could offer to give a talk, too. I am working on [substrate](https://github.com/paritytech/substrate), which uses rust and wasm features heavily, running an internal wasm-runtime, which can be live-upgraded through the connected p2p-network. I'd happily talk about how this being achieved and what amazing possibilities rust allows here. Would that be of interest?

**Comment by killercup** [comment]
That sounds very cool! We can't afford to miss that opportunity! :)

@Florob, should we go with the default time + place, then? We probably want to use the C4's recording setup.

(I officially move my "Rust 2018 Meetup" plans to December)

**Comment by Florob** [comment]
Yes, let's go with the default time/place. We don't exactly have anything else lined up anyway, do we?
Some talks in November, and a (celebratory?) Rust 2018 Meetup in December sounds fine.

**Comment by killercup** [comment]
Awesome! Let's try and annouce this, then!

@pizzamig, @gnunicorn can you give me

- a title for your talk,
- the name you want to be credited as,
- the links zu github/twitter that I should add next to your name,
- and a short summary of what you want to talk about?

**Comment by pizzamig** [comment]
so, for my talk, I'd say:
* title: Rust on FreeBSD
* my name is: Luca Pizzamiglio
* github: https://github.com/pizzamig twitter: https://twitter.com/pizzamig
* FreeBSD: what is it? Rust on FreeBSD: state of the art. How to build a FreeBSD package for a Rust project.
I think it will be about 30 minutes long, 40 minutes max.

**Comment by gnunicorn** [comment]
For me that will be:
 - title: WASM in the wild: hot-upgradable runtime in substrate thanks to Rust
 - my name: Benjamin Kampmann 
 - personal github: @gnunicorn, twitter: twitter.com/gnunicornBen, website: gnunicorn.org
 - project github: https://github.com/paritytech/substrate/  , website: https://www.parity.io/substrate/
 - desc: 2018 is the year of WebAssembly.  But did you know, you can do more than "Web" with it? In this talk we'll investigate how wasm allows substrate, the rust blockchain framework that will run [Polkadot](https://polkadot.network), to provide a hot-upgradable, fully configurable blockchain runtime that runs at native speed (most of the time).

**Comment by killercup** [comment]
All announcements done! (Thanks @mre for the help!)

**Comment by killercup** [comment]
Thanks for the great talks and discussions!

@pizzamig, @gnunicorn do you want to post your slides? (Feel free to attach a file here)

**Comment by pizzamig** [comment]
It was a pleasure. Here my slides.
[rust_cologne_201811.pdf](https://github.com/Rustaceans/rust-cologne/files/2561139/rust_cologne_201811.pdf)
