### ISSUE TITLE
December 2018

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#70]
# ToDo

- [x] Settle for a date and location: **Wednesday 2018-12-05, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyxqbhb/)
  - [x] [website](https://rust.cologne/2018/12/05/rust-2018-eve.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1065555443202879488)
  - [x] [community calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=M3BxNGlkdWh1ZTBrcHVxczIwNnMyZjYwaGMgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/9zfky3/celebrate_rust_2018_eve_at_rustcologne_on_dec_5/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/rust-cologne-5-dec-2018-rust-2018-eve/22519)

# Invitation draft

```markdown
Title: RustCologne: Rust 2018 Eve

Dear Rustaceans,

Join us on Wednesday, December 5, 2018 at the C4 to celebrate Rust 2018 Eve! Because the very next day, December 6, is the official release date for Rust 1.31 – the first stable version of Rust that gives you access to the 2018 Edition.

With this final release of Rust in 2018 the year itself is drawing to an end, too. As is our tradition, we’ll be commemorating this with glühwein as well as other hot and cold beverages.

Not sure what “2018 Edition” means? Check out https://blog.rust-lang.org/2018/07/27/what-is-rust-2018.html for a general description, as well as https://rust-lang-nursery.github.io/edition-guide/ for an overview of major features since Rust 1.0.

Opening at 19:15, we welcome anyone to join us in discussing Rust and related topics.

We are looking forward to seeing you!

Yours, Pascal and Florian

PS: The meetup will be held in English, but a lot of attendees understand German, too.
```

# Rust News

- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
- RustFest

**Comment by killercup** [comment]
IIRC, this event will be hours before the release of the 2018 edition. Talks about that very welcome :)

**Comment by killercup** [comment]
Also, Glühwein?

**Comment by killercup** [comment]
After talking with @Florob last week, we decided to go with Glühwein/Punsch at the C4 and something Rust 2018 related. Added an initital draft in #71.

Right now, we don't have any talks planned, but would be very excited if **you** wanted to give a talk! Drop a comment here or reach out to one of us directly :)

**Comment by mre** [comment]
Maybe other people would like to give a talk, but if not, I could prepare one about "The State of Rust Ergonomics". It would basically be a "before-and-after" slideshow of different code examples, which show all the little papercuts that were fixed with Rust 2018.

If anyone wants to collaborate on that, contact me. We can collect code snippets together. 🤝

**Comment by killercup** [comment]
That sounds like a great idea, @mre! Maybe we can even do live "upgrade to 2018" thing?

I'll most likely be writing a post about cargo-fix in the lead up to Dec 6, so I can say a few words about how that works too (without slides… and preparation).

**Comment by killercup** [comment]
Announced on meetup, added to calendar, and tweeted about it. More after lunch unless @mre `hello`s before then :)

**Comment by killercup** [comment]
@Florob how do the Glühwein and punsch ingredients get to the C4? What should I buy/bring?

**Comment by Florob** [comment]
@killercup Well, what do you feel comfortable bringing? I have no good idea what do do for punsch, so that would be appreciated. I'll try to get Glühwein this evening. Either via the C4, or a nearby store.

**Comment by killercup** [comment]
@Florob Alright, I'll try to make punsch happen! We did something with tea and juice last year and it was drinkable, so I'm sure we can to a similar point tomorrow :)

**Comment by mre** [comment]
There is a Netto supermarket next door. Usually they have awesome "Kinderpunsch". We should be arriving at around 6:30pm tomorrow, so I could go there and buy a few bottles. Just send me a tweet tomorrow if we have a need for it. 🎅

**Comment by killercup** [comment]
Oh, that stuff is actually drinkable? I planned on going there to get the ingredients anyway. Getting the ready-made variant would be fine with me!

I'll try to be there a bit after 6, too. I'll try to meet you at Netto!

**Comment by mre** [comment]
> Oh, that stuff is actually drinkable? 

I'm addicted.

> I'll try to meet you at Netto!

Deal.

**Comment by killercup** [comment]
Thanks for the great evening!
