### ISSUE TITLE
January 2019

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#72]
# ToDo

- [x] Settle for a date and location: **Monday 2019-01-14, 19:15 CET** at C4
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2018-12-21**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyzcbdb/)
  - [x] [website](https://rust.cologne/2019/01/14/open-space.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1080143497116729350)
  - [x] [community calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NWVqY3ZiZ3UxanMwcjQyMWY0MG8wZDRycG0gYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/adyecv/rust_cologne_new_year_open_space_meetup_on/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/rust-cologe-new-year-meetup-on-january-14-2019/24007)

# Invitation draft

```markdown
Title: Rust Cologne: Happy New Year of Rust

Happy new year everyone!
We hope you celebrated the new year appropriately.
To give you some time to recover from that we have moved our next meetup a bit later in the month.

Our next **open space** style Meetup will be on **Monday, January 14th, 2019** at **19:15**,

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```

# Rust News

- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by killercup** [comment]
Hey, @dcz-self, random question: Any chance you'll be able to make it to this meetup on Jan 14? @spacekookie might join and would love to meet you. :)

**Comment by dcz-self** [comment]
On Tue, 01 Jan 2019 08:45:06 -0800
Pascal Hertleif <notifications@github.com> wrote:

> Hey, @dcz-self, random question: Any chance you'll be able to make it to this meetup on Jan 14? @spacekookie might join and would love to meet you. :)
> 

I actually will! Nice to know I'm gaining recognition ;)

**Comment by killercup** [comment]
Awesome! Be careful with that fame, though, or you'll spend this year answering weird questions about wayland from random people! ;)

Also: Happy new year!

> Am 01.01.2019 um 17:49 schrieb Dorota <notifications@github.com>:
> 
> On Tue, 01 Jan 2019 08:45:06 -0800

**Comment by spacekookie** [comment]
@dcz-self oh yay, looking forward to it!

**Comment by Florob** [comment]
Thanks to everyone who joined us. We had some fun discussions.
