### ISSUE TITLE
February 2019

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#75]
# ToDo

- [x] Settle for a date and location: **Wednesday 2019-02-06, 19:15 CET** at C4 (default: first Wednesday each month)
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **2019-01-21**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/vnwndpyzdbjb/)
  - [x] [website](https://rust.cologne/2019/02/06/zero-cost.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1088191219170242564)
  - [x] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: The Cost of Zero Cost

Our next meetup will be on **Wednesday, February 6, 2019** at the C4!
Opening at 19:15, we welcome anyone to join us in discussing Rust and related topics.

This time around we want to look at Rust's Zero-Cost Abstractions.
Performance more often than not doesn't matter. However, when it does you might want to analyze what your abstractions compile down to.
We'll start the evening off with a talk about analyzing generated code at different levels.
After that we'll have an open session analyzing our favorite abstractions together.
Do you have a great crate, or abstraction in your own code, but were never quite sure of its overhead?
Bring it along so we can have a look at it.

We are looking forward to seeing you. ☺

Yours,
Florian
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
