### ISSUE TITLE
March 2019

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#76]
# ToDo

- [x] Settle for a date and location: **Wednesday 2019-03-06, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **???**)
  - [x] [meetup](https://www.meetup.com/de-DE/RustCologne/events/vnwndpyzfbjb/)
  - [x] [website](https://rust.cologne/2019/03/06/live-coding.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1100848268605644800)
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: Live Coding

Our next meetup will be on **Wednesday, March 6, 2019** at 19:15!
This time around we'll do some live-coding in a group with one (alternating) coder.

Generally we'll focus on small simple tasks; porting small scripts, code katas,
AdventOfCode, Project Euler, …
Feel free to suggest your own tasks at the meetup.

This meetup will have an explicit focus on being beginner friendly.
We'll try to explain everything we write and answer questions.

**[You can register here](https://www.meetup.com/RustCologne/events/vnwndpyzfbjb/)**.

We are looking forward to seeing you. ☺

Yours,
Florian

―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- [Rust 1.33.0](https://blog.rust-lang.org/2019/02/28/Rust-1.33.0.html)

**Comment by mre** [comment]
Did we already settle for a date for the next meetup?
Also, I could ask around if anyone wants to present if you like.

**Comment by Florob** [comment]
Well, it's the first Wednesday each month so people can plan ahead, unless we have a reason to choose another date (including "Let's switch it up once in a while"). I'm not entirely sure if Ash Wednesday qualifies as a reason, we'd have to pick some Monday then.
Presentations would be very welcome. Otherwise I don't really have any ideas right now besides the Open Space default. And honestly I'm a bit reluctant to announce that since interest has been relatively low the last few times we tried it.

**Comment by mre** [comment]
> Well, it's the first Wednesday each month so people can plan ahead

Just asking because the date in the ToDo above is still Wednesday 2019-02-06 😉 

> Otherwise I don't really have any ideas right now besides the Open Space default.

How about we port some Go/Python tool to Rust?

E.g. this code: https://github.com/schollz/howmanypeoplearearound/blob/master/howmanypeoplearearound/analysis.py 

Or some code katas / a task from AdventOfCode?

**Comment by mre** [comment]
Another idea: I need a tool which sets environment variables whenever I leave/enter a directory. The scope of this tool is small enough so that we can write it in two hours and it's easy to extend (e.g adding support for running arbitrary code). Maybe that's something we could build.

**Comment by Florob** [comment]
> Just asking because the date in the ToDo above is still Wednesday 2019-02-06 wink

Oh, got it. That was just me mistyping the month though.

I think writng/porting some code sounds like a good idea. I'll write and post an announcement after work or over lunch.

**Comment by Florob** [comment]
Some additional task suggestions:
* [Throwing Darts for Pi](http://www.thephysicsmill.com/2014/05/03/throwing-darts-pi/)
* [Pi by Riemann integration (threaded, cf. slide 23)](http://babelmonkeys.de/~florob/talks/RUG-2015-10-28-Rust.pdf)
* [Project Euler](https://projecteuler.net)
* [Dining Philosophers Problem (threaded)](https://en.wikipedia.org/wiki/Dining_philosophers_problem)
* [rustlings (may actually be too easy)](https://github.com/rust-lang/rustlings)
