### ISSUE TITLE
April 2019

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#77]
# ToDo

- [x] Settle for a date and location: **Wednesday 2019-04-03, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **???**)
  - [x] [meetup](https://www.meetup.com/de-DE/RustCologne/events/vnwndpyzgbfb/)
  - [x] [website](https://rust.cologne/2019/09/03/sizeable-matter.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1111282628601229312)
  - [x] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: A Sizeable Matter

Dear Rustaceans,

we're happy to announce that our next meetup will be on **Wednesday, April 5, 2019** at **19:15**!

We have two talks dealing with the size of things in very different ways.
First we'll have a talk by Matthias Endler showing how to size up a file, by reimplementing a simple
`wc` clone in Rust.
Second Florian Zeitz is going to tell us about the size of types in Rust, particularly those only
known at runtime.

Afterwards there will be time for socializing and open discussion over some drinks.

We are looking forward to seeing you. :-)

Yours,
Florian
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by Florob** [comment]
We still need a topic for next month's meetup.
Based on the discussion with @mre at the last meetup I was thinking about preparing a talk on Un-/Dynamically Sized and Existential Types in Rust.
It would be nice if someone volunteered to do a second talk on a less involved topic.

**Comment by mre** [comment]
That sounds great!
I could contribute a short talk / live presentation on the pitfalls of writing a `wc` (word count) program and how Rust saves you from them. Based on a workshop I recently gave. Would that be interesting?
We could also ask on Meetup/Twitter if people want to present other topics.

**Comment by Florob** [comment]
@mre That also sounds nice. Could you prepare a short abstract for your talk that I can use in an announcement/on the website?
Generally we/I should make a habit of asking around for topics/talks more and earlier. This time around its a bit late for that.

**Comment by mre** [comment]
Sure thing:

> The simple programs are sometimes the trickiest. Take `wc` for example, which prints the number of words, lines, characters, and bytes of its input. It's surprisingly hard to write a correct version of that program. Let me show you why and how Rusts prevents most of the bugs by design. This interactive coding session is targeted towards beginners and intermediate Rust programmers.

**Comment by Florob** [comment]
@mre Thanks for the abstract.

The meetup is now announced on the website and meetup.com. Other channels to follow.
