### ISSUE TITLE
June 2019

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#80]
# ToDo

- [x] Settle for a date and location: **Monday 2019-06-10, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2019-06-06**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/tnrnbryzjbhb/)
  - [x] [website](https://rust.cologne/2019/06/10/four-years-of-rust.html)
  - [x] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: Four Years of Rust

Since our last meetup Rust has turned [4 years old][four] (Rust 1.0 was released May 15th, 2015).
In the meantime a lot has happened: We've seen 35 minor releases, many added features,
and a new [Rust Edition][edition].

At our upcoming meetup we want to celebrate 4 years of Rust, and tell each other about our favorite
language features. Everyone is invited to participate and give a quick lightning talk about their
most beloved Rust feature.
If you're still new to the language and just want to listen in and enjoy a drink, that's fine too.

Talks should be about 5 minutes long, with additional time for discussion afterwards.

The meetup will take place on **Monday, June 10th, 2019** at **19:15**.
This is different from our usual schedule due to a clash of events on the regular date.

We are looking forward to seeing you. :-)

Yours,
Florian

- - -

The meetup will likely be held in English, we will however reevaluate this at the beginning of the evening and may switch to German if desired.

[four]: https://blog.rust-lang.org/2019/05/15/4-Years-Of-Rust.html
[edition]: https://doc.rust-lang.org/edition-guide/
```
# Rust News
- [Rust's fourth birthday](https://blog.rust-lang.org/2019/05/15/4-Years-Of-Rust.html)
  + May 15th
  + 4 years since 1.0
- decision on `await` syntax
  + field access like `future.await`
  + came out of lengthy discussion sparked by problems with precedence of `await future?`
  + implemented on nightly
- [Rust parallelism for non-C/C++ developers](https://medium.com/nearprotocol/rust-parallelism-for-non-c-c-developers-ec23f48b7e56)
- [Unsafe Code Guidelines Reference now available online](https://rust-lang.github.io/unsafe-code-guidelines/)
- [Rust 1.35.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1350-2019-05-23)
  + `Fn{,Once,Mut}` is now implemented for `Box<Fn{,Once,Mut}`
  + Threads show ID in `Debug` output
  + `dbg!()` can now be called without parameters
  + `contains()` method on ranges

**Comment by mre** [comment]
Do we have any talks yet? Maybe we should ask around on Twitter.
If we can't find a speaker, I could do a talk about Rust and WebAssembly.
It's an adaption of [a talk I gave two weeks ago at the Web Engineering meetup](https://www.meetup.com/Web-Engineering-Duesseldorf/events/260995020/).
Open for suggestions.

**Comment by Florob** [comment]
@mre Thank you for the offer. I have something a bit different in mind for this time around, cf. the announcement in the issue.

**Comment by mre** [comment]
Ah alright. I mistook the announcement with the default template. Sounds great.

**Comment by kawogi** [comment]
The Wednesday in the ToDo list should probably be a Monday.

**Comment by kawogi** [comment]
I just noticed that this is a public holiday, so I won't be able to attend (once more).

**Comment by rabite0** [comment]
Here are the slides from yesterday. I included both the shorter version from yesterday, as well as a longer version which also contains some more basic stuff in the beginning. The org-file, a latex file created from that, and the pictures are in there too, if case you want do any changes.

[rust-talk.zip](https://github.com/Rustaceans/rust-cologne/files/3276748/rust-talk.zip)

**Comment by mre** [comment]
Nice! Thanks @rabite0.
