### ISSUE TITLE
July 2019

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#81]
# ToDo

- [x] Settle for a date and location: **Wednesday 2019-07-03, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2019-06-19**)
  - [x] [meetup]
  - [x] [website]
  - [x] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: Don't panic

Rejoice! This month we'll have our 42nd meetup. So fill your towel with topics,
avoid the Ravenous Bugblatter Beast of Traal, and make your way to our
**open space** style meetup on **Wednesday, July 3rd, 2019** at **19:15**,

What is an open space? Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

We are looking forward to seeing you. :-)

```
# Rust News
- [The Typestate Pattern in Rust](http://cliffle.com/blog/rust-typestate/)
 - [Real Time For the Masses goes multi-core](https://blog.japaric.io/multicore-rtfm/)

**Comment by Florob** [comment]
This will be (by my count) our 42nd meetup. So something that roughly fits a "Don't panic!" theme might be nice: error handling, `panic!()`ing, etc.
