### ISSUE TITLE
August 2019

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#82]
# ToDo

- [x] Settle for a date and location: **Wednesday 2019-08-07, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **???**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/tnrnbryzlbkb/)
  - [x] [website](https://rust.cologne/2019/08/07/fast-safe-both.html)
  - [ ] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: Safe? Fast? Both?

Dear Rustaceans,

we're happy to announce that our next meetup will be on Wednesday, August 7th, 2019 at 19:15!

This time we'll have two talks:
Matthias Endler will talk to us about using Rust to build applications with WebAssembly.
Florian Zeitz will contrast the C programing language with Rust in terms of their safety
guarantees and resulting performance.

Afterwards there will be time for socializing and open discussion over some drinks.

We are looking forward to seeing you. :-)

Yours,
Florian

Abstracts:
# Matthias Endler - WebAssmebly
WebAssembly has the potential to change the way we write and deploy software in the future and Rust is in a great position to become the best language to target WebAssembly. Let me show you why I think both of these statements are true and why you should care. Featuring simple examples!

# Florian Zeitz - How defined is Rust?
C is notorious for its undefined behavior. It is relatively easy to void all program behavior by making a small error. Rust has no undefined behavior in its safe subset. Yet it has to deal with the same situations C makes undefined somehow, ideally without sacrificing performance. Also Rust's unsafe subset has its own set of undefined behavior. This talk will investigate how Rust deals with issues like oversized shift amounts, type punning, and integer overflow.
—
The meetup will likely be held in English, we will however reevaluate this at the beginning of the evening and may switch to German if desired.

```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by mre** [comment]
Any plans for talks yet? We can ask around a bit (on Twitter perhaps?).

I have a talk about WASM and a few Rust demos. Nothing special but maybe worth the 30 minutes. I have another one about emulators and Rust. This one is more like a lightning-talk but might be a good starting point for a conversation.

Other than that, I'd love to see a talk about the following topics:
* Hardware internals and low-level (@uwearzt recently [blogged a bit about Rust drivers](https://uwe-arzt.de/2019/rust-as5048a-driver/))
* Problems that beginners struggle with. 

If none of that sticks, we could go through the [Gentle Introduction to Rust](https://stevedonovan.github.io/rust-gentle-intro/print.html), which I recently discovered and which I like a lot?

**Comment by killercup** [comment]
I'm flying home for a family event next Wednesday and might show up :)

**Comment by mre** [comment]
Oh boy! 🎉

**Comment by Florob** [comment]
@mre I have a talk in mind I want to do contrasting Undefined Behavior in C with Rusts behavior in the same sort of situations. If you can send me a short abstract for the WASM talk I'll put out a proper announcement this evening. Meetup's automatic announcement has beaten me to it again, which is getting rather bothersome.

@killercup Yay, looking forward to seeing you.

**Comment by uwearzt** [comment]
@mre I have already prepared a talk about Rust embedded. Unfortunately i will not be able to attend on Wednesday, so hopefully in September.

**Comment by mre** [comment]
@Florob can we just go with this?

> WebAssembly has the potential to change the way we write and deploy software in the future 
> and Rust is in a great position to become the best language to target WebAssembly.
> Let me show you why I think both of these statements are true and why you should care.
> Featuring simple examples!

**Comment by Florob** [comment]
@mre We can always try :stuck_out_tongue: Thanks

**Comment by Florob** [comment]
@mre Can you send me (a link to) your slides so I can put them on the website?

**Comment by mre** [comment]
[Here you go](https://github.com/mre/wasm/)
