### ISSUE TITLE
September 2019

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#83]
# ToDo

- [x] Settle for a date and location: **Wednesday 2019-09-04, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **2019-08-21**)
  - [ ] [meetup]
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday YYYY-MM-DD, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by Florob** [comment]
@uwearzt How is the Rust embedded talk coming along?

**Comment by uwearzt** [comment]
@Florob started the preparation of my talk today, see https://github.com/uwearzt/embedded-rust

**Comment by Florob** [comment]
@uwearzt Well, the real question is do you think you'll want to do it/have it finished by the next meetup? If so it would be great if you could write up a short abstract for the announcement.

Generally I've been thinking about doing an/my introduction to Rust talk at the next meetup.
So we'd have a generic introduction to Rust, followed by one to embedded Rust.

**Comment by uwearzt** [comment]
https://github.com/uwearzt/embedded-rust
