### ISSUE TITLE
October 2019

### ISSUE THREAD

**Issue by uwearzt** [Rustaceans/rust-cologne#84]
# ToDo

- [x] Settle for a date and location: **Wednesday 2019-10-02, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2019-09-18**)
  - [x] [meetup]
  - [x] [website]
  - [ ] [twitter]
  - [x] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday YYYY-MM-DD, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- [rust.cologne](rust.cologne) has moved to new DNS 
- [docs.rs changes](https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html)
- [RustConf 2019 Videos](https://www.youtube.com/playlist?list=PL85XCvVPmGQhDOUIZBe6u388GydeACbTt)
- [rustup 1.20 will update to latest nightly with all required components](https://github.com/rust-lang/rustup.rs/pull/1997)
- [Awesome Rust Mentors](https://rustbeginners.github.io/awesome-rust-mentors/)
- [LLVM Blog: Closing the gap: cross-language LTO between Rust and C/C++](http://blog.llvm.org/2019/09/closing-gap-cross-language-lto-between.html)
- Rust was updated to LLVM 9.0.0
  + RISC-V no longer experimental
  + peephole optimizations for some byte swaps

**Comment by uwearzt** [comment]
Maybe also add the event to the [calendar](https://calendar.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc@group.calendar.google.com) for inclusion in the weekly Rust newsletter?
