### ISSUE TITLE
November 2019

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#86]
# ToDo

- [ ] Settle for a date and location: **Wednesday YYYY-MM-DD, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **???**)
  - [ ] [meetup]
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday YYYY-MM-DD, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- ["Inside Rust" Blog](https://blog.rust-lang.org/inside-rust/index.html)
- [rustup 1.20](https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html)
- [Call for blogs 2020](https://blog.rust-lang.org/2019/10/29/A-call-for-blogs-2020.html)
  + [Collection at Read Rust](https://readrust.net/rust-2020/)
- [ Completing the transition to the new borrow checker](https://blog.rust-lang.org/2019/11/01/nll-hard-errors.html)
  + Hits stable December 19th
