### ISSUE TITLE
December 2019 - Christmas.await?

### ISSUE THREAD

**Issue by mre** [Rustaceans/rust-cologne#88]
I'm not a organizer, but I just had this idea that we should go to the Christmas market again in December. We could talk about Rust and enjoy the cozy atmosphere.
Does that sound interesting?
We could also meet in Düsseldorf for a change, which has a particularly nice Christmas market. 🎅 
Proposing December 4th as it's the first Wednesday in December.

**Comment by mre** [comment]
Here's our usual announcement that we could edit. (Pasted here just so we don't forget.)

---

# ToDo

- [ ] Settle for a date and location: **Wednesday YYYY-MM-DD, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **???**)
  - [ ] [meetup]
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday YYYY-MM-DD, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by kawogi** [comment]
The last time we went to the market it was rather _uncozy_
I believe @Florob already suggested to make another Glühwein-session at the CCC on the recent meetup.

**Comment by uwearzt** [comment]
I would also prefer the Glühwein session@C4.

BTW: some info to spread at the meetup: https://users.rust-lang.org/t/36c3-assembly-table-ccc-leipzig/34040

**Comment by Florob** [comment]
Yes, I said something to the effect of disliking the past Christmas market experiences. We're bound to either stand in line for glühwein, or in peoples way as a group.
I'm into the `.await` part though. I'd prepare a small talk about async/await/Futures, so I finally have an excuse to learn about them. Anybody with actual experience should feel free to take this from me though.
Obviously also glühwein/punch/$beverage and cookies.

**Comment by mre** [comment]
Makes sense. Can we do the announcement in the next days to get the word out?
