### ISSUE TITLE
January 2020

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#89]
# ToDo

- [ ] Settle for a date and location: **Monday 2020-01-13, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **???**)
  - [ ] [meetup]
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday YYYY-MM-DD, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
