### ISSUE TITLE
April 2020

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#91]
# ToDo

- [x] Settle for a date and location: **Wednesday 2020-04-??, 19:15 CET** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [ ] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **???**)
  - [ ] [meetup]
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: CGN ###: Save The Date

Dear Rustaceans,

our next **open space** style Meetup will be on **Wednesday 2020-04-??, 19:15 CET**.

Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](...)**.

We are looking forward to seeing you. :-)

Yours,
Pascal and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by Florob** [comment]
Any events in Cologne until April 10th have been [prohibited](https://www.stadt-koeln.de/politik-und-verwaltung/presse/corona-virus-neue-regelungen-fuer-veranstaltungen).
So at any rate we won't meet on the first Wednesday in April.
We'll see how the COVID-19 situation develops and if/when another date in April makes sense.

**Comment by mre** [comment]
Got an invite from meetup.com yesterday. Maybe we can pause the notifications for the time being to avoid confusion.

**Comment by Florob** [comment]
@mre As you may have noticed in the past, if it was up to me I'd have Meetup send no notifications without my consent. Unfortunately it does and I also can't find any settings to change that.
Canceling/deleting events is all I can do. Canceled the April meetup for now, might delete the whole event series in the future.

**Comment by mre** [comment]
Thanks. 😄

**Comment by mre** [comment]
Guess we can close this.
