### ISSUE TITLE
June 2022: Reboot

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#95]
# ToDo

- [x] Settle for a date and location: **Monday 2022-06-20, 19:15 CEST** online
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
  + Talk by @florob: Inline Assembly
  + Discussion about the future of the meetup
- [x] Final invitation (deadline **2022-06-08**)
  - [x] [meetup]
  - [x] [website]
  - [x] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: Reboot

Dear Rustaceans,

it has been a while. So we're all the more happy to announce that our next Meetup will be on
**Monday 2022-06-20, 19:15 CEST**.

It will take place online at <https://bbb.daten.reisen/b/flo-qcv-jgx-m5b>.

The meetup will be split into two major parts.

The first part will be a regular meetup. We'll talk about what has been happening in the Rust world.
Florob will be giving a presentation on Rust's Inline Assembly, a long awaited feature that has
finally been stabilized.

The second part will be focused on the future of the meetup. Shortly after its inception the
meetup had a relatively large organizer team of ~5 people. This had the benefit of distributing
the work as well as being able to bounce ideas for the meetup around.
As you may be aware that number had shrunk to a single remaining organizer.
We're now back to being a team of two.

In this part we want to discuss how the meetup has been organized up to this point and what the
future should look like. We'd be happy to see others from the community step up to help organize
the meetup. There will be discussion of what exactly that entails. (Spoiler: Mostly finding topics
and writing announcements)

**[You can optionally register here](...)**.

We are looking forward to hearing and seeing you. :-)

Yours,
Kai and Florian
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.

Talks:
Florob - "Stable Inline Assembly"
    Inline assembly is a fairly niche language construct, allowing to insert arbitrary instructions
    into a generated binary. Nonetheless it is often implemented in systems programming languages 
    to support cases where precise instruction sequences are required, such as embedded or crypto.
    Rust's support for it has only recently been stabilized and undergone major changes in the
    process. This talk will present what is available in stable Rust now and how we got there.
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by kawogi** [comment]
I'm not used to this procedure and I'm wondering how I could help to move this forward.
Even though we settled for "online" as location I think we should add a link or service we have in mind.
You suggested "Big Blue Button" in https://github.com/Rustaceans/rust-cologne/issues/93#issuecomment-1145875608

Shall we explicitly ping some of the former residents to gain some traction for this meetup?

**Comment by Florob** [comment]
> I'm not used to this procedure and I'm wondering how I could help to move this forward.

Honestly, just nudging me is already pretty good, since for this meetup specifically I'll have to do most work. I'll try to get you permissions on Meetup and Twitter eventually.

I think the most important thing right now is publishing an announcement. I've updated the issue with an initial draft. Proof reading and suggestions for improvements would be great.

**Comment by kawogi** [comment]
The invitation looks good to me. Ready to be sent.

**Comment by kawogi** [comment]
~~@Florob would you give me an update on the current status?~~
edit: huh - I could have sworn those checkmarks weren't there a few minutes ago :)
See you later.
