### ISSUE TITLE
August 2022: Meetup in Cologne

### ISSUE THREAD

**Issue by kawogi** [Rustaceans/rust-cologne#97]
# ToDo

- [x] Settle for a date and location: **Wednesday 2022-08-24, 19:15 CET** at C4
- [ ] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda (default: Open Space)
- [ ] Final invitation (deadline **??? T - 1 week**)
  - [x] [meetup](https://www.meetup.com/de-DE/rustcologne/events/287924732/)
  - [x] [website](https://rust.cologne/2022/08/24/avoiding-leakpocalypse.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1560605362302029825)
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: Avoiding the Leakpocalypse

Dear Rustaceans,

our next Meetup will be on **Wednesday 2022-08-24 19:15 CEST**.

Rust's ownership and borrowing system is what gives it its "super powers". It enables guaranteed
memory safety and freedom from data races.
At this meetup we want to look at this system, devoting one half to a beginner level introduction
and the other to its relation to threading. The later will also provide an introduction to scoped
threads introduced in Rust 1.63 (released August 11th).

Throwback to early 2015. The Rust 1.0 release is around the corner and most of the Rust talks are
talking about this revolutionary feature: scoped threads.
Threads that can only run as long as the scope they are created in exists.
They can access local variables without any locks, mutexes, reference counting, *and* fear of
use-after-free. It's amazing.

However, a bit later it turns out that leaking memory breaks this API. Leaking a thread will make
it run longer than its defining scope. Leaking is memory safe. Wasteful but safe.
So the API is reconsidered and ultimately dropped from Rust's 1.0 release.
Some dub it the "leakpocalypse". Sadness.

Fast forward to today. Rust 1.63 has been released and scoped threads are finally back and kicking
in the standard library with a revised API. At the meetup we'll look at this new API and how it
makes fork-join style parallelism a lot easier.

Any remaining time will be used as **open space**: Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](TODO)**.

We are looking forward to seeing you. :-)

Yours,
Kai and Florian
- - -
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
- - -
Due to COVID-19 still being around, bringing a face mask will be necessary. For the same reason we need to know how many people will attend the meetup. Please make sure to register and, in case you are no longer able to attend, cancel your registration. Thank you.
```
# Rust News
- [new rust release?](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)

**Comment by kawogi** [comment]
I'm not available before the 15th of August. Suggesting August 17th, 24th, 31th

**Comment by Florob** [comment]
The 17th is blocked for OSAMC, so (unless I'm forgetting something right now) the 24th seems the most plausible option to me.

**Comment by Florob** [comment]
I've confirmed the 24th with the C4.

Rust 1.63 will release on August 11th.
As a consequence I'd like to talk about [scoped threads](https://doc.rust-lang.org/nightly/std/thread/fn.scope.html). My idea would be doing an updated version of my introductory Rust talk ([initial version](https://babelmonkeys.de/~florob/talks/RUG-2015-10-28-Rust.pdf), [variation focusing on ownership](https://babelmonkeys.de/~florob/talks/RC-2020-02-05-rust-ownership.pdf)).
It can easily be split into two parts. The first one a general introduction to ownership, that I would probably do with large live coding parts showing rust-analyzer errors. The second one focusing on (ownership in the context of) threading, naturally leading into scoped threads.

I'd appreciate some feedback if that sounds like a sensible/interesting plan.

**Comment by mre** [comment]
Sounds very reasonable to me.

**Comment by kawogi** [comment]
Totally in favor!

Do we need another topic to fill the evening?

**Comment by Florob** [comment]
> Do we need another topic to fill the evening?

I don't think so. I'd rather have more time for open discussion, than have too much content again.

**Comment by Florob** [comment]
@kawogi I've updated the issue with an invitation draft. Could you proof-read? Sorry for being so late with this.

**Comment by kawogi** [comment]
Perfect, ready to go.

**Comment by Florob** [comment]
Announced. Meetup, homepage and twitter links in the issue comment.
