### ISSUE TITLE
October 2022

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#99]
# ToDo

- [x] Settle for a date and location: **Wednesday 2022-10-12, 19:15 CEST** at C4 (default: first Wednesday each month)
- [ ] Send "Save the Date" info (with link to this ticket)
- [X] Basic Agenda (default: Open Space)
- [x] Final invitation (deadline **2022-10-06**)
  - [x] [meetup](https://www.meetup.com/de-DE/rustcologne/events/288977470/)
  - [x] [website](https://rust.cologne/2022/10/12/iterators.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/1578679091288498177)
  - [ ] [community calendar]

# Invitation draft

```markdown
Title: Iterators in Rust

Dear Rustaceans,

our next Meetup will be on **Wednesday 2022-10-12, 19:15 CEST**.

We'll talk about some new features in version 1.64.0. Namely: C-types in `core`, `IntoFuture` and inheritance of settings in workspaces and maybe others.

The main part will be about Iterators: What are they good for, how to implement them on your own and problems that will occur when iterators provide mutable access to an underlying data structure.

Any remaining time will be used as **open space**: Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests. You can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](https://www.meetup.com/rustcologne/events/288977470/)**.

We are looking forward to seeing you. :-)

Yours,
Florian and Kai
―  
The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
―
Due to COVID-19 still being around there are some precautions we feel are necessary to make everyone at ease.

We have restricted the maximum number of participants to ensure social distancing is possible.
Accordingly we need to know how many people will attend the meetup.
Please make sure to register and, in case you are no longer able to attend, cancel your registration.

Additionally we generally expect participants to wear masks. During warm weather the venue allows for
decent ventilation. In this case participants may **unanimously** decide masking is not necessary.
```
# Rust News
* Rust 1.64.0
  - [Blog Post](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html)
  - [Release Notes](https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1640-2022-09-22)
  - `IntoFuture` has been stabilized. The `.await` keyword can now be used on anything implementing it
  - Types for C FFI are now defined in `core`/`alloc`
  - The deprecated `mem::uninitialized()` is now akin to `memset(buf, 0x01)` avoiding many cases of UB
  - Cargo: workspace inheritance
  - Rustup: `rust-analyzer` is now available via `rustup`
* [bstr 1.0](https://blog.burntsushi.net/bstr/): String operations for byte types (for not-quite UTF-8 data)
* [wasmtime 1.0](https://bytecodealliance.org/articles/wasmtime-1-0-fast-safe-and-production-ready)
* [clap 4.0](https://epage.github.io/blog/2022/09/clap4/): API cleanup/polish, polished help output
* [`let else` has been stabilized](https://github.com/rust-lang/rust/pull/93628), coming to Rust 1.65 (?)
* [Rust Style Team](https://blog.rust-lang.org/inside-rust/2022/09/29/announcing-the-rust-style-team.html)
* Initial Rust support merged into mainline Linux

**Comment by kawogi** [comment]
I think I could give a tour through Iterators. I'll see in the next days how much time I find to prepare something.
Other suggestions are still welcome.

**Comment by kawogi** [comment]
I'm a little late on this. Shall we opt for a very late announcement or shall we defer the date?

**Comment by Florob** [comment]
I've also been a bit AWOL for work reasons.

I think delaying might be preferable to doing things super short notice. I can ask for an alternative date at the C4 on Tuesday. That would probably be the 12th or 26th, if you have a preference between those.

**Comment by kawogi** [comment]
Both are fine for me. I'd go for the 12th if we have a choice.

**Comment by kawogi** [comment]
Any news on the date?

**Comment by Florob** [comment]
Yes, October 12th it is. We'll be sharing the space (not the room though) with the "Free Software Evening".
@kawogi can you write up an announcement?

**Comment by kawogi** [comment]
Great, thanks.
Is the drafted version ok?

**Comment by Florob** [comment]
Uff… I feel really bad about having delayed this even further. My mail server somehow forgot how to IPv4, which led to a certain lack of GitHub notifications. And I noticed way to late.

The announcement looks fine to me, and good call on putting it out there.
